/**
 * This code configures the Expo project settings for deployment across iOS, Android, and Web platforms.
 * 
 * Defines platform-specific settings for iOS, Android, and Web including app name, version, icons, splash screen, and permissions.
 * Loads environment variables using dotenv to securely inject Firebase credentials and other runtime configuration.
 *
 * Firebase Integration:
 * The `extra` field pulls in Firebase environment variables (API key, auth domain, database URL, etc.) 
 *    from `.env` to enable backend connectivity across platforms.
 *
 * Generated by CoPilot AI
 */


// app.config.js
import 'dotenv/config';

export default {
  expo: {
    name: "Eat Like The Rainbow",
    slug: "ELTRFront",
    version: "1.0.1",
    orientation: "portrait",
    icon: "./app/assets/eltrLogo-IOS.png",
    splash: {
      image: "./app/assets/splash.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff",
    },
    updates: {
      fallbackToCacheTimeout: 0,
    },
    assetBundlePatterns: ["**/*"],
    
    ios: {
      bundleIdentifier: "com.eatliketherainbow.eatliketherainbow",
      buildNumber: "1.0.0",
      supportsTablet: true,
      infoPlist: {
        NSCameraUsageDescription:
          "This app uses the camera to scan barcodes of grocery items to pull their ingredients list.",
      },
    },
    
    android: {
      package: "com.eatliketherainbow.eatliketherainbow",
      versionCode: 1,
      permissions: [
        "CAMERA",
      ],
    },
    
    web: {
      favicon: "./app/assets/eltrLogo.png",
    },

    plugins: [
      [
        "expo-camera",
        {
          cameraPermission:
            "Allow Eat Like The Rainbow to access your camera for barcode scanning.",
        },
      ],
    ],

    extra: {
      API_KEY: process.env.API_KEY,
      AUTH_DOMAIN: process.env.AUTH_DOMAIN,
      DATABASE_URL: process.env.DATABASE_URL,
      PROJECT_ID: process.env.PROJECT_ID,
      MESSAGE_SENDER_ID: process.env.MESSAGE_SENDER_ID,
      APP_ID: process.env.APP_ID,
    },
  },
};
