/**
 * This code configures Babel for the Expo project to enable proper transpilation of JavaScript and React Native code.
 * 
 * It applies the Expo preset to support platform-specific features and includes the Reanimated plugin to resolve 
 *  a known white screen rendering issue.
 * Caching is enabled to improve build performance. The dotenv plugin is commented out but may be used for
 *  environment variable support in future builds.
 * 
 * Generated by CoPilot AI
 */

module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    // plugins: ['module:react-native-dotenv'],
    // new plugin configuration to fix white screen error
    plugins: ['react-native-reanimated/plugin'],
  };
};