/**
 * This code initializes an API client using the Apisauce library to communicate with the OpenFoodFacts database.
 * 
 * It sets a base URL for all requests and includes a custom User-Agent header to identify the app across platforms.
 * The configured client can be imported and used throughout the app to fetch food-related data such as ingredients and nutrition facts.
 * 
 * Generated by CoPilot AI
 */

import { create } from "apisauce";

const apiClient = create({
  baseURL: "https://us.openfoodfacts.org/api",
  headers: {
    "User-Agent": "ELTRApp - Android/IOS - Version 0.0",
  },
});

export default apiClient;
