/**
 * This code defines a function for retrieving product data from the OpenFoodFacts API using a barcode identifier.
 * 
 * It constructs a URL endpoint based on the barcode value and sends a GET request through the preconfigured API client.
 * The response typically includes nutritional information, ingredients, and other metadata about the scanned item.
 * 
 * Generated by CoPilot AI
 */

//note that there is a limit of 100 requests per minute
import client from "./client";

const getProduct = (barcode) => {
  const productURL = "/v0/product/" + barcode.data + ".json";

  return client.get(productURL);
};

export default {
  getProduct,
};
