/**
 * This component defines a reusable `AppButton` for the React Native app.
 * 
 * Features:
 * - Accepts `title`, `onPress`, and optional `color` props (defaulting to "primary")
 * - Styled with rounded corners, padding, and vertical spacing for consistent layout
 * - Displays bold, uppercase text using platform-specific fonts (Roboto for Android, Avenir for iOS)
 * 
 * This button enhances UI consistency and simplifies interaction handling across screens.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { StyleSheet, Platform, Text, TouchableOpacity } from "react-native";

import colors from "../config/colors";

function AppButton({ title, onPress, color = "primary" }) {
  return (
    <TouchableOpacity
      onPress={onPress}
      style={[styles.button, { backgroundColor: colors[color] }]}
    >
      <Text style={styles.buttonText}>{title}</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    height: 50,
    width: "100%",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    marginVertical: 10,
  },
  buttonText: {
    fontSize: 16,
    color: colors.white,
    textTransform: "uppercase",
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
  },
});

export default AppButton;
