/**
 * This component defines a reusable `AppButton` for the React Native app.
 * 
 * Features:
 * - Accepts `title`, `onPress`, and optional `color` props (defaulting to "primary")
 * - Styled with rounded corners, padding, and vertical spacing for consistent layout
 * - Displays bold, uppercase text using platform-specific fonts (Roboto for Android, Avenir for iOS)
 * 
 * This button enhances UI consistency and simplifies interaction handling across screens.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { StyleSheet, Platform, Text, TouchableOpacity, View, } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import colors from "../config/colors";

function AppButton({ title, onPress, color = "primary", style, leftAlign = false, showArrow = false, textStyle, }) {
  return (
    <TouchableOpacity
      onPress={onPress}
      style={[styles.button, { backgroundColor: colors[color] }, style]}
    >
      {/* NEW: Layout container */}
      <View
        style={[
          styles.content,
          leftAlign ? styles.leftAlign : styles.centerAlign,
        ]}
      >
        <Text
          style={[
            styles.buttonText,
            leftAlign ? styles.textLeft : styles.textCenter, textStyle,
          ]}
          numberOfLines={1}
        >
          {title}
        </Text>

        {/* Optional right-facing arrow on button*/}
        {showArrow && (
          <MaterialCommunityIcons
            name="chevron-right"
            size={24}
            color={colors.white}
            style={styles.icon}
          />
        )}
      </View>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    // height: 50,
    minHeight: 50,
    width: "100%",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    marginVertical: 10,
  },
  buttonText: {
    fontSize: 16,
    color: colors.white,
    textTransform: "uppercase",
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
  },
  // NEW
  content: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  centerAlign: {
    justifyContent: "center",
  },
  leftAlign: {
    justifyContent: "flex-start",
    paddingLeft: 1,
  },
  textCenter: {
    textAlign: "center",
    flex: 1,
  },
  textLeft: {
    textAlign: "left",
    flex: 1,
    marginLeft: 8,
  },
  icon: {
    marginRight: 4,
  },
});

export default AppButton;
