/**
 * This component defines a customizable `AppPicker` used to display a modal-based selection list in a React Native app.
 * 
 * Features:
 * - Displays a touchable input field with optional icon and placeholder or selected item label
 * - Opens a modal containing a scrollable `FlatList` of selectable items
 * - Supports custom item rendering via `PickerItemComponent` and multi-column layout
 * - Uses `Screen` wrapper for consistent modal styling and includes a close button
 * 
 * Props:
 * - `icon`: optional icon name for the picker field
 * - `placeholder`: text shown when no item is selected
 * - `items`: array of selectable items
 * - `numColumns`: number of columns in the modal list
 * - `onSelectItem`: callback when an item is selected
 * - `modalStyle`: optional styling for column layout
 * - `PickerItemComponent`: custom component to render each item
 * - `selectedItem`: currently selected item
 * - `width`: width of the picker field
 * 
 * This picker enhances user interaction by providing a clean, flexible selection interface.
 * 
 * Generated by CoPilot AI
 */

import React, { useState } from "react";
import {
  View,
  StyleSheet,
  TouchableWithoutFeedback,
  Modal,
  Button,
  FlatList,
} from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";

import defaultStyles from "../config/styles";
import AppText from "./AppText";
import Screen from "../components/Screen";
import PickerItem from "./PickerItem";

function AppPicker({
  icon,
  placeholder,
  items,
  numColumns = 1,
  onSelectItem,
  modalStyle,
  PickerItemComponent = PickerItem,
  selectedItem,
  width = "100%",
}) {
  const [modalVisible, setModalVisible] = useState(false);

  return (
    <>
      <TouchableWithoutFeedback onPress={() => setModalVisible(true)}>
        <View style={[styles.container, { width }]}>
          {icon && (
            <MaterialCommunityIcons
              name={icon}
              size={20}
              color={defaultStyles.colors.medium}
              style={styles.icon}
            />
          )}

          {selectedItem ? (
            <AppText style={styles.text}>{selectedItem.label}</AppText>
          ) : (
            <AppText style={styles.placeholder}>{placeholder}</AppText>
          )}
          <MaterialCommunityIcons
            name="plus-circle"
            size={20}
            color={defaultStyles.colors.eltrgreen}
          />
        </View>
      </TouchableWithoutFeedback>
      <Modal visible={modalVisible} animationType="slide">
        <Screen>
          <Button title="Close" onPress={() => setModalVisible(false)} />
          <FlatList
            columnWrapperStyle={modalStyle}
            numColumns={numColumns}
            data={items}
            keyExtractor={(item) => item.id.toString()}
            renderItem={({ item }) => (
              <PickerItemComponent
                item={item}
                onPress={() => {
                  setModalVisible(false);
                  onSelectItem(item);
                }}
              />
            )}
          />
        </Screen>
      </Modal>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    padding: 15,
    marginVertical: 10,
    alignItems: "center",
  },
  icon: {
    marginRight: 10,
  },
  text: {
    flex: 1,
    color: defaultStyles.colors.dark,
  },
  placeholder: {
    flex: 1,
    color: defaultStyles.colors.medium,
  },
});
export default AppPicker;
