/**
 * This component defines a reusable `AppTextInput` for form inputs in a React Native app.
 * 
 * Features:
 * - Optional icon displayed on the left using MaterialCommunityIcons
 * - Styled container with rounded corners, padding, and consistent spacing
 * - Customizable width (default is 100%)
 * - Applies default text styling and placeholder color from the app's shared style config
 * 
 * Props:
 * - `icon`: optional icon name to display
 * - `width`: sets the width of the input field
 * - `...otherProps`: passed directly to the underlying `TextInput` (e.g., `placeholder`, `secureTextEntry`)
 * 
 * This component ensures consistent styling and behavior across all text inputs in the app.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { View, StyleSheet, TextInput } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";

import defaultStyles from "../config/styles";

function AppTextInput({ icon, width = "100%", ...otherProps }) {
  return (
    <View style={[styles.container, { width }]}>
      {icon && (
        <MaterialCommunityIcons
          name={icon}
          size={20}
          color={defaultStyles.colors.medium}
          style={styles.icon}
        />
      )}
      <TextInput
        placeholderTextColor={defaultStyles.colors.medium}
        {...otherProps}
        // style={defaultStyles.text}
        style={[defaultStyles.text, styles.input]}
        includeFontPadding={true}
        textAlignVertical="center"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    width: "100%",
    backgroundColor: defaultStyles.colors.light,
    borderRadius: 10,
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginVertical: 10,
    alignItems: "center",
  },
  input: {
    width: "90%",
    // minHeight: 35,
    height: 35, 
    paddingVertical: 0,
  },
  icon: {
    marginRight: 10,
  },
});
export default AppTextInput;
