/**
 * This component defines a reusable `AppText` wrapper around React Native's `Text` component.
 * 
 * Features:
 * - Applies default text styling from the app's shared style configuration
 * - Accepts custom `style` overrides and additional props via `...otherProps`
 * - Renders any child content passed to it
 * 
 * This abstraction ensures consistent typography across the app while allowing flexible customization.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { Text } from "react-native";

import defaultStyles from "../config/styles";

function AppText({ children, style, ...otherProps }) {
  return (
    <Text style={[defaultStyles.text, style]} {...otherProps}>
      {children}
    </Text>
  );
}

export default AppText;
