/**
 * This component defines a reusable `Card` for displaying visual and textual content in a React Native app.
 * 
 * Features:
 * - Displays an image at the top with fixed height and full width
 * - Shows a title and subtitle below the image inside a padded container
 * - Uses `AppText` for consistent typography and limits each line to one row
 * - Styled with rounded corners, white background, and vertical spacing
 * 
 * Props:
 * - `title`: main heading text
 * - `subTitle`: secondary descriptive text
 * - `image`: image source object (e.g., require or URI)
 * 
 * This component is ideal for showcasing food items, products, or educational content in a clean, card-style layout.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { View, StyleSheet, Image } from "react-native";

import colors from "../config/colors";
import AppText from "./AppText";

function Card({ title, subTitle, image }) {
  return (
    <View style={styles.card}>
      <Image style={styles.image} source={image} />
      <View style={styles.detailsContainer}>
        <AppText numberOfLines={1} style={styles.title}>
          {title}
        </AppText>
        <AppText numberOfLines={1} style={styles.subTitle}>
          {subTitle}
        </AppText>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    borderRadius: 15,
    backgroundColor: colors.white,
    marginBottom: 20,
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: 200,
  },
  detailsContainer: {
    padding: 20,
  },
  title: {
    marginBottom: 7,
  },
  subTitle: {
    color: colors.secondary,
    fontWeight: "bold",
  },
});

export default Card;
