/**
 * This component defines a `CategoryPickerItem` used within a custom picker modal to display selectable categories.
 * 
 * Features:
 * - Renders a large icon using the `Icon` component with customizable background color and icon name
 * - Displays the category label below the icon using `AppText`
 * - Wraps the item in a `TouchableOpacity` to handle selection via the `onPress` callback
 * 
 * Props:
 * - `item`: an object containing `label`, `icon`, and `backgroundColor` properties
 * - `onPress`: function to execute when the item is tapped
 * 
 * This component is ideal for grid-style category selection in forms or onboarding flows.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { View, StyleSheet, TouchableOpacity } from "react-native";
import AppText from "./AppText";

import Icon from "./Icon";

function CategoryPickerItem({ item, onPress }) {
  return (
    <TouchableOpacity style={styles.container} onPress={onPress}>
      <Icon backgroundColor={item.backgroundColor} name={item.icon} size={80} />
      <AppText style={styles.text}>{item.label}</AppText>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    width: "33%",
    paddingVertical: 15,
  },
  text: {
    marginTop: 5,
    textAlign: "center",
  },
});

export default CategoryPickerItem;
