/**
 * This component defines a reusable `ChildButtonFood` used in the Child Mode food-related screens of a React Native app.
 * 
 * Features:
 * - Rounded, medium-height button with full width and customizable background color (default: "eltrdarkblue")
 * - Bold, uppercase label text styled for readability across platforms
 * - Executes the `onPress` callback when tapped
 * 
 * Props:
 * - `title`: button label text
 * - `onPress`: function to execute on tap
 * - `color`: optional color key from the app's color palette
 * 
 * This button is ideal for interactive food exploration activities in child-friendly interfaces.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { StyleSheet, Platform, Text, TouchableOpacity } from "react-native";

import colors from "../config/colors";

function ChildButtonFood({ title, onPress, color = "eltrdarkblue" }) {
  return (
    <TouchableOpacity
      onPress={onPress}
      style={[styles.button, { backgroundColor: colors[color] }]}
    >
      <Text style={styles.buttonText}>{title}</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    height: 50,
    width: "100%",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    fontSize: 16,
    color: colors.white,
    textTransform: "uppercase",
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
  },
});

export default ChildButtonFood;
