/**
 * This component defines a large, visually engaging `ChildButtonLarge` used in Child Mode screens of a React Native app.
 * 
 * Features:
 * - Oversized button with rounded corners, shadow effects, and vibrant background color (default: "eltrapricot")
 * - Bold, centered label text using `AppText` for consistent styling
 * - Executes the `onPress` callback when tapped
 * 
 * Props:
 * - `title`: button label text
 * - `onPress`: function to execute on tap
 * - `color`: optional color key from the app's palette
 * - `screenName`: unused prop (can be removed or integrated for navigation if needed)
 * 
 * This button is ideal for child-friendly interfaces where large touch targets and playful design enhance usability.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { StyleSheet, Platform, TouchableOpacity } from "react-native";
import AppText from "./AppText";
import colors from "../config/colors";
import { useNavigation } from '@react-navigation/native';

function ChildButtonLarge({ title, onPress, color = "eltrapricot", screenName }) {
    const navigation = useNavigation();

  return (
    <TouchableOpacity
    onPress={onPress}
    style={[styles.button, { backgroundColor: colors[color] }]}
    >
      <AppText style={styles.buttonText}>{title}</AppText>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    borderWidth: 0.5,
    borderColor: colors.medium,
    borderRadius: 80,
    shadowColor: colors.white,
    shadowOpacity: 0.5,
    shadowOffset: {
      width: 0,
      height: 2
    },
    shadowRadius: 4,
    alignItems: "center", 
    width: 280,
    height: 130,
    justifyContent:"center",
    padding: 25,
    margin: 5,
  },

  buttonText: {
    fontSize: 50,
    color: colors.dark,
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
    textAlign:"center",
  },
});

export default ChildButtonLarge;
