/**
 * This component defines a reusable `ChildButtonSmall` used in Child Mode interfaces of a React Native app.
 * 
 * Features:
 * - Compact, vertically-oriented button with rounded corners and subtle shadow for a playful, tactile look
 * - Customizable background color (default: "eltrlightpink") from the app's color palette
 * - Bold, centered label text styled for readability across platforms
 * - Executes the `onPress` callback when tapped
 * 
 * Props:
 * - `title`: button label text
 * - `onPress`: function to execute on tap
 * - `color`: optional color key from the app's theme
 * 
 * This button is ideal for grid layouts or interactive menus in child-friendly screens, offering a fun and accessible touch target.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { StyleSheet, Platform, Text, TouchableOpacity } from "react-native";

import colors from "../config/colors";

function ChildButtonSmall({ title, onPress, color = "eltrlightpink" }) {
  return (
    <TouchableOpacity
      onPress={onPress}
      style={[styles.button, { backgroundColor: colors[color] }]}
    >
      <Text style={styles.buttonText}>{title}</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    borderWidth: 0.5,
    borderColor: colors.medium,
    borderRadius: 50,
    shadowColor: colors.white,
    shadowOpacity: 0.5,
    shadowOffset: {
      width: 0,
      height: 2
    },
      shadowRadius: 4,
      alignItems: "center", 
      width: 140,
      height: 180,
      justifyContent:"center",
      margin: 5
      //padding: 25,
      //marginVertical: 10,
  },

  buttonText: {
    fontSize: 24,
    color: colors.dark,
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
    textAlign:"center",
  },
});

export default ChildButtonSmall;
