/**
 * This component defines a reusable `ChildBackButton` tailored for Child Mode navigation in a React Native app.
 * 
 * Features:
 * - Large, rounded button with customizable background color (defaulting to "eltrgreen")
 * - Bold, uppercase label text styled for readability and consistency across platforms
 * - Executes the `onPress` callback when tapped
 * 
 * Props:
 * - `title`: button label text
 * - `onPress`: function to execute on tap
 * - `color`: optional color key from the app's color config
 * 
 * This button provides a friendly and accessible way for children to navigate back or exit screens.
 * 
 * Generated by CoPilot AI
 */


import React from "react";
import { StyleSheet, Platform, Text, TouchableOpacity } from "react-native";

import colors from "../config/colors";

function ChildBackButton({ title, onPress, color = "eltrgreen" }) {
  return (
    <TouchableOpacity
      onPress={onPress}
      style={[styles.button, { backgroundColor: colors[color] }]}
    >
      <Text style={styles.buttonText}>{title}</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    height: 70,
    width: "100%",
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
  },
  buttonText: {
    fontSize: 16,
    color: colors.white,
    textTransform: "uppercase",
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
  },
});

export default ChildBackButton;
