/**
 * This component defines a reusable `ChildButtonBottom` used in Child Mode screens for bottom-aligned actions.
 * 
 * Features:
 * - Full-width button with customizable background color (defaulting to "secondary")
 * - Bold, uppercase label text styled for readability across platforms
 * - Executes the `onPress` callback when tapped
 * 
 * Props:
 * - `title`: button label text
 * - `onPress`: function to execute on tap
 * - `color`: optional color key from the app's color config
 * 
 * This button is ideal for prominent actions in child-friendly interfaces, such as progressing through games or confirming choices.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { StyleSheet, Platform, Text, TouchableOpacity } from "react-native";

import colors from "../config/colors";

function ChildButtonBottom({ title, onPress, color = "secondary" }) {
  return (
    <TouchableOpacity
      onPress={onPress}
      style={[styles.button, { backgroundColor: colors[color] }]}
    >
      <Text style={styles.buttonText}>{title}</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  button: {
    height: 70,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
  },
  buttonText: {
    fontSize: 16,
    color: colors.white,
    textTransform: "uppercase",
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
  },
});

export default ChildButtonBottom;
