/**
 * This component defines a reusable `Icon` used to display circular icons with customizable styling.
 * 
 * Features:
 * - Renders a MaterialCommunityIcons icon centered inside a circular background
 * - Accepts customizable `name`, `size`, `backgroundColor`, and `iconColor` props
 * - Icon size is automatically scaled to 50% of the container size for visual balance
 * 
 * Props:
 * - `name`: icon name from MaterialCommunityIcons
 * - `size`: diameter of the circular container (default: 40)
 * - `backgroundColor`: background color of the circle (default: black)
 * - `iconColor`: color of the icon itself (default: white)
 * 
 * This component is ideal for use in pickers, buttons, or category indicators where visual clarity and consistency are important.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { StyleSheet, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";

function Icon({
  name,
  size = 40,
  backgroundColor = "#000",
  iconColor = "#fff",
}) {
  return (
    <View
      style={{
        width: size,
        height: size,
        borderRadius: size / 2,
        backgroundColor,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <MaterialCommunityIcons
        name={name}
        color={iconColor}
        size={size * 0.5}
      ></MaterialCommunityIcons>
    </View>
  );
}

export default Icon;
