/**
 * This component defines a simple `PickerItem` used within a modal picker interface.
 * 
 * Features:
 * - Displays the `label` of an `item` using the `AppText` component
 * - Wraps the text in a `TouchableOpacity` to handle selection via the `onPress` callback
 * - Adds padding for touch-friendly spacing and visual clarity
 * 
 * Props:
 * - `item`: an object with a `label` property representing the display text
 * - `onPress`: function to execute when the item is tapped
 * 
 * This component is typically used inside a `FlatList` within a modal to allow users to select from a list of options.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { TouchableOpacity, StyleSheet } from "react-native";
import AppText from "./AppText";

function PickerItem({ item, onPress }) {
  return (
    <TouchableOpacity onPress={onPress}>
      <AppText style={styles.text}>{item.label}</AppText>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  text: {
    padding: 20,
  },
});
export default PickerItem;
