/**
 * This component defines a reusable `Screen` wrapper for consistent layout and keyboard handling across the app.
 * 
 * Features:
 * - Uses `KeyboardAvoidingView` to prevent the keyboard from overlapping input fields
 * - Adjusts behavior based on platform (`padding` for iOS, `height` for Android)
 * - Applies top padding equal to the device's status bar height using Expo's `Constants`
 * - Wraps children inside a styled `View` and includes a flexible spacer to push content upward
 * 
 * Props:
 * - `children`: the content to render inside the screen
 * - `style`: optional custom styles to override or extend default layout
 * 
 * This component helps maintain a clean, responsive layout while managing keyboard interactions gracefully.
 * 
 * Generated by CoPilot AI
 */


// FOLLOWING SECTION IS NEW CODE

import React from "react";
import { Platform, KeyboardAvoidingView, StyleSheet, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useHeaderHeight } from "@react-navigation/elements";
import Constants from "expo-constants";
import colors from "../config/colors";

/*  
    If you ever need to add edge to edge componenets onto the screen
    (like an image background), try using the following code to manually 
    override the whole screen formatting this file provides:

    <Screen style={{ paddingTop: 0 }}>
      { custom full screen layout goes here }
    </Screen>
*/

function Screen({ children, style }) {
  const headerHeight = useHeaderHeight(); // returns 0 if no header is present on screen
  
  return (
    <SafeAreaView
      style={[
        styles.safeArea,
        // if there's no header on the screen, adds top padding equal to the status bar height. otherwise, if there is a header, no padding is added
        headerHeight === 0 && { paddingTop: Constants.statusBarHeight },
      ]}
      edges={["left", "right"]} // could add "bottom" also
    >
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        style={styles.keyboardContainer}
      >
        <View style={[styles.view, style]}>
          {children}
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.light,
    paddingTop: Platform.OS === "android" ? Constants.statusBarHeight : 0,
  },
  keyboardContainer: {
    flex: 1,
  },
  view: {
    flex: 1, 
  },
});

export default Screen;


// OLD SCREEN CODE BELOW
/* 
import React from "react";
import {Platform} from 'react-native';
import Constants from "expo-constants";
import {
  KeyboardAvoidingView,
  StyleSheet,
  View,
} from "react-native";
import { SafeAreaView } from 'react-native-safe-area-context';


function Screen({ children, style }) {
  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === "ios" ? "padding" : "height"}
      style={[styles.screen, style]}
    >
      <View style={[styles.view, style]}>{children}</View>
      <View style={{ flex: 1 }} />
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  screen: {
    paddingTop: Constants.statusBarHeight,
    flex: 1,
  },
  view: {
    justifyContent: "flex-end",
  },
});

export default Screen;
*/