/**
 * This component defines a reusable `Screen` wrapper for consistent layout and keyboard handling across the app.
 * 
 * Features:
 * - Uses `KeyboardAvoidingView` to prevent the keyboard from overlapping input fields
 * - Adjusts behavior based on platform (`padding` for iOS, `height` for Android)
 * - Applies top padding equal to the device's status bar height using Expo's `Constants`
 * - Wraps children inside a styled `View` and includes a flexible spacer to push content upward
 * 
 * Props:
 * - `children`: the content to render inside the screen
 * - `style`: optional custom styles to override or extend default layout
 * 
 * This component helps maintain a clean, responsive layout while managing keyboard interactions gracefully.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import {Platform} from 'react-native';
import Constants from "expo-constants";
import {
  KeyboardAvoidingView,
  SafeAreaView,
  StyleSheet,
  View,
} from "react-native";

function Screen({ children, style }) {
  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === "ios" ? "padding" : "height"}
      style={[styles.screen, style]}
    >
      <View style={[styles.view, style]}>{children}</View>
      <View style={{ flex: 1 }} />
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  screen: {
    paddingTop: Constants.statusBarHeight,
    flex: 1,
  },
  view: {
    justifyContent: "flex-end",
  },
});

export default Screen;
