import colors from "./colors";

export const budgets = [
    {
        id: "$25",
        color: "eltryellow",
        items: [
            { text: ["1 package ", { label: "chicken", url: "https://www.chefcathyzeis.com/tags/chicken/" }, " thighs (8 count)"] },
            { text: ["1 package ", { label: "pork", url: "https://www.chefcathyzeis.com/tags/pork/" }, " tenderloin"] },
            { text: ["1 carton large ", { label: "eggs", url: "https://www.chefcathyzeis.com/tags/eggs/" }] },
            { text: ["15 oz. bag ", { label: "pinto beans", url: "https://www.chefcathyzeis.com/tags/beans/" }] },
            { text: ["2 ", { label: "sweet potatoes", url: "https://www.chefcathyzeis.com/tags/sweet-potato/" }, " or Idaho potatoes"] },
            { text: ["1 crown fresh broccoli"] },
            { text: ["1 bunch ", { label: "bananas", url: "https://www.chefcathyzeis.com/tags/bananas/" }] },
            { text: ["1 box Cheerios"] },
            { text: ["1 gallon Silk Almond Milk with Vanilla OR 2% milk"] },
            { text: ["***If buying for kids under 18, please buy whole milk! Their brains and muscles need it for development."], italic: true },
            { text: ["2.37 oz. garlic powder"] },
            { text: ["2.37 oz. ground cinnamon"] },
            { text: ["2.37 oz. black pepper"] },
            { text: ["2.37 oz. ground cumin"] },
        ]
    },
    {
        id: "$50",
        color: "eltrpink",
        items: [
            { text: ["1 package ", { label: "chicken", url: "https://www.chefcathyzeis.com/tags/chicken/" }, " thighs (8 count)"] },
            { text: ["1 package ", { label: "pork", url: "https://www.chefcathyzeis.com/tags/pork/" }, " tenderloin"] },
            { text: ["1 frozen package wild caught ", { label: "salmon", url: "https://www.chefcathyzeis.com/tags/salmon/" }] },
            { text: ["1 carton large ", { label: "eggs", url: "https://www.chefcathyzeis.com/tags/eggs/" }] },
            { text: ["1-15 oz. bag ", { label: "pinto beans", url: "https://www.chefcathyzeis.com/tags/beans/" }] },
            { text: ["2 ", { label: "sweet potatoes", url: "https://www.chefcathyzeis.com/tags/sweet-potato/" }, " or Idaho potatoes"] },
            { text: ["1 lemon"] },
            { text: ["1 crown fresh broccoli"] },
            { text: ["1 carton fresh baby ", { label: "spinach", url: "https://www.chefcathyzeis.com/tags/spinach/" }] },
            { text: ["1 red ", { label: "onion", url: "https://www.chefcathyzeis.com/tags/onion/" }] },
            { text: ["1 bunch red grapes"] },
            { text: ["1 bunch ", { label: "bananas", url: "https://www.chefcathyzeis.com/tags/bananas/" }] },
            { text: ["1 carton Better Oats Steel Cut Instant Oatmeal with Flax Seeds"] },
            { text: ["1-12 oz. jar local honey"] },
            { text: ["1 box Cheerios"] },
            { text: ["1 gallon Silk Almond Milk with Vanilla OR 2% milk"] },
            { text: ["***If buying for kids under 18, please buy whole milk! Their brains and muscle need the whole milk to help with the development of their brain and muscles"], italic: true },
            { text: ["1-2.37 oz. garlic powder"] },
            { text: ["1-2.37 oz. ground cinnamon"] },
            { text: ["1-2.37 oz. black pepper"] },
            { text: ["1-2.37 oz. cayenne pepper"] },
            { text: ["1-2.37 oz. ground cumin"] },
        ]
    },
    {
        id: "$75",
        color: "eltrgreen",
        items: [
            { text: ["1 package ", { label: "chicken", url: "https://www.chefcathyzeis.com/tags/chicken/" }, " thighs (8 count)"] },
            { text: ["1 package ", { label: "pork", url: "https://www.chefcathyzeis.com/tags/pork/" }, " tenderloin"] },
            { text: ["1 frozen package wild caught ", { label: "salmon", url: "https://www.chefcathyzeis.com/tags/salmon/" }] },
            { text: ["1 carton large ", { label: "eggs", url: "https://www.chefcathyzeis.com/tags/eggs/" }] },
            { text: ["1-package All Natural ", { label: "Bacon", url: "https://www.chefcathyzeis.com/tags/bacon/" }, " (free of nitrates, nitrites and preservatives)"] },
            { text: ["1-lb. sliced ", { label: "turkey", url: "https://www.chefcathyzeis.com/tags/turkey/" }, " breast (free of nitrates, nitrites and preservatives)"] },
            { text: ["1-lb. baby swiss ", { label: "cheese", url: "https://www.chefcathyzeis.com/tags/cheese/" }] },
            { text: ["1 package Flatouts or Dave's Killer ", { label: "Bread", url: "https://www.chefcathyzeis.com/tags/bread/" }] },
            { text: ["1-16 oz. spicy mustard or Hellman's Mayo"] },
            { text: ["1-15 oz. bag ", { label: "pinto beans", url: "https://www.chefcathyzeis.com/tags/beans/" }] },
            { text: ["1 box wild or brown rice"] },
            { text: ["2 ", { label: "sweet potatoes", url: "https://www.chefcathyzeis.com/tags/sweet-potato/" }, " or Idaho potatoes"] },
            { text: ["1 lemon"] },
            { text: ["1 crown fresh broccoli"] },
            { text: ["1 carton fresh baby ", { label: "spinach", url: "https://www.chefcathyzeis.com/tags/spinach/" }] },
            { text: ["1 red ", { label: "onion", url: "https://www.chefcathyzeis.com/tags/onion/" }] },
            { text: ["2 large ", { label: "tomatoes", url: "https://www.chefcathyzeis.com/tags/tomato/" }] },
            { text: ["1 bunch red grapes"] },
            { text: ["1 bunch ", { label: "bananas", url: "https://www.chefcathyzeis.com/tags/bananas/" }] },
            { text: ["1 carton Better Oats Steel Cut Instant Oatmeal with Flax Seeds"] },
            { text: ["1-12 oz. jar local honey"] },
            { text: ["1 box Cheerios"] },
            { text: ["1 gallon Silk Almond Milk with Vanilla OR 2% milk"] },
            { text: ["***If buying for kids under 18, please buy whole milk! Their brains and muscle need the whole milk to help with the development of their brain and muscles"], italic: true },
            { text: ["1-2.37 oz. garlic powder"] },
            { text: ["1-2.37 oz. ground cinnamon"] },
            { text: ["1-2.37 oz. black pepper"] },
            { text: ["1-2.37 oz. cayenne pepper"] },
            { text: ["1-2.37 oz. ground cumin"] },
        ]
    },
    {
        id: "$100",
        color: "eltrpurple",
        items: [
            { text: ["1 package ", { label: "chicken", url: "https://www.chefcathyzeis.com/tags/chicken/" }, " thighs (8 count)"] },
            { text: ["1 package ", { label: "pork", url: "https://www.chefcathyzeis.com/tags/pork/" }, " tenderloin"] },
            { text: ["1 frozen package wild caught ", { label: "salmon", url: "https://www.chefcathyzeis.com/tags/salmon/" }] },
            { text: ["2 lbs. 80/20 ground ", { label: "beef", url: "https://www.chefcathyzeis.com/tags/beef/" }] },
            { text: ["1 carton large ", { label: "eggs", url: "https://www.chefcathyzeis.com/tags/eggs/" }] },
            { text: ["1-package All Natural ", { label: "Bacon", url: "https://www.chefcathyzeis.com/tags/bacon/" }, " (free of nitrates, nitrites and preservatives)"] },
            { text: ["1-lb. sliced ", { label: "turkey", url: "https://www.chefcathyzeis.com/tags/turkey/" }, " breast (free of nitrates, nitrites and preservatives)"] },
            { text: ["1-lb. baby swiss ", { label: "cheese", url: "https://www.chefcathyzeis.com/tags/cheese/" }] },
            { text: ["1-8 oz. Sargento cheddar ", { label: "cheese", url: "https://www.chefcathyzeis.com/tags/cheese/" }] },
            { text: ["1 package Flatouts or Dave's Killer ", { label: "Bread", url: "https://www.chefcathyzeis.com/tags/bread/" }] },
            { text: ["1-16 oz. spicy mustard or Hellman's Mayo"] },
            { text: ["1-15 oz. bag ", { label: "pinto beans", url: "https://www.chefcathyzeis.com/tags/beans/" }] },
            { text: ["1 box wild or brown rice"] },
            { text: ["2 ", { label: "sweet potatoes", url: "https://www.chefcathyzeis.com/tags/sweet-potato/" }, " or Idaho potatoes"] },
            { text: ["1 lemon"] },
            { text: ["2 yellow ", { label: "squash", url: "https://www.chefcathyzeis.com/tags/squash/" }] },
            { text: ["1 crown fresh broccoli"] },
            { text: ["1 carton fresh baby ", { label: "spinach", url: "https://www.chefcathyzeis.com/tags/spinach/" }] },
            { text: ["1 red ", { label: "onion", url: "https://www.chefcathyzeis.com/tags/onion/" }] },
            { text: ["2 large ", { label: "tomatoes", url: "https://www.chefcathyzeis.com/tags/tomato/" }] },
            { text: ["1 carton ", { label: "mushrooms", url: "https://www.chefcathyzeis.com/tags/mushrooms/" }] },
            { text: ["1 bunch red grapes"] },
            { text: ["1 bunch ", { label: "bananas", url: "https://www.chefcathyzeis.com/tags/bananas/" }] },
            { text: ["4 Red Delicious apples"] },
            { text: ["1-28 oz. Low-Sodium Creamy JIF ", { label: "peanut butter", url: "https://www.chefcathyzeis.com/tags/peanut-butter/" }] },
            { text: ["1 carton Better Oats Steel Cut Instant Oatmeal with Flax Seeds"] },
            { text: ["1-12 oz. jar local honey"] },
            { text: ["1 box Cheerios"] },
            { text: ["1 box Kashi Cinnamon Harvest cereal"] },
            { text: ["1 gallon Silk Almond Milk with Vanilla OR 2% milk"] },
            { text: ["***If buying for kids under 18, please buy whole milk! Their brains and muscle need the whole milk to help with the development of their brain and muscles"], italic: true },
            { text: ["1-2.37 oz. garlic powder"] },
            { text: ["1-2.37 oz. ground cinnamon"] },
            { text: ["1-2.37 oz. black pepper"] },
            { text: ["1-2.37 oz. cayenne pepper"] },
            { text: ["1-2.37 oz. chili powder"] },
            { text: ["1-2.37 oz. ground cumin"] },
            { text: ["1-2.37 oz. sea salt"] },
        ]
    },
    {
        id: "$125",
        color: "eltrorange",
        items: [
            { text: ["1 package ", { label: "chicken", url: "https://www.chefcathyzeis.com/tags/chicken/" }, " thighs (8 count)"] },
            { text: ["1 package ", { label: "pork", url: "https://www.chefcathyzeis.com/tags/pork/" }, " tenderloin"] },
            { text: ["1 frozen package wild caught ", { label: "salmon", url: "https://www.chefcathyzeis.com/tags/salmon/" }] },
            { text: ["2 lbs. 80/20 ground ", { label: "beef", url: "https://www.chefcathyzeis.com/tags/beef/" }] },
            { text: ["1 carton large ", { label: "eggs", url: "https://www.chefcathyzeis.com/tags/eggs/" }] },
            { text: ["1-package All Natural ", { label: "Bacon", url: "https://www.chefcathyzeis.com/tags/bacon/" }, " (free of nitrates, nitrites and preservatives)"] },
            { text: ["1-lb. sliced ", { label: "turkey", url: "https://www.chefcathyzeis.com/tags/turkey/" }, " breast (free of nitrates, nitrites and preservatives)"] },
            { text: ["1-lb. sliced ", { label: "ham", url: "https://www.chefcathyzeis.com/tags/ham/" }, " (free of nitrates, nitrites and preservatives)"] },
            { text: ["1-lb. baby swiss ", { label: "cheese", url: "https://www.chefcathyzeis.com/tags/cheese/" }] },
            { text: ["1-8 oz. Sargento cheddar ", { label: "cheese", url: "https://www.chefcathyzeis.com/tags/cheese/" }] },
            { text: ["1 package Flatouts or Dave's Killer ", { label: "Bread", url: "https://www.chefcathyzeis.com/tags/bread/" }] },
            { text: ["1-16 oz. spicy mustard or Hellman's Mayo"] },
            { text: ["1-15 oz. bag ", { label: "pinto beans", url: "https://www.chefcathyzeis.com/tags/beans/" }] },
            { text: ["1 box wild or brown rice"] },
            { text: ["2 ", { label: "sweet potatoes", url: "https://www.chefcathyzeis.com/tags/sweet-potato/" }, " or Idaho potatoes"] },
            { text: ["1 carton blue corn taco shells"] },
            { text: ["1 can ", { label: "black beans", url: "https://www.chefcathyzeis.com/tags/beans/" }] },
            { text: ["1 lemon"] },
            { text: ["2 yellow ", { label: "squash", url: "https://www.chefcathyzeis.com/tags/squash/" }] },
            { text: ["1 crown fresh broccoli"] },
            { text: ["1 carton fresh baby ", { label: "spinach", url: "https://www.chefcathyzeis.com/tags/spinach/" }] },
            { text: ["1 red ", { label: "onion", url: "https://www.chefcathyzeis.com/tags/onion/" }] },
            { text: ["1 white ", { label: "onion", url: "https://www.chefcathyzeis.com/tags/onion/" }] },
            { text: ["1 green pepper"] },
            { text: ["2 large ", { label: "tomatoes", url: "https://www.chefcathyzeis.com/tags/tomato/" }] },
            { text: ["1 carton ", { label: "mushrooms", url: "https://www.chefcathyzeis.com/tags/mushrooms/" }] },
            { text: ["1 bunch red grapes"] },
            { text: ["1 bunch ", { label: "bananas", url: "https://www.chefcathyzeis.com/tags/bananas/" }] },
            { text: ["4 Red Delicious apples"] },
            { text: ["1-8 oz. bag frozen blueberries"] },
            { text: ["1-28 oz. Low-Sodium Creamy JIF ", { label: "peanut butter", url: "https://www.chefcathyzeis.com/tags/peanut-butter/" }] },
            { text: ["1 carton Better Oats Steel Cut Instant Oatmeal with Flax Seeds"] },
            { text: ["1-12 oz. jar local honey"] },
            { text: ["1 box Cheerios"] },
            { text: ["1 box Kashi Cinnamon Harvest cereal"] },
            { text: ["1 gallon Silk Almond Milk with Vanilla OR 2% milk"] },
            { text: ["***If buying for kids under 18, please buy whole milk! Their brains and muscle need the whole milk to help with the development of their brain and muscles"], italic: true },
            { text: ["1-4 pack carton Oikos Triple Zero Berry Yogurt"] },
            { text: ["1-2.37 oz. garlic powder"] },
            { text: ["1-2.37 oz. ground cinnamon"] },
            { text: ["1-2.37 oz. black pepper"] },
            { text: ["1-2.37 oz. cayenne pepper"] },
            { text: ["1-2.37 oz. chili powder"] },
            { text: ["1-2.37 oz. ground cumin"] },
            { text: ["1-2.37 oz. sea salt"] },
        ]
    },
]