/**
 * This code defines a list of energy-boosting foods for use in the app's nutrition-related features.
 * 
 * Each item is labeled with a unique ID and a descriptive name, representing healthy snack options that support sustained energy levels.
 * This dataset can be used to educate users, populate food selection interfaces, or support condition-based dietary recommendations.
 * 
 * Generated by CoPilot AI
 */


export default {
    energy: [
        {
            id: 1,
            label: "Dried Fruit",
        },
        {
            id: 2,
            label: "Eggs (hard-boiled)",
        },
        {
            id: 3,
            label: "Lean Meats",
        },
        {
            id: 4,
            label: "Low-fat Cheeses",
        },
        {
            id: 5,
            label: "Milk",
        },
	{
	    id: 6,
	    label: "Nuts",
	},
	{
	    id: 7,
	    label: "Oatmeal",
	},
	{
	    id: 8,
	    label: "Seeds",
	},
	{
	    id: 9,
	    label: "Soybeans",
	},
	{
	    id: 10,
	    label: "Spinach",
	},
	{
	    id: 11,
	    label: "Sweet Potatoes",
	},
	{
	    id: 12,
	    label: "Trail Mix",
	},
	{
	    id: 13,
	    label: "Whole Grain Crackers",
	},
	{
	    id: 14,
	    label: "Yogurt",
	},
    ],
};