/**
 * This code defines a list of healthy fat-rich foods for use in the app's nutrition guidance features.
 * 
 * Each item is represented by an ID and label, covering a variety of sources including nuts, seeds, oils, fish, and dairy.
 * The dataset supports personalized dietary recommendations, educational content, and condition-based food analysis.
 * 
 * Generated by CoPilot AI
 */

export default {
    fats: [
	{
	     id: 1,
             label: "Almonds"
	},
	{
	     id: 2,
             label: "Atlantic Mackerel"
	},
	{
	     id: 3,
             label: "Avocado"
	},
	{
	     id: 4,
             label: "Avocado Oil"
	},
	{
	     id: 5,
             label: "Brazil Nuts"
	},
	{
	     id: 6,
             label: "Cashews"
	},
	{
	     id: 7,
             label: "Chia Seeds"
	},
	{
	     id: 8,
             label: "Cod"
	},
	{
	     id: 9,
             label: "Dark Chocolate"
	},
	{
	     id: 10,
             label: "Eggs"
	},
	{
	     id: 11,
             label: "Flaxseeds"
	},
	{
	     id: 12,
             label: "Hazelnuts"
	},
	{
	     id: 13,
             label: "Herring"
	},
	{
	     id: 14,
             label: "Light Tuna (canned)"
	},
	{
	     id: 15,
             label: "Olives"
	},
	{
	     id: 16,
             label: "Olive Oil"
	},
	{
	     id: 17,
             label: "Peanuts"
	},
	{
	     id: 18,
             label: "Peanut Butter"
	},
	{
	     id: 19,
             label: "Pecans"
	},
	{
	     id: 20,
             label: "Pistachios"
	},
	{
	     id: 21,
             label: "Pumpkin Seeds"
	},
	{
	     id: 22,
             label: "Salmon"
	},
	{
	     id: 23,
             label: "Sardines"
	},
	{
	     id: 24,
             label: "Sunflower Seeds"
	},
	{
	     id: 25,
             label: "Trout"
	},
	{
	     id: 26,
             label: "Walnuts"
	},
	{
	     id: 27,
             label: "Yogurt"
	},
	
     ],
};