
/**
 * This code initializes and configures Firebase services for use in a React Native application.
 * 
 * It uses the modular Firebase SDK to set up authentication (`auth`), Firestore (`db`), and Realtime Database (`rtdb`),
 * pulling configuration values from Expo constants for secure environment management.
 * The initialization is guarded to prevent re-instantiating Firebase if it's already been initialized.
 * Legacy Firebase initialization code using the compat SDK is included as comments for reference or fallback.
 * 
 * Generated by CoPilot AI
 */

// app/config/firebase.js

// NEW
import { initializeApp, getApps } from "firebase/app";
import { initializeAuth, getReactNativePersistence, getAuth, connectAuthEmulator, browserLocalPersistence } from "firebase/auth";
import { getDatabase } from "firebase/database";
import { getFirestore, connectFirestoreEmulator } from "firebase/firestore";
import Constants from "expo-constants";
import { Platform } from 'react-native'; // <--- IMPORT Platform for Android check
import AsyncStorage from '@react-native-async-storage/async-storage';
import { GoogleGenerativeAI } from "@google/generative-ai";



const {
  API_KEY,
  AUTH_DOMAIN,
  //DATABASE_URL, //currently don't have a db URL, since we aren't using realtime database
  PROJECT_ID,
  MESSAGE_SENDER_ID,
  APP_ID,
  GEMINI_API_KEY,
} = Constants.expoConfig.extra;

const firebaseConfig = {
  apiKey: API_KEY,
  authDomain: AUTH_DOMAIN,
  //databaseURL: DATABASE_URL,
  projectId: PROJECT_ID,
  messagingSenderId: MESSAGE_SENDER_ID,
  appId: APP_ID,
};

// Initialize Firebase (avoid reinitialization)
const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig);

// // Initialize Auth with persistence (needed for React Native)
// const auth =
//   initializeAuth(app, {
//     persistence: getReactNativePersistence(AsyncStorage),
//   });

// Initialize other services
//const auth = getAuth(app);
// FIX FOR WEB AUTH ERROR BELOW (rewrite of code)
let auth;
if (Platform.OS === "web") {
  // browser persistence
  auth = getAuth(app);
  auth.setPersistence(browserLocalPersistence);
} else {
  // persistence for other platforms
  auth = initializeAuth(app, {persistence: getReactNativePersistence(AsyncStorage)});
}
const db = getFirestore(app);
const rtdb = getDatabase(app);

const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
const geminiModel = genAI.getGenerativeModel({ 
    model: "gemini-2.5-flash",
    systemInstruction: `You are a friendly nutritional assistant. Your main goals are: 
    - suggest healthy food alternatives
    - provide budget friendly nutritional advice
    - provide dietary and nutritional budgeting assistance
    - answer questions about specific health conditions, dietary preferences, and allergies
    - avoid using complex medical terms, keep your answers friendly and concise (150 words or less) 
    - never provide medical help or diagnosis 
    - ensure you are giving easily digestible responses, while providing additional context if prompted
    - avoid recommending name brands and admit when you don't know something
    - format your responses to fit general mobile device ratios`
});

// Export for use in other files
export { app, auth, db, rtdb, geminiModel };

/*
if (__DEV__) { // __DEV__ is true in development builds
  const EMULATOR_HOST = Platform.OS === 'android' ? '10.0.2.2' : 'localhost';

  // connect Firebase Authentication to its emulator
  console.log(`[Firebase Config] Connecting to Auth Emulator at http://${EMULATOR_HOST}:9099`);
  connectAuthEmulator(auth, `http://${EMULATOR_HOST}:9099`);

  // connect Firestore to its emulator
  console.log(`[Firebase Config] Connecting to Firestore Emulator at http://${EMULATOR_HOST}:8080`);
  connectFirestoreEmulator(db, EMULATOR_HOST, 8080);

  // If you also want to connect Realtime Database to its emulator
  // console.log(`[Firebase Config] Connecting to Realtime Database Emulator at http://${EMULATOR_HOST}:9000`);
  // connectDatabaseEmulator(rtdb, EMULATOR_HOST, 9000);
}*/


export default app;

