// How the pictures are displayed and refrenced in foods.js

const imageAssets = {
  // FRUIT
  apple: require('../assets/food_images/fruit/apple.png'),
  apricot: require('../assets/food_images/fruit/apricot.png'),
  avacado: require('../assets/food_images/fruit/avacado.png'),
  banana: require('../assets/food_images/fruit/banana.png'),
  blackberry: require('../assets/food_images/fruit/blackberry.png'),
  blackgrape: require('../assets/food_images/fruit/blackgrape.png'),
  blueberry: require('../assets/food_images/fruit/blueberry.png'),
  cantaloupe: require('../assets/food_images/fruit/cantaloupe.png'),
  cherry: require('../assets/food_images/fruit/cherry.png'),
  coconut: require('../assets/food_images/fruit/coconut.png'),
  cranberry: require('../assets/food_images/fruit/cranberry.png'),
  cucumber: require('../assets/food_images/fruit/cucumber.png'),
  date: require('../assets/food_images/fruit/date.png'),
  fig: require('../assets/food_images/fruit/fig.png'),
  grapefruit: require('../assets/food_images/fruit/grapefruit.png'),
  greengrape: require('../assets/food_images/fruit/greengrape.png'),
  honeydew: require('../assets/food_images/fruit/honeydew.png'),
  jackfruit: require('../assets/food_images/fruit/jackfruit.png'),
  kiwi: require('../assets/food_images/fruit/kiwi.png'),
  lemon: require('../assets/food_images/fruit/lemon.png'),
  lime: require('../assets/food_images/fruit/lime.png'),
  mango: require('../assets/food_images/fruit/mango.png'),
  olive: require('../assets/food_images/fruit/olive.png'),
  orange: require('../assets/food_images/fruit/orange.png'),
  peach: require('../assets/food_images/fruit/peach.png'),
  pear: require('../assets/food_images/fruit/pear.png'),
  pineapple: require('../assets/food_images/fruit/pineapple.png'),
  plum: require('../assets/food_images/fruit/plum.png'),
  prune: require('../assets/food_images/fruit/prune.png'),
  pumpkin: require('../assets/food_images/fruit/pumpkin.png'),
  redgrape: require('../assets/food_images/fruit/redgrape.png'),
  squash: require('../assets/food_images/fruit/squash.png'),
  strawberry: require('../assets/food_images/fruit/strawberry.png'),
  tomato: require('../assets/food_images/fruit/tomato.png'),
  watermelon: require('../assets/food_images/fruit/watermelon.png'),

  kale: require('../assets/food_images/vegetable/kale.jpg'),
  eggplant: require('../assets/food_images/vegetable/eggplant.jpg'),
  butter: require('../assets/food_images/dairy/butter.jpg'),
  cheese: require('../assets/food_images/dairy/cheese.jpg'),
  black_bean: require('../assets/food_images/legume/black-bean.jpg'),
  chickpea: require('../assets/food_images/legume/chickpea.jpg'),
};

export default imageAssets;