import colors from "./colors";

export const TAG_COLORS = {
  // Protein related (blue / pink)
  "High Protein": colors.eltrpink,
  "For Athletes": colors.eltrdarkblue,
  "Builds Muscle": colors.eltrdarkblue,

  // Heart related (red)
  "Heart Healthy": colors.eltrred,
  "Heart Health": colors.eltrred,
  "Heart Disease Fighting": colors.eltrred,
  "Blood Pressure Support": colors.eltrred,
  "Lowers Cholesterol": colors.eltrred,

  // Metabolic & blood sugar (purple)
  "Blood Sugar Control": colors.eltrpurple,
  "Weight Loss": colors.eltrpurple,

  // Brain & eyes (blue)
  "Brain Health": colors.eltrdarkblue,
  "Eye Health": colors.eltrdarkblue,

  // Bones & minerals (orange)
  "Bone Health": colors.eltrorange,
  "Calcium": colors.eltrorange,
  "Minerals": colors.eltrorange,

  // Cancer, inflammation, & pain (purple)
  "Cancer Fighting": colors.eltrpurple,
  "Anti-Inflammatory": colors.eltrpurple,
  "Pain Relief": colors.eltrpurple,

  // Digestion & gut (yellow)
  "Gut Health": colors.eltryellow,
  "Digestive Health": colors.eltryellow,
  "IBS Friendly": colors.eltryellow,
  "High Fiber": colors.eltryellow,

  // Immunity & cells (green)
  "Immune Support": colors.eltrgreen,
  "Cell Health": colors.eltrgreen,

  // Pregnancy & birth support (pink)
  "Pregnancy Support": colors.eltrpink,
  "Birth Defect Prevention": colors.eltrpink,
  "Folate": colors.eltrpink,

  // Energy & fats (orange)
  "Healthy Fats": colors.eltrorange,
  "Energy Boost": colors.eltrorange,

  // Skin (pink)
  "Skin Health": colors.eltrpink,

  // Diet (green / orange)
  "Vegetarian": colors.eltrgreen,
  "Vegan": colors.eltrgreen,
  "Whole Grains": colors.eltrorange,
};


export const recipes = [
    {
        id: "pork-chop",
        title: "Baked, Bone-In Pork Chops",
        image: require("../assets/recipe_images/pork-chop.png"),
        tags: [
            "High Protein",
            "For Athletes",
            "Bone Health",
            "Heart Disease Fighting",
            "Eye Health",
            "Digestive Health",
            "Cancer Fighting",
            "Blood Sugar Control",
            "Weight Loss",
        ],
        prepTime: "10m",
        cookTime: "25m",
        totalTime: "35m",
        ingredients: [
            "3 Bone-In Pork Chops",
            "3 TBS Worcestershire Sauce",
            "2 tsp Dried Parsley",
            "1.5 tsp Garlic powder",
            "1 tsp Cayenne pepper",
        ],
        instructions: [
            "Preheat oven to 425 degrees Farenheit.",
            "Spray a 9 x 13″ glass pan and place pork chops in the pan.",
            "Top each chop with Worcestershire sauce and spices.",
            "Bake, uncovered, for 20-25 minutes or until golden brown and juices run clear.",
        ],
        description: [
            "The forgotten meat? Not in this house! Pork gets such a bad rap, yet it is one of the easiest and healthiest proteins around! Plus, it is really easy on the ‘ol grocery budget. Three, large, 1″ thick bone-in pork chops, all natural, I might add, cost me $5.85. That’s $ 1.95 for two adults and a bottomless 16 year old young man! Rather cost effective…don’t you think? Add a beautiful Brainiac Salad that is also on the website as a nice side dish and you have an amazingly delicious, healthy, inexpensive dinner! ~Enjoy!",
        ],
        notes: [
            "**Remember…pork is cooked medium! NOT well done! Let rest for 5 minutes and serve. YUM!",
        ],
    },
    {
        id: "roast-chicken",
        title: "Roasted Chicken, Asparagus, and Tomato",
        image: require("../assets/recipe_images/roast-chicken.png"),
        tags: [
            "High Protein",
            "Heart Healthy",
            "Blood Pressure Support",
            "Digestive Health",
            "High Fiber",
            "Pregnancy Support",
            "Birth Defect Prevention",
            "Folate",
            "Anti-Inflammatory",
            "Weight Loss",
        ],
        prepTime: "15m",
        cookTime: "40m",
        totalTime: "55m",
        ingredients: [
            "1 large Fresh bunch of asparagus ((washed and trimmed; cut off the bottom of the stem of each piece of asparagus. About 1\" up the stalk.",
            "2 medium Vine-ripened tomatoes ((cut into quarters))",
            "4 Chicken thighs ((skin removed))",
            "2 TBS Worcestershire sauce",
            "1 TBS Extra-virgin olive oil",
            "3 tsp Garlic powder ((divided))",
            "3 tsp Cayenne pepper ((divided))",
            "3 tsp Lemon & herb ((divided))",
        ],
        instructions: [
            "Preheat oven to 425° Farenheit",
            "Place the asparagus in a 9 X 12″ pan.",
            "Add olive oil and toss.",
            "Place the tomato quarters along the side of the pan.",
            "Sprinkle asparagus and tomatoes with 2 tsp of each of the spices.",
            "Lay the chicken thighs on top of the asparagus and pour Worcestershire Sauce onto the thighs.",
            "Sprinkle the thighs with the remaining spices and place into a 425° degree oven and cook for 40 minutes or until chicken is done and juices run clear.",
            "Let rest for 5 minutes and serve warm.",
        ],
        description: [
            "Loaded with protein, vitamins, antioxidants and nutrients, this dish will please any cardiologist! But what about the bad rap that using bottled sauces is not good for us? I’m glad you asked! First of all, not all sauces are the same and secondly, it depends on the ingredients. One of the ingredients in the Worcestershire Sauce I use in this recipe is tamarind. Tamarind Fruit is both fruit and a legume, which means it is full of fiber. The benefits of this little gem is amazing! Not only does it work in sweet dishes, but is also a famous addition in stir-fry. This great spice also has properties that may help in keeping your heart healthy as well. An old spice native to Africa and dating back hundreds of years, this bean-like pod plant has been used as medicine as well! Not only is it known to help with constipation, it helps relieve fever and promotes in digestion. Home to nutrients that help reduce inflammation, tamarind is a winner for all your dishes. So next time someone says that using a sauce like Worcestershire Sauce is bad for you, enlighten them with your superior knowledge about this magical ingredient! Until next time ~Enjoy!"
        ],
        notes: [

        ],
    },
    {
        id: "stuff-mushrooms",
        title: "Stuffed Mushrooms with Chicken",
        image: require("../assets/recipe_images/stuff-mushroom.png"),
        tags: [
            "High Protein",
            "Gut Health",
            "Brain Health",
            "Immune Support",
            "Cell Health",
            "Cancer Fighting",
            "Birth Defect Prevention",
        ],
        prepTime: "10m",
        cookTime: "25m",
        totalTime: "35m",
        ingredients: [
            "1 Large portobello mushroom ((Stem removed))",
            "5 Large black olives ((sliced))",
            "1/2 cup Dice tomato",
            "1 cup cooked chicken ((Use any leftovers you have on hand))",
            "1/4 cup Fresh baby spinach ((Enough to cover the stuffed mushroom))",
            "1 slice Dietz & Watson Baby Swiss Cheese (Cut on 1-1/2\" (The deli person will love that you know how you want it sliced.))",
            "1 tsp Garlic powder",
            "1 tsp Dried basil",
        ],
        instructions: [
            "Preheat oven to 425 degrees Farenheit.",
            "Spray the bottom of a small pan and place mushroom, bottom side up, into the pan.",
            "Add olives, tomato, and spices.",
            "Top with spinach and chicken and place slice cheese on top.",
            "Cook, uncovered, for 25 minutes or until cheese is golden brown. Let stand 3 minutes before serving. YUM!",
        ],
        description: [
            "Mushrooms are disease fighters. This is your anti-inflammatory food which is necessary in fighting all diseases but especially important for healthy gut function.",
            "Okay, here comes one of my all time favorites, and yes, you get some cheese! ~Enjoy!",
        ],
        notes: [

        ],
    },
    {
        id: "asparagus-soup",
        title: "Asparagus Soup",
        image: require("../assets/recipe_images/asparagus-soup.png"),
        tags: [
            "High Protein",
            "Heart Healthy",
            "Gut Health",
            "Cell Health",
            "Cancer Fighting",
            "Anti-Inflammatory",
            "Blood Sugar Control",
            "Weight Loss",
        ],
        prepTime: "3m",
        cookTime: "1.5m",
        totalTime: "4.5m",
        ingredients: [
            "1-14.5 oz can Asparagus spears*",
            "1/4 cup All Natural Chicken Broth",
            "1/2 tsp Dill Weed",
            "1/4 tsp Garlic powder",
            "1 TBS Heavy Whipping Cream**",
        ],
        instructions: [
            "In a blender, add all ingredients except heavy whipping cream and blend 15 seconds.",
            "Pour into a soup cup and heat on high in the microwave for 45 seconds.",
            "Repeat and stir.",
            "Add heavy whipping cream and serve warm.",
        ],
        description: [
            "Perfect for those suffering from an upset tummy due to chemo or just feeling yucky from treatments. Also good for aching joints. Perfect heart healthy snack!",
            "Shed those pounds with this vitamin packed mid-afternoon snack.",
            "Gut health hero with this recipe! ~Enjoy!",
        ],
        notes: [
            "Makes 2 servings.",
            "*Make sure that the ONLY ingredients are asparagus, water, and sea salt! Buying NO SALT added is my favorite!",
            "**You may also heat in a small pan on top of the stove in low-medium setting, stirring often, for 5 minutes. Serve warm.",
        ],
    },
    {
        id: "pumpkin-coconut",
        title: "Pumpkin-Coconut Smoothie",
        image: require("../assets/recipe_images/pumpkin-coconut.png"),
        tags: [
            "Vegan",
            "IBS Friendly",
            "High Protein",
            "Digestive Health",
            "High Fiber",
            "Healthy Fats",
            "Minerals",
            "Energy Boost",
            "Brain Health",
            "Eye Health",
            "Immune Support",
            "Skin Health",
            "Cancer Fighting",
            "Anti-Inflammatory",
            "Heart Health",
            "Bone Health",
            "Blood Sugar Control",
            "Weight Loss",
        ],
        prepTime: "5m",
        cookTime: "1m",
        totalTime: "6m",
        ingredients: [
            "1 medium Banana",
            "1/2 cup Pureed pumpkin ((Libby's 100% Pumpkin in a can is perfect to use!))",
            "1 cup Silk Almond-Coconut Milk",
            "2 tsp Ground Ginger",
        ],
        instructions: [
            "Peel the banana and place into a blender.",
            "Add all other ingredients and mix on high for 10 to 15 seconds or until smooth.",
            "Pour into a glass and drink.",
        ],
        description: [
            "Great for those who suffer from IBS and other digestion problems! ~Enjoy!",
        ],
        notes: [

        ],
    },
    {
        id: "sweet-potato",
        title: "Stuffed Sweet Potato",
        image: require("../assets/recipe_images/sweet-potato.png"),
        tags: [
            "Vegetarian",
            "IBS Friendly",
            "High Protein",
            "Builds Muscle",
            "Heart Healthy",
            "Lowers Cholesterol",
            "Eye Health",
            "Bone Health",
            "Cancer Fighting",
            "Anti-Inflammatory",
            "Pain Relief",
            "Blood Sugar Control",
            "Weight Loss",
        ],
        prepTime: "2m",
        cookTime: "5m",
        totalTime: "7m",
        ingredients: [
            "1 medium Sweet potato ((washed & patted dry))",
            "1 TBS 4% Cottage Cheese ((Lactose free is OK))",
            "1 tsp Dill weed",
        ],
        instructions: [
            "Wash the sweet potato and pat dry with a paper towel.",
            "Using a fork, poke the potato three time, creating holes.*",
            "Place on a paper napkin and microwave on high for 4-1/2 to 5 minutes or until done.",
            "Remove from microwave and place potato on a plate and split open.",
            "Spoon cottage cheese on the potato and sprinkle with dill weed.",
            "Serve warm.",
        ],
        description: [
            "Three ingredients creates one powerful meal!",
            "Heart Healthy… Full of potassium, an important electrolyte that helps regulate your heartbeat.",
            "Cancer Fighter… Rich in beta-carotene that may reduce the risk of developing certain cancers.",
            "IBS Friendly… Loaded with fiber and easy to digest.",
            "Helps in weight loss… Low calorie content, high in water and fiber that help you fill fuller longer. ~Enjoy!",
        ],
        notes: [
            "*This will allow the steam to evaporate when cooking in the microwave.",
        ],
    },
    {
        id: "beef-sliders",
        title: "Grass-Fed Beef Sliders",
        image: require("../assets/recipe_images/beef-sliders.png"),
        tags: [
            "High Protein",
            "For Athletes",
            "Whole Grains",
            "Bone Health",
            "Calcium",
            "Heart Health",
            "Blood Pressure Support",
            "Brain Health",
            "Gut Health",
            "Cell Health",
            "Cancer Fighting",
            "Folate",
            "Birth Defect Prevention",
        ],
        prepTime: "10m",
        cookTime: "15m",
        totalTime: "35m",
        ingredients: [
            "1 lb Grass-fed beef ((85% lean, 15% fat))",
            "2 slices Baby swiss cheese ((thin sliced and quartered))",
            "1 8-pack Small, whole wheat or multi-grain buns",
            "1/4 cup Red onion ((sliced thin))",
            "1 cup Baby spinach",
            "2 TBS Newman's Own Olive Oil & Vinegar Dressing",
            "1 TBS Worcestershire Sauce",
            "1/4 tsp Garlic powder",
            "1/4 tsp Lemon pepper",
            "1/4 tsp Cayenne pepper",
        ],
        instructions: [
            "Preheat oven to 425 degrees Farenheit.",
            "In a large bowl, mix meat with dressing, Worcestershire Sauce, garlic powder, lemon pepper, and cayenne pepper.",
            "Using your hands, make patties with the meat. Should make 8 small patties.",
            "Gently push the back of a spoon into the center of the patty, making a slight indenture.*",
            "Place patties in a shallow glass pan and bake at 425 for 15 minutes or until juices run clear.**",
            "Remove cooked patties from oven and top with cheese.",
            "Let stand for 5 minutes.",
            "Place cheese patty, sliced red onion, and baby spinach on a bun.",
            "Add your favorite condiment and serve warm.",
        ],
        description: [
            "Here’s a fun and healthy way to get some great protein in those you love! Perfect when the kiddos have friends over or for an easy afternoon snack when your athlete is beyond hungry! ~Enjoy!",
        ],
        notes: [
            "*This will keep the patty from folding into a small ball during cooking.",
            "**You can also grill patties on a hot grill.",
        ],
    },
    {
        id: "brainiac-salad",
        title: "Brainiac Salad",
        image: require("../assets/recipe_images/brainiac-salad.png"),
        tags: [
            "Vegetarian",
            "High Protein",
            "For Athletes",
            "Brain Health",
            "Eye Health",
            "Heart Health",
            "Lowers Cholesterol",
            "Healthy Fats",
            "Digestive Health",
            "High Fiber",
            "Cell Health",
            "Cancer Fighting",
            "Anti-Inflammatory",
            "Bone Health",
            "Birth Defect Prevention",
            "Weight Loss",
        ],
        prepTime: "5m",
        cookTime: "2m",
        totalTime: "7m",
        ingredients: [
            "1 cup fresh blueberries, rinsed",
            "1/4 cup Balsamic vinegar",
            "3 TBS extra virgin olive oil",
            "1/4 tsp garlic powder",
            "1/4 tsp ground ginger",
            "2 cups fresh baby spinach",
            "1/2 cup red cabbage, chopped",
            "1/4 tsp dried parsley ",
            "1/2 medium avocado, sliced",
            "1 medium boiled egg, diced",
        ],
        instructions: [
            "In a blender, blend the blueberries, Balsamic vinegar, olive oil, garlic powder, and ginger for 15 seconds.*",
            "In a large bowl, add dressing to the bottom.",
            "Add avocado, egg, the remaining spices, cabbage and spinach.",
            "Chill for up to 1 day in the refrigerator or toss and serve. (Building the salad this way will allow you to keep the salad chilled for up to one day without it getting soggy!)",
        ],
        description: [
            "Want to keep your focus and help improve your brain health? Then here’s your salad! ~Enjoy!",
        ],
        notes: [
            "*I like to have a few chunks of blueberries in my dressing but if you prefer, blend until the dressing is smooth, about 30 seconds for this consistency.",
        ],
    },
]