/**
 * This code defines a default styling configuration for the app, combining color themes and text formatting.
 * 
 * It imports a centralized color palette and sets a standard text style with platform-specific font selection—using "Roboto" for Android and "Avenir" for iOS.
 * This configuration ensures consistent visual design across devices and simplifies styling throughout the app.
 * 
 * Generated by CoPilot AI
 */

import { Platform } from "react-native";

import colors from "../config/colors";

export default {
  colors,
  text: {
    color: colors.dark,
    fontSize: 18,
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
  },
};
