/**
 * This file defines a comprehensive dataset of essential vitamins and minerals, including their health benefits and food sources.
 * 
 * Each entry contains:
 * - `label`: the nutrient name
 * - `use`: a brief description of its biological role or health impact
 * - `good`: a list of foods rich in that nutrient
 * 
 * The dataset spans various nutrients—from Vitamin A to Zinc—and supports features like personalized nutrition guidance, 
 *   condition-based dietary recommendations, and educational tools within the app.
 * 
 * Generated by CoPilot AI
 */

export default {
    vitamins: [
        {
            id: 1,
            label: "Vitamin A",
            use: "Plays an important role in bone growth and in the immune system",
            buttonColor: "#5F2879",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 2,
            label: "Vitamin B1",
            use: "Helps convert food into energy and is critical for nerve function",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 3,
            label: "Vitamin B2",
            use: "Helps convert food into energy. Needed for healthy skin, hair, blood, and brain",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 4,
            label: "Vitamin B3",
            use: "Helps convert food into energy. Essential for healthy skin, blood cells, brain, and nervous system",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 5,
            label: "Vitamin B5",
            use: "Helps convert food into energy. Helps make lipids (fats), neurotransmitters, steroid hormones, and hemoglobin",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 6,
            label: "Vitamin B6",
            use: "Aids in lowering homocysteine levels and may reduce the risk of heart disease",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 7,
            label: "Vitamin B12",
            use: "Aids in lowering homocysteine levels and may lower the risk of heart disease. Assists in making new cells",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 8,
            label: "Biotin",
            use: "Helps convert food into energy and synthesize glucose",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 9,
            label: "Vitamin C",
            use: "Long-term use of supplemental vitamin C may protect against cataracts. Helps make collagen, a connective tissue that knits together wounds and supports blood vessel walls",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 10,
            label: "Choline",
            use: "Helps make and release the neurotransmitter acetylcholine, which aids in many nerve and brain activities",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 11,
            label: "Vitamin D",
            use: "Helps maintain normal blood levels of calcium and phosphorus, which strengthen bones",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 12,
            label: "Vitamin E",
            use: "Acts as an antioxidant, neutralizing unstable molecules that can damage cells",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 13,
            label: "Vitamin Bg",
            use: "Helps prevent brain and spine birth defects when taken early in pregnancy",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 14,
            label: "Vitamin K",
            use: "Activates proteins and calcium essential to blood clotting. May help prevent hip fractures",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 15,
            label: "Calcium",
            use: "Builds and protects bones and teeth",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 16,
            label: "Chloride",
            use: "Balances fluids in the body",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 17,
            label: "Chronium",
            use: "Enhances the activity of insulin, helps maintain normal blood glucose levels, and is needed to free energy from glucose",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 18,
            label: "Copper",
            use: "Plays an important role in iron metabolism and immune system",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 19,
            label: "Fluoride",
            use: "Encourages strong bone formation. Keeps dental cavities from starting or worsening",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 20,
            label: "Iodine",
            use: "Part of thyroid hormone, which helps set body temperature and influences nerve and muscle function",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 21,
            label: "Iron",
            use: "Helps hemoglobin in red blood cells and myoglobin in muscle cells ferry oxygen throughout the body",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 22,
            label: "Magnesium",
            use: "Works with calcium in muscle contraction, blood clotting, and regulation of blood pressure",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 23,
            label: "Manganese",
            use: "Helps form bones. Helps metabolize amino acids, cholesterol, and carbohydrates",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 24,
            label: "Molybdenum",
            use: "Part of several enzymes, one of which helps ward off a form of severe neurological damage in infants",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 25,
            label: "Phosphorus",
            use: "Helps build and protect bones and teeth. Part of DNA and RNA. Helps convert food into energy",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 26,
            label: "Potassium",
            use: "Balances fluids in the body. Helps maintain steady heartbeat and send nerve impulses",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 27,
            label: "Selenium",
            use: "Acts as an antioxidant, neutralizing unstable molecules that can damage cells",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 28,
            label: "Sodium",
            use: "Balances fluids in the body. Helps send nerve impulses. Needed for muscle contractions",
            buttonColor: "#00BA71",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 29,
            label: "Sulfur",
            use: "Needed for healthy hair, skin, and nails",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2,
            ],
        },
        {
            id: 30,
            label: "Zinc",
            use: "Needed for immune system, taste, smell, and wound healing",
            buttonColor: "#F43545",
            linkTo: [
                1, 2,
            ],
        },
    ],
};
