/**
 * This file defines a comprehensive dataset of essential vitamins and minerals, including their health benefits and food sources.
 * 
 * Each entry contains:
 * - `label`: the nutrient name
 * - `use`: a brief description of its biological role or health impact
 * - `good`: a list of foods rich in that nutrient
 * 
 * The dataset spans various nutrients—from Vitamin A to Zinc—and supports features like personalized nutrition guidance, 
 *   condition-based dietary recommendations, and educational tools within the app.
 * 
 * Generated by CoPilot AI
 */


// Bone health: #5F2879
// Conversion: #ea9c60
// Brain Health: #00BA71
// Pigment: #FAD717
// Fluids: #8acff4
// Heart/Blood Health: #F43545
// Other: #F786AA

export default {
    vitamins: [
        {
            id: 1,
            label: "Vitamin A",
            use: "Plays an important role in bone growth and in the immune system",
            buttonColor: "#5F2879",
            linkTo: [
                0, 1, 2, 7, 8,
            ],
        },
        {
            id: 2,
            label: "Vitamin B1",
            use: "Helps convert food into energy and is critical for nerve function",
            buttonColor: "#ea9c60",
            linkTo: [
                0, 2, 3, 4, 5, 7, 8, 9, 10, 11,
            ],
        },
        {
            id: 3,
            label: "Vitamin B2",
            use: "Helps convert food into energy. Needed for healthy skin, hair, blood, and brain",
            buttonColor: "#ea9c60",
            linkTo: [
                0, 1, 2, 3, 4, 7, 8, 9, 11,
            ],
        },
        {
            id: 4,
            label: "Vitamin B3",
            use: "Helps convert food into energy. Essential for healthy skin, blood cells, brain, and nervous system",
            buttonColor: "#ea9c60",
            linkTo: [
                0, 1, 3, 4, 5, 7, 8, 9, 10, 11,
            ],
        },
        {
            id: 5,
            label: "Vitamin B5",
            use: "Helps convert food into energy. Helps make lipids (fats), neurotransmitters, steroid hormones, and hemoglobin",
            buttonColor: "#ea9c60",
            linkTo: [
                1, 2, 3, 10, 12,
            ],
        },
        {
            id: 6,
            label: "Vitamin B6",
            use: "Aids in lowering homocysteine levels and may reduce the risk of heart disease",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11,
            ],
        },
        {
            id: 7,
            label: "Vitamin B12",
            use: "Aids in lowering homocysteine levels and may lower the risk of heart disease. Assists in making new cells",
            buttonColor: "#F43545",
            linkTo: [
                2, 9, 10,
            ],
        },
        {
            id: 8,
            label: "Biotin",
            use: "Helps convert food into energy and synthesize glucose",
            buttonColor: "#ea9c60",
            linkTo: [
                3, 5,
            ],
        },
        {
            id: 9,
            label: "Vitamin C",
            use: "Long-term use of supplemental vitamin C may protect against cataracts. Helps make collagen, a connective tissue that knits together wounds and supports blood vessel walls",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 3, 7, 8,
            ],
        },
        {
            id: 10,
            label: "Choline",
            use: "Helps make and release the neurotransmitter acetylcholine, which aids in many nerve and brain activities",
            buttonColor: "#00BA71",
            linkTo: [
                2, 9, 10,
            ],
        },
        {
            id: 11,
            label: "Vitamin D",
            use: "Helps maintain normal blood levels of calcium and phosphorus, which strengthen bones",
            buttonColor: "#5F2879",
            linkTo: [
                2, 6, 9, 10,
            ],
        },
        {
            id: 12,
            label: "Vitamin E",
            use: "Acts as an antioxidant, neutralizing unstable molecules that can damage cells",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 4, 5, 6, 9, 10, 11, 12,
            ],
        },
        {
            id: 13,
            label: "Vitamin K",
            use: "Activates proteins and calcium essential to blood clotting. May help prevent hip fractures",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 2, 3, 6, 7, 8, 12,
            ],
        },
        {
            id: 14,
            label: "Calcium",
            use: "Builds and protects bones and teeth",
            buttonColor: "#5F2879",
            linkTo: [
                0, 1, 2, 3, 7, 8, 9, 10, 11,
            ],
        },
        {
            id: 15,
            label: "Chloride",
            use: "Balances fluids in the body",
            buttonColor: "#8acff4",
            linkTo: [
                7,
            ],
        },
        {
            id: 16,
            label: "Chronium",
            use: "Enhances the activity of insulin, helps maintain normal blood glucose levels, and is needed to free energy from glucose",
            buttonColor: "#F43545",
            linkTo: [
                0, 9,
            ],
        },
        {
            id: 17,
            label: "Copper",
            use: "Plays an important role in iron metabolism and immune system",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 2, 3, 4, 5, 9, 10, 12,
            ],
        },
        {
            id: 18,
            label: "Fluoride",
            use: "Encourages strong bone formation. Keeps dental cavities from starting or worsening",
            buttonColor: "#5F2879",
            linkTo: [
                0, 10,
            ],
        },
        {
            id: 19,
            label: "Iodine",
            use: "Part of thyroid hormone, which helps set body temperature and influences nerve and muscle function",
            buttonColor: "#8acff4",
            linkTo: [
                2, 10, 12,
            ],
        },
        {
            id: 20,
            label: "Iron",
            use: "Helps hemoglobin in red blood cells and myoglobin in muscle cells ferry oxygen throughout the body",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11,
            ],
        },
        {
            id: 21,
            label: "Magnesium",
            use: "Works with calcium in muscle contraction, blood clotting, and regulation of blood pressure",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11,
            ],
        },
        {
            id: 22,
            label: "Manganese",
            use: "Helps form bones. Helps metabolize amino acids, cholesterol, and carbohydrates",
            buttonColor: "#5F2879",
            linkTo: [
                0, 1, 3, 4, 5, 7, 8, 11,
            ],
        },
        {
            id: 23,
            label: "Molybdenum",
            use: "Part of several enzymes, one of which helps ward off a form of severe neurological damage in infants",
            buttonColor: "#00BA71",
            linkTo: [
                2, 3, 4,
            ],
        },
        {
            id: 24,
            label: "Phosphorus",
            use: "Helps build and protect bones and teeth. Part of DNA and RNA. Helps convert food into energy",
            buttonColor: "#5F2879",
            linkTo: [
                0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12,
            ],
        },
        {
            id: 25,
            label: "Potassium",
            use: "Balances fluids in the body. Helps maintain steady heartbeat and send nerve impulses",
            buttonColor: "#8acff4",
            linkTo: [
                0, 1, 2, 3, 4, 5, 7, 8, 9, 10,
            ],
        },
        {
            id: 26,
            label: "Selenium",
            use: "Acts as an antioxidant, neutralizing unstable molecules that can damage cells",
            buttonColor: "#F786AA",
            linkTo: [
                2, 4, 5, 9, 10, 11,
            ],
        },
        {
            id: 27,
            label: "Sodium",
            use: "Balances fluids in the body. Helps send nerve impulses. Needed for muscle contractions",
            buttonColor: "#8acff4",
            linkTo: [
                7, 9, 10, 11,
            ],
        },
        {
            id: 28,
            label: "Sulfur",
            use: "Needed for healthy hair, skin, and nails",
            buttonColor: "#F786AA",
            linkTo: [
                1, 3, 9, 10,
            ],
        },
        {
            id: 29,
            label: "Zinc",
            use: "Needed for immune system, taste, smell, and wound healing",
            buttonColor: "#F43545",
            linkTo: [
                2, 3, 4, 5, 7, 8, 9, 10, 11, 12,
            ],
        },
        {
            id: 30,
            label: "Vitamin B9",
            use: "Essential for DNA repair and red blood cell production.",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11,
            ],
        },
        {
            id: 31,
            label: "Lutein",
            use: "An orange-yellow antioxidant pigment that is important for eye health and muscle strength",
            buttonColor: "#FAD717",
            linkTo: [
                0, 1, 3, 7,
            ],
        },
        {
            id: 32,
            label: "Zeaxanthin",
            use: "An orange-yellow pigment found in fruits and vegetables. Promotes eye health.",
            buttonColor: "#FAD717",
            linkTo: [
                0, 1, 3, 7,
            ],
        },
        {
            id: 33,
            label: "Anthocyanin",
            use: "A red, purple, and blue antioxidant pigment found in fruits and vegetables. Helps to reduce inflammation, improve cardiovascular health, and reduces the risk of cancer.",
            buttonColor: "#FAD717",
            linkTo: [
                0, 1,
            ],
        },
        {
            id: 34,
            label: "Anthoxanthin",
            use: "A white pigment found in fruits and vegetables. Helps reduce cholesterol and blood pressure.",
            buttonColor: "#FAD717",
            linkTo: [
                0, 1,
            ],
        },
        {
            id: 35,
            label: "Polyphenol",
            use: "An antioxidant found in plants and vegetables. Reduces inflammation, and lowers the risks of getting heart diseases and diabetes.",
            buttonColor: "#F43545",
            linkTo: [
                0, 1, 5, 8,
            ],
        },
        {
            id: 36,
            label: "Lycopene",
            use: "A red pigment found in fruits and vegetables. Helps reduce the risk of cancer.",
            buttonColor: "#FAD717",
            linkTo: [
                0, 1,
            ],
        },
        {
            id: 37,
            label: "Capsaicin",
            use: "The source of the spicy taste of certain vegetables. Reduces inflammation and has pain relieving properties.",
            buttonColor: "#F786AA",
            linkTo: [
                1, 12,
            ],
        },
        {
            id: 38,
            label: "Chlorophyll",
            use: "A green pigment found in vegetables. Contains lots of B-Vitamins and other nutrients.",
            buttonColor: "#FAD717",
            linkTo: [
                1, 3, 8,
            ],
        },
        {
            id: 39,
            label: "Omega-3",
            use: "Healthy, essential fats that your body needs for heart and brain health.",
            buttonColor: "#F43545",
            linkTo: [
                3, 5, 6, 10, 11,
            ],
        },
        {
            id: 40,
            label: "Omega-6",
            use: "Healthy, essential fats that your body needs for heart health.",
            buttonColor: "#F43545",
            linkTo: [
                7, 8, 10,
            ],
        },
    ],
};
