/**
 * ChildScan Component
 *
 * Enables barcode scanning in Child Mode using the device camera.
 * Fetches product data via `productApi.getProduct` and navigates to `CHILD_FOODITEM` with the result.
 *
 * Key Features:
 * - Requests camera permission on mount
 * - Uses `expo-camera` to scan barcodes
 * - Displays loading indicator while fetching product data
 * - Navigates to food detail screen with scanned item
 *
 * Generated by Copilot AI
 */

import React, { useState, useEffect, useCallback, useRef } from "react";
import { View, StyleSheet,  ActivityIndicator, Text, Button } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useIsFocused, useFocusEffect } from "@react-navigation/native";

import colors from "../../config/colors";
import routes from "../../navigation/routes";
import productApi from "../../api/products";

function ChildScan({ navigation }) {
  const [permission, requestPermission] = useCameraPermissions();
  const [loading, setLoading] = useState(false);
  const isFocused = useIsFocused();
  const scanLock = useRef(false);

  {/* un-comment below block to simulate barcode scan on android studio */}
  // const MOCK_BARCODE = "8711299100174"; // replace this to test different food products
  // const mockScan = () => {
  //   barcodeScanned({ data: MOCK_BARCODE });
  // };

  const barcodeScanned = async ({ data }) => {
    if (scanLock.current) return; // block repeat scans
    
    scanLock.current = true;
    setLoading(true);
    
    try {
      const response = await productApi.getProduct(data);
    
      if (!response || !response.data) {
        console.log("Invalid/empty API response:", response);
        throw new Error("Invalid/empty API response");
      }

      navigation.navigate(routes.CHILD_FOODITEM, response.data);
    } catch (error) {
      console.log("Scan error:", error);
      setHasScanned(false); // allow rescan 
    } finally {
      setLoading(false);
    }
  };

  useFocusEffect(
    useCallback(() => {
      scanLock.current = false;
      setLoading(false);
    }, [])
  );

  useEffect(() => {
    if (!permission?.granted) {
      requestPermission();
    }
  }, [permission]);

  if (!permission) return <View />;
  if (!permission.granted) 
    return (
      <View style={styles.permissionContainer}>
        <Text>No access to camera</Text>
      </View>
    );

  return (
    <View style={styles.container}>

    {/* un-comment below block to simulate barcode scan on android studio */}
      {/* <View style={styles.mockButton}>
        <Button
          title="Mock Scan (Emulator)"
          onPress={mockScan}
          disabled={loading}
          color={colors.primary}
        />
      </View> */}

      {isFocused && !loading && (
        <CameraView
          style={StyleSheet.absoluteFill}
          facing="back"
          onBarcodeScanned={barcodeScanned}          
          zoom={0.1} // prevents 0.5 zoom camera effect
        />
      )}

      {!loading && (
        <View style={styles.overlay}>
          <View style={styles.barcodeBorder} />
        </View>
      )}

      {loading && (
        <View style={styles.loadingOverlay}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.loadingText}>Analyzing product...</Text>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "black",
  },
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  barcodeBorder: {
    borderWidth: 4,
    width: "75%",
    height: "30%",
    borderColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.light,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "black",
    marginTop: 15,
    fontSize: 16,
  },
  // un-comment below style block to simulate android barcode scan
  // mockButton: {
  //   position: "absolute",
  //   bottom: 40,
  //   alignSelf: "center",
  //   backgroundColor: "white",
  //   padding: 6,
  //   borderRadius: 8,
  //   zIndex: 9999,
  //   elevation: 10,
  // },
});

export default ChildScan;
