/**
 * ChildFoodAbout Component
 *
 * Provides detailed information about a scanned food item in Child Mode.
 * Displays ingredients, additives, allergy warnings, and health condition tips based on the product data.
 *
 * Key Features:
 * - Checks for allergens and dietary conditions using `checkAllergens` and `checkConditions` utilities
 * - Displays food image, ingredients, and additives if available
 * - Highlights allergy risks and health tips with styled alerts
 * - Includes a back button to return to `CHILD_FOODITEM`
 *
 * Generated by Copilot AI
 */

import React, { useEffect, useState } from "react";
import { StyleSheet, View, Image, ScrollView } from "react-native";

import Screen from "../../components/Screen";
import AppText from "../../components/AppText";
import colors from "../../config/colors";
import ChildBackButton from "../../components/ChildBackButton";
// import routes from "../../navigation/routes";

function ChildFoodAbout({ navigation, route }) {

  const { food, allergyConflicts, conditionConflicts, dietConflicts } = route.params;
  const productName =
    food?.product?.product_name ||
    food?.product?.product_name_en ||
    "Unknown Food";

  const image = food?.product?.image_small_url || null;
  const traces = food?.product?.traces_tags || [];
  const additives = food?.product?.additives || null;

//displayes image of food item if available
  return (
    <ScrollView>
      <Screen style={styles.screen}>
        <View style = {styles.container}>
          <View style={styles.backButton}>
            <ChildBackButton
                title="<<   GO BACK"
                onPress={() => navigation.goBack()} // adding goBack() makes screen slide from left to right
            />
          </View>

          <AppText style = {styles.title}>Food Details</AppText> 

          {image && (
            <Image
              source={{ uri: image }}
              style={styles.image}
            />
          )}

          <AppText style={styles.subTitle}>What's in {productName}?</AppText>

          {/* allergy */}
          {allergyConflicts?.length > 0 && (
            <View style={styles.warningBox}>
              <AppText style={styles.warningHeader}>
                These could trigger your allergies:
              </AppText>

              {allergyConflicts?.map((item, i) => (
                <AppText key={i} style={styles.bullet}>
                  • {item}
                </AppText>
              ))}
            </View>
          )}

          {/* condition */}
          {conditionConflicts?.length > 0 && (
            <View style={styles.warningBox}>
              <AppText style={styles.warningHeader}>
                These could worsen your health conditions:
              </AppText>

              {conditionConflicts?.map((item, i) => (
                <AppText key={i} style={styles.bullet}>
                  • {item}
                </AppText>
              ))}
            </View>
          )}

          {/* diet */}
          {dietConflicts?.length > 0 && (
            <View style={styles.warningBox}>
              <AppText style={styles.warningHeader}>
                These may not follow your diet:
              </AppText>

              {dietConflicts?.map((item, i) => (
                <AppText key={i} style={styles.bullet}>
                  • {item}
                </AppText>
              ))}
            </View>
          )}

          <View style={styles.sectionBox}>
            {/* additives */}
            <AppText style={styles.sectionTitle}>Additives:</AppText>
            {additives ? (
              <AppText style={styles.sectionText}>{additives}</AppText>
            ) : (
              <AppText style={styles.sectionText}>
                Adam could not find additives for this item.
              </AppText>
            )}

            {/* traces */}
            {/* formats each trace found to remove everything before the colon (if there is one)
                and add a comma and a space after each item if there are multiple
            */}
            <AppText style={styles.sectionTitle}>Possible Traces:</AppText>
            {traces.length > 0 ? (
              <AppText style={styles.sectionText}>
                  {traces
                    .map(t => {
                      const clean = t.includes(":") ? t.split(":")[1] : t;
                      return clean.replace("-", " ");
                    })
                    .join(", ")}
              </AppText>
              ) : (
              <AppText style={styles.sectionText}>
                Adam could not find traces for this item.
              </AppText>
            )}
          </View>

          {/* <AppText style = {styles.title}>Food Details</AppText> 
          <AppText style = {styles.title}>Item Name: </AppText> 
          <AppText style = {styles.text}>{food.product.product_name}</AppText> 

          <AppText style = {styles.title}>What's in {food.product.product_name}? </AppText> 
          {ingredients ? <AppText style = {styles.text}>{food.product.ingredients_text}</AppText> :<AppText style = {styles.text}>Adam does not have the list of ingredients for this item.</AppText>}

          <AppText style = {styles.title}>Additives: </AppText> 
          {additives ? <AppText style = {styles.text}>{food.product.additives}. </AppText> :<AppText style = {styles.text}>Adam does not have the list of additives for this item.</AppText>} */}
        </View>
      </Screen>
    </ScrollView>
  );
}

//how every part looks on the screen
const styles = StyleSheet.create({
  screen: {
    backgroundColor: colors.light,
  },
  container: {
    alignItems: 'center',
    // justifyContent: 'center',
    padding: 20,
    paddingBottom: 90,
  },
  backButton: {
    marginBottom: 30,
  },
  image: {
    height: 250,
    width: 250,
    borderColor: colors.secondary,
    borderRadius: 25,
    borderWidth: 8,
    marginBottom: 20,
  },
  title: {
    // paddingTop: 5,
    fontSize: 50,
    fontWeight: "bold",
    color: colors.secondary,
    marginBottom: 15,
    textAlign: "center",
    // alignSelf: 'center',
    // paddingBottom: 10,
    // textDecorationLine: 'underline'
  },
  subTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: colors.eltrdarkblue,
    marginBottom: 10,
    textAlign: "center",
  },
  warningBox: {
    backgroundColor: "#ffeaea",
    padding: 14,
    marginTop: 20,
    borderWidth: 5,
    borderColor: colors.eltrred,
    borderRadius: 15,
    width: "90%",
    alignItems: "center",
  },
  warningHeader: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.danger,
    alignSelf: "flex-start",
    marginBottom: 4,
  },
  text: {
    fontSize: 20,
    textAlign: "center",
    marginBottom: 10,
  },
  bullet: {
    fontSize: 20,
    alignSelf: "flex-start",
    marginLeft: 20,
    marginBottom: 4,
  },

  sectionBox: {
    backgroundColor: "#f2faff",
    padding: 14,
    marginTop: 20,
    borderWidth: 5,
    borderColor: colors.secondary,
    borderRadius: 15,
    width: "90%",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 25,
    fontWeight: "bold",
    color: colors.secondary,
    marginBottom: 4,
  },
  sectionText: {
    fontSize: 20,
    textAlign: "center",
    marginBottom: 10,
  },
});
export default ChildFoodAbout;
