/**
 * ChildFoodAbout Component
 *
 * Provides detailed information about a scanned food item in Child Mode.
 * Displays ingredients, additives, allergy warnings, and health condition tips based on the product data.
 *
 * Key Features:
 * - Checks for allergens and dietary conditions using `checkAllergens` and `checkConditions` utilities
 * - Displays food image, ingredients, and additives if available
 * - Highlights allergy risks and health tips with styled alerts
 * - Includes a back button to return to `CHILD_FOODITEM`
 *
 * Generated by Copilot AI
 */

import React, { useEffect, useState } from "react";
import { StyleSheet, View, Image, ScrollView } from "react-native";

import Screen from "../../components/Screen";
import AppText from "../../components/AppText";
import colors from "../../config/colors";
import ChildButtonFood from "../../components/ChildButtonFood";
import routes from "../../navigation/routes";
import check from "../../utility/check";

//checkAllergies/Conditions compare food ingredients allergies & conditions respectively 

function ChildFoodAbout({ navigation, route }) {
  const [allergic, setAllergic] = useState(null);
  const [condition, setCondition] = useState(null);
  const food = route.params;
  const ingredients = food.product.ingredients_text;
  const additives = food.product.additives;
  let image = false;
  let traces = false;

  if (food.status) {
    image = food.product.image_small_url;
    traces = food.product.traces;

    useEffect(() => {
      checkAllergies();
      checkConditions();
    }, []);
  }
  const checkAllergies = async () => {
    const allergic = await check.checkAllergens(
      food.product.ingredients_text,
      food.product.traces
    );
    setAllergic(allergic);
  };

  const checkConditions = async () => {
    const condition = await check.checkConditions(food.product.nutriments);
    setCondition(condition);
  };

//displayes image of food item if available
  return (
    <ScrollView>
      <Screen style={styles.screen}>
        <View style = {styles.container}>
          {image ? (
              <Image
                source={{ uri: food.product.image_small_url }}
                style={{
                  height: 250,
                  width: 250,
                  borderColor: colors.secondary,
                  borderWidth: 8,
                  marginBottom: 20,
                }}
              />
            ) : null}

          {allergic ? (
                <>
                  <AppText style={styles.allergy}>
                    **Warning! This food contains {allergic} which you are allergic to. 
                  </AppText>
                </>
              ) : null}

          {traces ? <AppText style = {styles.text}> May also contain traces of:{food.product.traces}.</AppText>: null}

          {condition ? (
                <>
                  <AppText style = {styles.tips}>*ADAM'S TIP*</AppText>
                  <AppText style={styles.text}>-{condition}</AppText>
                </>
              ) : null}

          <AppText style = {styles.title1}>Food Details</AppText> 
          <AppText style = {styles.title}>Item Name: </AppText> 
          <AppText style = {styles.text}>{food.product.product_name}</AppText> 

          <AppText style = {styles.title}>What's in {food.product.product_name}? </AppText> 
          {ingredients ? <AppText style = {styles.text}>{food.product.ingredients_text}</AppText> :<AppText style = {styles.text}>Adam does not have the list of ingredients for this item.</AppText>}

          <AppText style = {styles.title}>Additives: </AppText> 
          {additives ? <AppText style = {styles.text}>{food.product.additives}. </AppText> :<AppText style = {styles.text}>Adam does not have the list of additives for this item.</AppText>}

          <ChildButtonFood
            title="<<   GO BACK"
            onPress={() => navigation.navigate(routes.CHILD_FOODITEM)}/>
        </View>
      </Screen>
    </ScrollView>
  );
}
//Above code displayes warning if allergy &/or condition matches ingredients & food info

//how every part looks on the screen
const styles = StyleSheet.create({
  screen: {
    backgroundColor:colors.light,
  },

  container: {
    alignItems: 'center',
    justifyContent: 'center',
},

  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.danger,
  },

  title1: {
    paddingTop: 5,
    fontSize: 32,
    fontWeight: "bold",
    color: colors.secondary,
    alignSelf: 'center',
    paddingBottom: 10,
    textDecorationLine: 'underline'
  },

  text: {
    fontSize: 18,
    paddingBottom: 10
  },

  allergy: {
    backgroundColor:colors.danger,
    fontSize: 22,
    fontWeight: "bold",
    color: colors.white,
    marginBottom:10    
  },
  tips: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.eltrgreen,
    textDecorationLine: 'underline'
  }
});
export default ChildFoodAbout;
