/**
 * ChildHome Component
 *
 * Main landing screen for Child Mode in the ELTR app.
 * Provides access to scanning, games, recipes, and mode switching in a kid-friendly layout.
 *
 * Key Features:
 * - Prevents hardware back button from exiting the app (Android)
 * - Navigation buttons for Scan, Game, Secret Recipes, and Change Mode
 * - Displays themed images and "CHILD MODE" label for visual clarity
 *
 * Generated by Copilot AI
 */

import React, { useEffect } from "react";
import { StyleSheet, View, Image, BackHandler, Dimensions, ScrollView } from "react-native";

import Screen from "../../components/Screen";
import ChildButtonLarge from "../../components/ChildButtonLarge";
import ChildButtonSmall from "../../components/ChildButtonSmall";
import AppText from "../../components/AppText";
import colors from "../../config/colors";
import routes from "../../navigation/routes";

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

function ChildHome({ navigation }) {
  return (
    <Screen backgroundColor={colors.eltrlightblue} style={styles.container}>
        <View style={styles.mainButtons}>
          <View style={styles.buttonContainer}>
            <Image
              source={require("../../assets/child_mode/CM_Scan.jpg")}
              style={styles.scan}
            />
            <ChildButtonLarge
              title="Scan"
              onPress={() => navigation.navigate(routes.CHILD_SCAN)}
            />
          </View>

          <View style={styles.buttonContainer}>
            <Image
              source={require("../../assets/child_mode/CM_Play.jpg")}
              style={styles.play}
            />
            <ChildButtonLarge
              title="Play"
              onPress={() => navigation.navigate("DriveThru")}
            />
          </View>
        </View>

        <View style={styles.otherButtons}>
          <View style={styles.buttonContainer}>
            <Image
              source={require("../../assets/child_mode/CM_Adam.jpg")}
              style={styles.adam}
            />
            <ChildButtonSmall
              title="Change Mode"
              onPress={() => navigation.navigate(routes.CHILD_CHANGE)}
            />
          </View>

          <View style={styles.buttonContainer}>
            <Image
              source={require("../../assets/child_mode/CM_Toddy.jpg")}
              style={styles.toddy}
            />
            <ChildButtonSmall
              title="Secret Recipes"
              onPress={() => navigation.navigate(routes.CHILD_RECIPES)}
            />
          </View>
        </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: colors.eltrlightblue,
  },
  buttonContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  mainButtons: {
    marginTop: 100,
    gap: 140,
    zIndex: 2,
  },
  otherButtons: {
    position: "absolute",
    bottom: 80,
    flexDirection: "row",
    gap: 15,
    zIndex: 2,
  },
  kidrainbow: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: -50,
    paddingTop: 0,
    top: 60,
    width: 350,
    height: 220,
    shadowColor: colors.white,
    shadowOpacity: 0.5,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 4,
  },
  scan: {
    position: "absolute",
    top: -115,
    width: 180,
    height: 160,
    resizeMode: "contain",
    zIndex: 0,
  },
  play: {
    position: "absolute",
    top: -148,
    width: 260,
    height: 180,
    resizeMode: "contain",
    zIndex: 0,
  },
  adam: {
    position: "absolute",
    top: -90,
    width: 110,
    height: 110,
    resizeMode: "contain",
    zIndex: 0,
  },
  toddy: {
    position: "absolute",
    top: -80,
    width: 100,
    height: 100,
    resizeMode: "contain",
    zIndex: 0,
  },
});

export default ChildHome;
