/**
 * DriveThru Component
 *
 * Interactive game screen where children choose a character, a mode of transport, and a restaurant destination.
 * Once all selections are made, navigates to `DriveThruDecision` with the chosen options.
 *
 * Key Features:
 * - Step-by-step selection flow: character → transport → restaurant
 * - Uses `FlatList` for horizontal scrolling of choices
 * - Displays selected character and transport visually
 * - Automatically navigates when restaurant is selected
 *
 * Generated by Copilot AI
 */

import React, { Component, useRef, useState, useEffect, } from "react";
import UnityView from '@azesmway/react-native-unity';
import { View, StyleSheet, } from "react-native";

const DriveThru = () => {
  return <UnityView style={{flex: 1}} />;
};

const styles = StyleSheet.create({
    screen: {
      flex: 1,
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
});

export default DriveThru;