/**
 * This code defines a basic unit test for the `App` class using JUnit in a Java project initialized by Gradle.
 * 
 * The test method `testAppHasAGreeting` checks that the `getGreeting()` method of the `App` class returns a non-null value.
 * This ensures that the application provides a greeting message, serving as a simple verification of core functionality.
 * 
 * Generated by CoPilot AI
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ELTRFront;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
