/**
 * This code creates a React context to manage authentication state across the application.
 * 
 * AuthContext allows components to access and update user-related data such as login status and profile information without prop drilling.
 * It is typically used with a context provider to share state globally throughout the app's component tree.
 * 
 * Generated by CoPilot AI
 */

import React from "react";

const AuthContext = React.createContext();

export default AuthContext;
