/**
 * This code provides utility functions for storing and retrieving data using React Native's AsyncStorage.
 * 
 * The `store` function saves a value under a specified key after converting it to a JSON string.
 * The `get` function retrieves the value for a given key, parses it from JSON, and returns an empty array if no data is found.
 * These methods are used throughout the app to persist user-specific data such as allergies and conditions.
 * 
 * Generated by CoPilot AI
 */

import AsyncStorage from "@react-native-async-storage/async-storage";

const store = async (key, value) => {
  try {
    await AsyncStorage.setItem(key, JSON.stringify(value));
  } catch (error) {
    console.log(error);
  }
};

const get = async (key) => {
  try {
    const value = await AsyncStorage.getItem(key);
    if (value) {
      return JSON.parse(value);
    } else {
      return [];
    }
  } catch (error) {
    console.log(error);
  }
};

export default {
  store,
  get,
};
