/**
 * Displays information about the "Eat Like The Rainbow™" initiative, Chef Cathy Zeis, and a curated library of health-related resources.
 *
 * Content is organized into scrollable sections with headings, descriptive text, and external links. 
 * Includes images and styled text for clarity and engagement.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { useEvent } from 'expo';
import { StyleSheet, ScrollView, Text, Image, Linking, View, Alert, Button, Pressable } from "react-native";
// import { Pressable } from "react-native-gesture-handler";
import { VideoView, useVideoPlayer } from "expo-video";

import AppText from "../components/AppText";
import Screen from "../components/Screen";
import colors from "../config/colors";

function AboutScreen(props) {
  
  const player = useVideoPlayer(
    require("../assets/videos/introHuman.mp4"),
    (player) => {
      player.loop = true;
      player.pause();
      // player.play();
    }
  );

  const { isPlaying } = useEvent(player, 'playingChange', { isPlaying: player.playing });

  return (
    <Screen style={styles.container}>
      <ScrollView>
        <Image
          style={styles.rainbowPic}
          source={require("../assets/eltrRainbow_new.png")}
        />

        {/* SOCIAL MEDIA ICONS SECTION */}
        <View style={styles.socialContainer}>

          {/* Instagram combined */}
          <Pressable
            onPress={() =>
              Alert.alert(
                "Open Instagram",
                "Which page do you want to visit?",
                [
                  {
                    text: "Eat Like The Rainbow",
                    onPress: () =>
                      Linking.openURL("https://www.instagram.com/eat.liketherainbow/"),
                  },
                  {
                    text: "Chef Cathy Zeis",
                    onPress: () =>
                      Linking.openURL("https://www.instagram.com/chefcathyzeis/"),
                  },
                  { text: "Cancel", style: "cancel" },
                ]
              )
            }
          >
            <Image source={require("../assets/instagram.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://www.facebook.com/cathy.zeisallnaturalchef")}>
            <Image source={require("../assets/facebook.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://x.com/ChefZeis49662")}>
            <Image source={require("../assets/twitter.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://www.youtube.com/@CathyZeis")}>
            <Image source={require("../assets/youtube.png")} style={styles.socialIcon} />
          </Pressable>

        </View>

       <View style={styles.socialContainer}>
          <Pressable onPress={() => Linking.openURL("https://www.tiktok.com/@chef.cathy.zeis?is_from_webapp=1&sender_device=pc")}>
            <Image source={require("../assets/tiktok.png")} style={styles.socialIcon} />
          </Pressable>
          
          <Pressable onPress={() => Linking.openURL("https://www.lemon8-app.com/@chef.cathy.zeis")}>
            <Image source={require("../assets/lemon8.png")} style={styles.socialIcon} />
          </Pressable>
          
          <Pressable onPress={() => Linking.openURL("https://truthsocial.com/@eatliketherainbow")}>
            <Image source={require("../assets/truthsocial.png")} style={styles.socialIcon} />
          </Pressable>
          
          <Pressable onPress={() => Linking.openURL("https://www.linkedin.com/in/cathy-zeis-292988b/")}>
            <Image source={require("../assets/linkedin.png")} style={styles.socialIcon} />
          </Pressable>
        </View>

        <AppText style={styles.title}>Welcome to the Eat Like The Rainbow™ App!</AppText>
        <AppText style={styles.text}>
          This app was created by people who care about food and your health! Godsource Foods™,
          foods created by God, are preventative medicine. Our app will enable you to
          confidently maneuver the marketing traps of the grocery store and empower you to shop with food
          wisdom and healthy, minded choices that will keep you and your family from falling
          prey to the fake food that occupies our grocery shelves.
          {"\n\n"}
          Learn more about what's in the food you're purchasing by using the barcode scanner,
          read facts about the ingredients in your food on the Home page,
          try out some Chef Cathy Zeis recommended recipes on the Recipes page,
          and get help planning your grocery store trip on the Budget page.
          You can even transform the app into a simple and fun educational experience for your child by
          switching to Child Mode. Check out our FAQ page
          for more information about how to use the app.
          {"\n\n"}
          You can read more information about the Eat Like The Rainbow™ program and Chef Cathy Zeis below. 
          You can can also visit our social media accounts linked above for direct access to Chef Cathy Zeis' platforms! 
        </AppText>

        <AppText style={styles.title}>What is "Eat Like The Rainbow™?"</AppText>
        <VideoView
          style={styles.video}
          player={player}
        />
        <AppText style={styles.text}>
          <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org')}>
          Eat Like The Rainbow™</Text> is a naturally done non-profit, catering to the
          youngest palates. Kindergarten through 4th grade are pivotal years in
          developing major lifestyle characteristics that will guide our future
          leaders into childhood and beyond. From religious beliefs, to sleeping
          patterns, to manners, following rules, and yes, even what to eat. The
          youngest among us just might be our greatest learners!
        </AppText>

        <AppText style={styles.title}>Meet Chef Cathy Zeis</AppText>
        <Image
          style={styles.cathyPic1}
          source={require("../assets/cathyHeadshotNew.png")}
        />
        <AppText style={styles.text}>
          This is God's talent, not mine! He puts it in my head and I throw it in a pan. 
          I have spent most of my life around food. From my first job in a local grocery 
          store in Connecticut at age 16 to creating healthy food plans for those humbled 
          by disease, food is my life! From restaurant owner, to 10 years on television, 
          food editor of a magazine, food photographer, food line creator, columnist, award-winning 
          author and chef, and college lecturer, I've touched just about every area of the food 
          industry. Educating people about how Godsource Foods™, foods 
          that were created by God, work in our bodies is my loaned talent. Helping fight 
          chronic disease and childhood obesity through The Power of Godsource Foods™ is my 
          passion. Creating healthy food plans and educational information is my calling. 
          I am so very blessed to love what I have been called to do! 
          {"\n\n"}
          God created foods on days 3 and 5. He created us on day 6! He had an idea on how 
          to feed us before He created us. As an all-natural chef, I study foods and how they 
          work in our bodies. Foods created for us is preventative medicine. In today's grocery 
          stores, marketing controls the aisles more than health. Because of this, we now have 
          more obesity and chronic disease in the history of our world. This is all due to the 
          processed foods, additives, dyes and sugars that make up our food. This is not acceptable 
          in my food world! I strive each day to educate those looking to encourage their kids 
          and change their own lifestyles in a healthy way by using the very foods available to us each day.
          {"\n\n"}
          Our nonprofit, <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org')}>
          Eat Like The Rainbow™</Text>, is my purpose. Helping change the way we see 
          food and use food to fuel our bodies is a priority. Our next generation of leaders 
          are our best learners! Helping them in a fun, interactive way through our free website 
          and app are rewarding beyond belief. With each bite, each new taste or discovery, our 
          kids need to know just how important they are and how the simple foods created just for 
          them can and will help them flourish.
          {"\n\n"}
          For more information about me and many recipes, 
          visit <Text style={styles.link1} onPress={() => Linking.openURL('https://www.chefcathyzeis.com')}>my website</Text>!
          For more information on certain topics, you can also check out some resources in the library below!
        </AppText>

        <AppText style={styles.title}>Meet the team that brought the app to life!</AppText>
        <Image
          style={styles.eltrTeamPic}
          source={require("../assets/14-eyes.png")}
        />
        <AppText style={styles.text}>
          <Text style={{fontWeight: "bold"}}>From left to right: </Text>Joshua Muñoz, Ethan Holley, Aayushma Bhattarai, Rowen Salazar, Lukas Kallus
        </AppText>

        <AppText style={styles.text}>
          {"\n"}<Text style={{fontWeight: "bold", textDecorationLine: 'underline', fontSize: 17,}}>App Version 1.0 Team</Text>
        </AppText>
        <AppText style={styles.text}>
          <Text style={{fontSize: 17}}>Olivia Jones, Ime Ekpo, Mitchell Heinold, Mason Petersen, Zelvin Sandoval</Text>
        </AppText>


        <AppText style={styles.title}>Library</AppText>

        <Text style={styles.subTitle}>Athletic Lifestyle</Text>
        <View style={styles.linkContainer}>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/exercise/art-20048389')}>
              Exercise: 7 benefits of regular physical activity
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.lancastergeneralhealth.org/health-hub-home/2020/march/what-athletes-should-eat-back-to-the-basic-food-groups')}>
              What Athletes Should Eat: Back to the Basic Food Groups
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.uwhealth.org/news/eating-for-peak-athletic-performance')}>
              Eating for peak athletic performance
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/exercise/art-20045506')}>
              Eating and exercise: 5 tips to maximize your workouts
          </Text>
        </View>

        <Text style={styles.subTitle}>Bedtime</Text>
        <View style={styles.linkContainer}>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://youtu.be/bom6ZrVwGIc?si=08Zoe9HfNkU9grMy')}>
              Why healthy sleep is crucial for academic success
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://health.clevelandclinic.org/sleep-and-health/')}>
              Does a Bad Night's Sleep Affect Your Health?
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.cdc.gov/physical-activity-education/staying-healthy/sleep.html?CDC_AAref_Val=https://www.cdc.gov/healthyschools/sleep.htm')}>
              Sleep and Health
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.sleepfoundation.org/nutrition/food-and-drink-promote-good-nights-sleep')}>
              The Best Foods To Help You Sleep
          </Text>
        </View>

        <Text style={styles.subTitle}>Food and Mental Health</Text>
        <View style={styles.linkContainer}>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://youtu.be/CSHO9VdVRfg?si=JfJw7A8twroVtlGw')}>
            Food and mood
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.webmd.com/diet/foods-high-in-polyphenols#1')}>
            Healthy Foods High in Polyphenols
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://pmc.ncbi.nlm.nih.gov/articles/PMC6836211/')}>
            Cognitive Function and Consumption of Fruit and Vegetable Polyphenols in a Young Population: Is There a Relationship?
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://cbn.com/news/us/surprising-link-between-these-foods-and-depression-anxiety-and-other-mental-health-issues')}>
            The Surprising Link Between These Foods and Depression, Anxiety and Other Mental Health Issues 
          </Text>
        </View>

        <Text style={styles.subTitle}>Grocery Stores</Text>
        <View style={styles.linkContainer}>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.webmd.com/food-recipes/default.htm')}>
            10 Tips for Healthy Grocery Shopping
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://medlineplus.gov/ency/article/001973.htm')}>
            Cow's milk and children
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.nytimes.com/2020/09/08/dining/grocery-shopping-coronavirus.html')}>
            7 Ways the Pandemic Has Changed How We Shop for Food
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.forbes.com/sites/capitalone/2018/08/20/is-fast-food-really-cheaper-than-healthy-eating/?sh=75263bb5410a')}>
            Is Fast Food Really Cheaper Than Healthy Eating?
          </Text>
        </View>

        <Text style={styles.subTitle}>Preservatives</Text>
        <View style={styles.linkContainer}>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.webmd.com/diet/food-additives-special-report/video/cm/what-food-additives')}>
            What are Food Additives? 
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.britannica.com/topic/preservative')}>
            Preservative: Food Processing
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.loseit.com/articles/the-best-processed-foods-for-weight-loss-according-to-registered-dietitians/')}>
            Harmful Effects of Preservatives in Foods
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://healthfully.com/what-are-the-dangers-of-preservatives-3201078.html')}>
            What Are the Dangers of Preservatives? 
          </Text>
        </View>

        <Text style={styles.subTitle}>Rainbow Foods</Text>
        <View style={styles.linkContainer}>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://youtu.be/onyR8Rnzgrs?si=pcvdKQw5seQVh2q2')}>
            Follow the rainbow to healthy eating 
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.health.harvard.edu/blog/phytonutrients-paint-your-plate-with-the-colors-of-the-rainbow-2019042516501')}>
            Phytonutrients: Paint your plate with the colors of the rainbow 
          </Text>
          <Text style={styles.link2} 
            onPress={() => Linking.openURL('https://www.healthline.com/nutrition/eat-the-rainbow')}>
            Eating the Rainbow — Is It Useful and Should You Try It?
          </Text>
        </View>

        <Image
          style={styles.cathyPic2}
          source={require("../assets/cathyHeadshot.png")}
        />
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: colors.light,
  },
  rainbowPic: {
    alignSelf: "center",
    width: 230,
    height: 230,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.white,
    marginTop: 10,
    marginBottom: 10,
  },
  video: {
    width: "50%",
    height: 300, // fixed height avoids flex issues
    backgroundColor: colors.primary,
    alignSelf: "center",
    borderRadius: 10,
    borderWidth: 5,
    borderColor: colors.primary,
    marginBottom: 10,
  },
  title: {
    color: colors.primary,
    fontSize: 35,
    marginBottom: 5,
    marginTop: 25,
    textAlign: "center",
  },
  text: {
    textAlign: "center",
    fontSize: 20,
  },
  link1: {
    fontSize: 20,
    color: colors.eltrdarkblue,
    fontWeight: "bold",
    textDecorationLine: "underline",
    marginVertical: 5,
    textAlign: "center",
  },
  subTitle: {
    // color: colors.primary,
    fontSize: 22,
    marginTop: 10,
    marginBottom: 5,
    textAlign: "center",
  },
  linkContainer: {
    alignItems: "center",
    marginBottom: 15,
  },
  link2: {
    fontSize: 16,
    color: colors.eltrdarkblue,
    fontWeight: "bold",
    textDecorationLine: "underline",
    marginVertical: 5,
    textAlign: "center",
  },
  cathyPic1: {
    alignSelf: "center",
    width: 200,
    height: 240,
    marginTop: 5,
    marginBottom: 10,
    borderRadius: 7,
    borderWidth: 4,
  },
  eltrTeamPic: {
    alignSelf: "center",
    width: 250,
    height: 170,
    marginTop: 5,
    marginBottom: 10,
    borderRadius: 7,
    borderWidth: 4,
  },
  cathyPic2: {
    alignSelf: "center",
    width: 320,
    height: 210,
    marginBottom: 5,
  },

  socialContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 5,
    // iOS Shadow properties
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
  },
  socialIcon: {
    width: 45,
    height: 45,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.eltrdarkblue,
    marginHorizontal: 10,
    // Android Elevation property
    elevation: 3,
  },
});

export default AboutScreen;