/**
 * Displays information about the "Eat Like The Rainbow™" initiative, Chef Cathy Zeis, and a curated library of health-related resources.
 *
 * Content is organized into scrollable sections with headings, descriptive text, and external links. 
 * Includes images and styled text for clarity and engagement.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { StyleSheet, ScrollView, Text, Image, Linking, View, Alert } from "react-native";
import { Pressable } from "react-native-gesture-handler";
import { block } from "react-native-reanimated";

import AppText from "../components/AppText";
import Screen from "../components/Screen";
import colors from "../config/colors";

//what information is being displayed

function AboutScreen(props) {
  return (
    <Screen style={styles.container}>
      <ScrollView>
        <Image
          style={styles.pic}
          source={require("../assets/eltrRainbow.png")}
        />

{/* SOCIAL MEDIA ICONS SECTION */}
        <View style={styles.socialContainer}>

          {/* Instagram combined */}
          <Pressable
            onPress={() =>
              Alert.alert(
                "Open Instagram",
                "Which page do you want to visit?",
                [
                  {
                    text: "Eat Like The Rainbow",
                    onPress: () =>
                      Linking.openURL("https://www.instagram.com/eat.liketherainbow/"),
                  },
                  {
                    text: "Chef Cathy Zeis",
                    onPress: () =>
                      Linking.openURL("https://www.instagram.com/chefcathyzeis/"),
                  },
                  { text: "Cancel", style: "cancel" },
                ]
              )
            }
          >
            <Image source={require("../assets/instagram.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://www.facebook.com/cathy.zeisallnaturalchef")}>
            <Image source={require("../assets/facebook.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://x.com/ChefZeis49662")}>
            <Image source={require("../assets/twitter.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://www.youtube.com/@CathyZeis")}>
            <Image source={require("../assets/youtube.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://www.tiktok.com/@chef.cathy.zeis?is_from_webapp=1&sender_device=pc")}>
            <Image source={require("../assets/tiktok.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://www.lemon8-app.com/@chef.cathy.zeis")}>
            <Image source={require("../assets/lemon8.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://truthsocial.com/@eatliketherainbow")}>
            <Image source={require("../assets/truthsocial.png")} style={styles.socialIcon} />
          </Pressable>

          <Pressable onPress={() => Linking.openURL("https://www.linkedin.com/in/cathy-zeis-292988b/")}>
            <Image source={require("../assets/linkedin.png")} style={styles.socialIcon} />
          </Pressable>

        </View>
        
        <AppText style={styles.title}>What is "Eat Like The Rainbow™?"</AppText>
        <AppText style={styles.text}>
          <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org')}>Eat Like The Rainbow™</Text> is a naturally done non-profit, catering to the
          youngest palates. Kindergarten through 4th grade are pivotal years in
          developing major lifestyle characteristics that will guide our future
          leaders into childhood and beyond. From religious beliefs, to sleeping
          patterns, to manners, following rules, and yes, even what to eat. The
          youngest among us just might be our greatest learners!
        </AppText>

        <AppText style={styles.title}>Meet Chef Cathy Zeis</AppText>
        <AppText style={styles.text}>
          I am an all-natural chef who creates healthy food plans for those who
          are humbled by disease. I also passionately create healthy cuisine for
          those who crave a healthier lifestyle. Based on the foods that were
          created for us to feed our bodies from the very beginning, is the base
          for all my plans. Whether you are fighting a disease like cancer,
          heart disease, IBS, or obesity, this is where you want to be! If you
          love and crave all natural, Godsource Foods™ as I do to maintain a
          healthy lifestyle, then this is your place! It’s the combinations of
          the foods that fuel our bodies. Foods can kill, but it can also heal!
          I love educating people on how the simplest ingredients can power our
          bodies. After all, our bodies are the most amazing machines ever
          created! I’ll teach you how to fuel it…naturally! For more information about me
          and many recipes, visit my <Text style={styles.link1} onPress={() => Linking.openURL('https://www.chefcathyzeis.com')}>website</Text>!
          For more information on certain topics, you can also check out some resources in the library below!
        </AppText>

        <AppText style={styles.title}>Library</AppText>

        <Text style={styles.header1}>Athletic Lifestyle</Text>
        <Text style={styles.text1}>
          <Text>{'\u2022'}<Text style={styles.link1} onPress={() => Linking.openURL('https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/exercise/art-20048389')}>Exercise: 7 benefits of regular physical activity</Text>{'\n'}</Text>
          <Text>{'\u2022'}<Text style={styles.link1} onPress={() => Linking.openURL('https://www.lancastergeneralhealth.org/health-hub-home/2020/march/what-athletes-should-eat-back-to-the-basic-food-groups')}>What Athletes Should Eat: Back to the Basic Food Groups</Text>{'\n'}</Text>
          <Text>{'\u2022'}<Text style={styles.link1} onPress={() => Linking.openURL('https://www.uwhealth.org/news/eating-for-peak-athletic-performance')}>Eating for peak athletic performance</Text>{'\n'}</Text>
          <Text>{'\u2022'}<Text style={styles.link1} onPress={() => Linking.openURL('https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/exercise/art-20045506')}>Eating and exercise: 5 tips to maximize your workouts</Text>{'\n'}</Text>
        </Text>

        <Image
          style={styles.pic}
          source={require("../assets/cathyHeadshot.png")}
        />
      </ScrollView>
    </Screen>
  );
}

//how info is being displayed

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: colors.light,
  },
  title: {
    color: colors.primary,
    fontSize: 23,
    marginBottom: 5,
    marginTop: 25,
    textAlign: "center",
  },
  text: {
    textAlign: "center",
    fontSize: 18,
  },
  pic: {
    alignSelf: "center",
    width: 280,
    height: 190,
    marginBottom: 10,
  },
  link1: {
    color: colors.eltrdarkblue,
    fontWeight: "bold",
    textDecorationLine: "underline",
    alignItems: "center",
    justifyContent: "center",
  },

  socialContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
  },
  socialIcon: {
    width: 40,
    height: 40,
    marginHorizontal: 6,
  },
});

export default AboutScreen;