/**
 * Displays a list of account-related navigation options for the authenticated user.
 *
 * Each item includes an icon and title, and navigates to a corresponding screen when tapped.
 * Each menu item navigates to a different screen for managing user-specific data (e.g., conditions, allergies).
 * Uses context to access the current user and provides a logout handler via Firebase.
 * 
 * The logout function calls `Firebase.auth().signOut()` to terminate the session, then clears the user from context.
 * This ensures the app reflects the signed-out state and redirects appropriately.
 * Firebase Authentication manages user sessions securely and supports multiple providers (email/password, Google, etc.).
 * When `signOut()` is called, Firebase invalidates the user's token and disconnects them from protected resources.
 *
 * Generated by Copilot AI
 */

import React, { useContext } from "react";
import { StyleSheet, View, FlatList } from "react-native";

import Screen from "../components/Screen";
import ListItem from "../components/lists/ListItem";
import Icon from "../components/Icon";
import colors from "../config/colors";
import ListItemSeparator from "../components/lists/ListItemSeparator";
import routes from "../navigation/routes";
import AuthContext from "../auth/context";
import Firebase from "../config/firebase";
import { useFocusEffect } from "@react-navigation/native";
import { auth } from "../config/firebase";


const menuItems = [
  {
    title: "My Conditions",
    icon: {
      name: "medical-bag",
      backgroundColor: colors.primary,
    },
    target: "AccountConditions",
  },
  {
    title: "My Allergies",
    icon: {
      name: "food-off",
      backgroundColor: colors.secondary,
    },
    target: "AccountAllergies",
  },
  {
    title: "My Dietary Preferences",
    icon: {
      name: "leaf",
      backgroundColor: colors.eltrgreen,
    },
    target: "AccountDietaryPreferences",
  },
  // new button to route to new screen
  {
    title: "Account Center",
    icon: {
      name: "account-cog", // can use any icon from MaterialCommunityIcons
      backgroundColor: colors.eltrpink,
    },
    target: "EditAccount", // should match screen’s route name
  },
];

function AccountDetails({ navigation }) {
  const authContext = useContext(AuthContext);

  const handleLogOut = () => {
    Firebase.auth()
      .signOut()
      .then(() => {
        // Sign-out successful.
        authContext.setUser(null);
      })
      .catch((error) => {
        console.log(error);
      });
  };
  useFocusEffect(
    React.useCallback(() => {
      const reloadUser = async () => {
        try {
          await auth.currentUser.reload(); // refresh Firebase user
          authContext.setUser(auth.currentUser); // update context
        } catch (err) {
          console.log("USER RELOAD ERROR:", err);
        }
      };

      reloadUser();
    }, [])
  );
  
  return (
    <Screen style={styles.screen}>
      <View style={styles.container}>
        <FlatList
          data={menuItems}
          keyExtractor={(item) => item.title}
          ItemSeparatorComponent={ListItemSeparator}
          renderItem={({ item }) => (
            <ListItem
              title={item.title}
              onPress={() => navigation.navigate(item.target)}
              IconComponent={
                <Icon
                  name={item.icon.name}
                  backgroundColor={item.icon.backgroundColor}
                />
              }
            />
          )}
			    scrollEnabled={false} // needed to prevent list of options from scrolling
        />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  container: {
    marginVertical: 1,
  },
  screen: {
    backgroundColor: colors.light,
		paddingTop: 8,
  },
});

export default AccountDetails;
