/**
 * Displays editable account settings and provides a modal for confirming account deletion.
 *
 * Users can update their name, email, or password by navigating to corresponding screens.
 * A "Delete Account" option triggers a confirmation modal to prevent accidental deletion.
 * The actual deletion logic should be implemented in the handleDeleteConfirm function.
 *
 * Uses Firebase Authentication context to display current user data and manage session state.
 * The modal overlay ensures user focus and clearly communicates the irreversible nature of deletion.
 *
 * Generated by Copilot AI
 */


import React, { useContext, useState, useEffect } from "react";
import { useFocusEffect } from "@react-navigation/native";
import { StyleSheet, View, FlatList, Modal, Text, TouchableOpacity, ActivityIndicator, Alert, Switch} from "react-native";
import Screen from "../components/Screen";
import ListItem from "../components/lists/ListItem";
import colors from "../config/colors";
import ListItemSeparator from "../components/lists/ListItemSeparator";
import AuthContext from "../auth/context";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { db } from "../config/firebase";
import {deleteUser, onAuthStateChanged } from "firebase/auth";
import { deleteDoc, doc, getDoc } from "firebase/firestore"
import { auth } from "../config/firebase";
import { clearAllOptionCaches } from "../utility/fetchOptions";
import { useBiometrics } from "../hooks/useBiometric";
import AppText from "../components/AppText";


function EditAccount({ navigation }) {
  const authContext = useContext(AuthContext);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [displayName, setDisplayName] = useState("");

  //biometric hook
  const {
    isAvailable,
    isEnabled,
    biometricType,
    isChecking,
    enableBiometric,
    disableBiometric,
    authenticate,
  } = useBiometrics();

  // Load name from Firestore every time screen opens
  useFocusEffect(
    React.useCallback(() => {
      const loadName = async () => {
        const uid = auth.currentUser?.uid;
        if (!uid) return;

        const userDoc = await getDoc(doc(db, "users", uid));
        if (userDoc.exists()) {
          const data = userDoc.data();
          setDisplayName(data.name || "Not set");

          if (authContext?.setUser) {
            authContext.setUser((prev) => ({
              ...prev,
              displayName: data.name,
            }));
          }
        }
      };

      loadName();
    }, [])
  );

  const menuItems = [
    {
      title: "Name",
      description: displayName,
      target: "EditAccountName",
    },
    {
      title: "Email",
      description: auth.currentUser?.email,
      target: "EditAccountEmail",
    },
    {
      title: "Change Password",
      target: "EditAccountPassword",
    },
  ];

  const { setUser } = useContext(AuthContext);
  
  const handleBiometricToggle = async (value) => {
    if (value) {
      const success = await authenticate();

      if (success) {
        await enableBiometric();
        Alert.alert("Biometric login is now enabled")
      } else {
        Alert.alert("Authentication failed, check your device biometric settings");
      }
    } else {
      Alert.alert(
        "Disable biometric login?",
        [
          { text: "Cancel", style: "cancel" },
          { text: "Disable", style: "destructive", 
            onPress: async() => {
              await disableBiometric();
            },
          },
        ]
      );
    }
  };

  // DELETE ACCOUNT
  const handleDeleteConfirm = async () => {
    try {
      setShowDeleteModal(false); 
      
      const currentUser = auth.currentUser;
      if (!currentUser) return;
      
      const uid = currentUser.uid;

      deleteDoc(doc(db, "users", uid));
      deleteUser(currentUser);
      await clearAllOptionCaches();   
      setUser(null);
      console.log("Account deleted and cache cleared");
    } catch (error) {
      console.error("Error deleting account:", error);

      if (error.code === "auth/requires-recent-login") {
        alert("Please re-login and try deleting your account again.");
      }
    }
  };

  return (
    <Screen style={styles.screen}>
      <FlatList
        data={menuItems}
        keyExtractor={(item) => item.title}
        ItemSeparatorComponent={ListItemSeparator}
        renderItem={({ item }) => (
          <ListItem
            title={item.title}
            subTitle={item.description}
            titleStyle={{ paddingLeft: 0 }}
            onPress={() => navigation.navigate(item.target)}
            IconComponent={null}
            renderRightIcon={() => (
              <MaterialCommunityIcons
                name="chevron-right"
                size={28}
                color={colors.medium}
              />
            )}
          />
        )}
        scrollEnabled={false}
      />

      <View style={styles.securitySection}>
        <AppText style={styles.sectionTitle}>Security</AppText>

        {isChecking ? (
          <View style={styles.biometricContainer}>
            <ActivityIndicator size="small" color={colors.primary} />
            <AppText style={styles.checkingText}>
              Checking biometric availability...
            </AppText>
          </View>
        ) : !isAvailable ? (
          <View style={styles.unavailableContainer}>
            <AppText style={styles.unavailableText}>
              No biometric authentication detected on this device.
            </AppText>
            <AppText style={styles.unavailableSubtext}>
              Make sure you have enrolled biometric authentication in
              your device settings.
            </AppText>
          </View>
        ) : (
          <View style={styles.biometricContainer}>
            <View style={styles.biometricTextContainer}>
              <AppText style={styles.biometricLabel}>
                Use {biometricType} to sign in
              </AppText>
            </View>
            <Switch
              value={isEnabled}
              onValueChange={handleBiometricToggle}
              trackColor={{ false: colors.medium, true: colors.eltrgreen }}
              thumbColor={isEnabled ? colors.white : colors.light}
              ios_backgroundColor={colors.medium}
            />
          </View>
        )}
      </View>

      <View style={styles.container}>
        <ListItem
          title="Delete Account"
          onPress={() => setShowDeleteModal(true)}
          IconComponent={null}
          showChevron={false}
          titleStyle={{ color: colors.danger, fontWeight: "bold", paddingLeft: 0 }}
        />
      </View>

      <Modal visible={showDeleteModal} transparent animationType="fade">
        <View style={styles.modalOverlay}>
          <View style={styles.modalContainer}>
            <Text style={styles.modalTitle}>Confirm Delete</Text>
            <Text style={styles.modalMessage}>
              Are you sure you want to delete your account? This action cannot be undone.
            </Text>
            <View style={styles.modalButtons}>
              <TouchableOpacity
                style={[styles.modalButton, styles.cancelButton]}
                onPress={() => setShowDeleteModal(false)}
              >
                <Text style={styles.cancelText}>Cancel</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.modalButton, styles.confirmButton]}
                onPress={handleDeleteConfirm}
              >
                <Text style={styles.confirmText}>Delete</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </Screen>
  );
}

const styles = StyleSheet.create({
  screen: {
    backgroundColor: colors.light,
    paddingTop: 70,
  },
  container: {
    marginBottom: 250,
  },
  securitySection: {
    marginTop: 7,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
    color: colors.dark,
  },
  
  // Biometric Container Styles
  biometricContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    backgroundColor: colors.white,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  biometricTextContainer: {
    flex: 1,
    marginRight: 12,
  },
  biometricLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.dark,
    marginBottom: 4,
  },
  biometricDescription: {
    fontSize: 13,
    color: colors.medium,
  },
  checkingText: {
    marginLeft: 12,
    color: colors.medium,
    fontSize: 14,
  },
  
  // Unavailable State Styles
  unavailableContainer: {
    padding: 16,
    backgroundColor: colors.light,
    borderRadius: 12,
  },
  unavailableText: {
    fontSize: 14,
    color: colors.medium,
    marginBottom: 8,
  },
  unavailableSubtext: {
    fontSize: 12,
    color: colors.medium,
    fontStyle: "italic",
  },

  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContainer: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.dark,
    marginBottom: 10,
  },
  modalMessage: {
    fontSize: 16,
    color: colors.medium,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "center",
  },
  modalButton: {
    marginLeft: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  cancelButton: {
    backgroundColor: colors.light,
  },
  confirmButton: {
    backgroundColor: colors.danger,
  },
  cancelText: {
    color: colors.dark,
    fontSize: 19,
  },
  confirmText: {
    color: colors.white,
    fontWeight: "bold",
    fontSize: 19,
  },
});

export default EditAccount;
