/**
 * Displays editable account settings and provides a modal for confirming account deletion.
 *
 * Users can update their name, email, or password by navigating to corresponding screens.
 * A "Delete Account" option triggers a confirmation modal to prevent accidental deletion.
 * The actual deletion logic should be implemented in the handleDeleteConfirm function.
 *
 * Uses Firebase Authentication context to display current user data and manage session state.
 * The modal overlay ensures user focus and clearly communicates the irreversible nature of deletion.
 *
 * Generated by Copilot AI
 */


import React, { useContext, useState, useEffect } from "react";
import { useFocusEffect } from "@react-navigation/native";
import { StyleSheet, View, FlatList, Modal, Text, TouchableOpacity } from "react-native";
import Screen from "../components/Screen";
import ListItem from "../components/lists/ListItem";
import colors from "../config/colors";
import ListItemSeparator from "../components/lists/ListItemSeparator";
import AuthContext from "../auth/context";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { db } from "../config/firebase";
import { deleteUser } from "firebase/auth";
import { deleteDoc, doc, getDoc } from "firebase/firestore";
import { auth } from "../config/firebase";

function EditAccount({ navigation }) {
  const authContext = useContext(AuthContext);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [displayName, setDisplayName] = useState("");

  // Load name from Firestore every time screen opens
  useFocusEffect(
    React.useCallback(() => {
      const loadName = async () => {
        const uid = auth.currentUser?.uid;
        if (!uid) return;

        const userDoc = await getDoc(doc(db, "users", uid));
        if (userDoc.exists()) {
          const data = userDoc.data();
          setDisplayName(data.name || "Not set");

          if (authContext?.setUser) {
            authContext.setUser((prev) => ({
              ...prev,
              displayName: data.name,
            }));
          }
        }
      };

      loadName();
    }, [])
  );

  const menuItems = [
    {
      title: "Name",
      description: displayName,
      target: "EditAccountName",
    },
    {
      title: "Email",
      description: auth.currentUser?.email,
      target: "EditAccountEmail",
    },
    {
      title: "Change Password",
      target: "EditAccountPassword",
    },
  ];

  const { setUser } = useContext(AuthContext);

  const handleDeleteConfirm = () => {
    setShowDeleteModal(false);
    const uid = auth.currentUser.uid;

    deleteDoc(doc(db, "users", uid));
    deleteUser(auth.currentUser);
    setUser(null);
  };

  return (
    <Screen style={styles.screen}>
      <FlatList
        data={menuItems}
        keyExtractor={(item) => item.title}
        ItemSeparatorComponent={ListItemSeparator}
        renderItem={({ item }) => (
          <ListItem
            title={item.title}
            subTitle={item.description}
            titleStyle={{ paddingLeft: 0 }}
            onPress={() => navigation.navigate(item.target)}
            IconComponent={null}
            renderRightIcon={() => (
              <MaterialCommunityIcons
                name="chevron-right"
                size={28}
                color={colors.medium}
              />
            )}
          />
        )}
        scrollEnabled={false}
      />

      <View style={styles.container}>
        <ListItem
          title="Delete Account"
          onPress={() => setShowDeleteModal(true)}
          IconComponent={null}
          showChevron={false}
          titleStyle={{ color: colors.danger, fontWeight: "bold", paddingLeft: 0 }}
        />
      </View>

      <Modal visible={showDeleteModal} transparent animationType="fade">
        <View style={styles.modalOverlay}>
          <View style={styles.modalContainer}>
            <Text style={styles.modalTitle}>Confirm Delete</Text>
            <Text style={styles.modalMessage}>
              Are you sure you want to delete your account? This action cannot be undone.
            </Text>
            <View style={styles.modalButtons}>
              <TouchableOpacity
                style={[styles.modalButton, styles.cancelButton]}
                onPress={() => setShowDeleteModal(false)}
              >
                <Text style={styles.cancelText}>Cancel</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.modalButton, styles.confirmButton]}
                onPress={handleDeleteConfirm}
              >
                <Text style={styles.confirmText}>Delete</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </Screen>
  );
}

const styles = StyleSheet.create({
  screen: {
    backgroundColor: colors.light,
    paddingTop: 70,
  },
  container: {
    marginBottom: 250,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContainer: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.dark,
    marginBottom: 10,
  },
  modalMessage: {
    fontSize: 16,
    color: colors.medium,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "center",
  },
  modalButton: {
    marginLeft: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  cancelButton: {
    backgroundColor: colors.light,
  },
  confirmButton: {
    backgroundColor: colors.danger,
  },
  cancelText: {
    color: colors.dark,
    fontSize: 19,
  },
  confirmText: {
    color: colors.white,
    fontWeight: "bold",
    fontSize: 19,
  },
});

export default EditAccount;
