/**
 * Displays a scrollable list of energy-rich foods tailored for athletes.
 *
 * The list is sourced from a local config file (`energylist.js`) and rendered using `AppText` components.
 * Each item includes a label describing a food that supports athletic performance and sustained energy.
 *
 * The screen is styled with a bright background and bold orange text to emphasize vitality and nutrition.
 * This component is ideal for educational or wellness-focused apps promoting healthy eating habits.
 *
 * Generated by Copilot AI
 */

//importing all the necessary items

import React from "react";
import { FlatList, StyleSheet, View, ScrollView } from "react-native";

import AppText from "../components/AppText";
import Screen from "../components/Screen";
import colors from "../config/colors";
import en from "../config/energylist";

const energy = en.energy;

//pulling the array/list elements from the appropriate list in the config file

function Energy({navi}) {
    return (
      <Screen style={styles.container}>
	    <ScrollView>
          <AppText style={styles.title}>List of Energy-Filled Foods for Athletes</AppText>
        
          {energy.map(ener => (
			<AppText style={styles.text} key={ener.id}>{ener.label}</AppText>
          ))}
	    </ScrollView>
      </Screen>
    );
}

//How the list, title, and background will look on the screen

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.light,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    backgroundColor: colors.light,
  },
  title: {
    color: colors.buttonorange,
    fontSize: 30,
    marginBottom: 12,
    marginTop: 0,
    textAlign: "center",
  },
  text: {
    color: colors.buttonorange,
    fontSize: 20,
  },
  
});

//exporting the function

export default Energy;