/**
 * Displays a scrollable list of healthy fats recommended for adult diets.
 *
 * The list is sourced from a local config file (`fatlist.js`) and rendered using `AppText` components.
 * Each item highlights a nutrient-rich fat option that supports heart health, brain function, and overall wellness.
 *
 * A footnote provides dietary guidance, noting that fat intake should range from 30% to 75% of total calories,
 * depending on individual dietary goals. The screen is styled with warm gold tones to reflect richness and vitality.
 *
 * Generated by Copilot AI
 */

//importing all the necessary items

import React from "react";
import { FlatList, StyleSheet, View, ScrollView } from "react-native";

import AppText from "../components/AppText";
import Screen from "../components/Screen";
import colors from "../config/colors";
import healthyfats from "../config/fatlist";

const fats = healthyfats.fats;

//pulling the array/list elements from the appropriate list in the config file

function HealthyFats({navi}) {
    return (
	<Screen style={styles.container}>
	   <ScrollView>
              <AppText style={styles.title}>List of Healthy Fats for Adults*</AppText>
        
	      {fats.map(fat => (
          	   <AppText style={styles.text} key={fat.id}>{fat.label}</AppText>
        ))}

	<AppText style={styles.italic}>*The recommended amount of fats should be
	    anywhere between 30 (low-fat diet) - 75% (high-fat diet) of your total caloric intake.</AppText>

	  </ScrollView>
       </Screen>
    );
}

//How the list, title, and background will look on the screen

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.light,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    backgroundColor: colors.light,
  },
  title: {
    color: colors.buttongold,
    fontSize: 30,
    marginBottom: 10,
    marginTop: 0,
    textAlign: "center",
  },
  text: {
    color: colors.buttongold,
    fontSize: 20,
  },

  italic: {
    fontStyle: 'italic',
    textAlign: "left",
    marginBottom: 10,
    fontSize: 14,
  },
  
});

//exporting the function

export default HealthyFats;
