/**
 * FoodsForVitamin Component
 *
 * Displays a list of nutrient-rich foods that are good sources of a specific vitamin.
 * The vitamin data is passed via navigation route parameters and includes:
 * - `label`: the vitamin's name
 * - `use`: a brief description of its health benefits
 * - `good`: an array of food items that contain the vitamin
 *
 * The component renders a styled screen with a title, use case, and food list.
 * It is ideal for educational or health-focused apps that promote nutritional awareness.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { FlatList, StyleSheet, View, ScrollView, TouchableOpacity, Text, Image, Platform } from "react-native";

import AppText from "../components/AppText";
import AppButton from "../components/AppButton";
import Screen from "../components/Screen";
import colors from "../config/colors";
import foodz from "../config/foods";
import imageSource from "../config/photoBank";
import vitaminData from "../config/vitaminlist";
import LineDivider from "../components/Divider";

const { vitamins, vitaminLegend } = vitaminData;

//Takes the vitamin parameter set when navigating to display its name and list of good food
export const FoodsForVitamin = ({route, navigation}) => {
    const foodList = route.params.food.mapToo

    return (
        <Screen style={styles.screen}>
          <ScrollView
            contentContainerStyle={styles.scrollContent}
            showsVerticalScrollIndicator={false}
          >
            <AppText style={styles.title}>{route.params.food.label}</AppText>
            <AppText style={styles.italic}>{route.params.food.pageDesc}</AppText>
            <AppText style={styles.legendIntroText}>To know what a certain vitamin or mineral does for your body, click on its name. Each name is colored corresponding to one of the target areas below:</AppText>
            <View style={styles.legendContainer}>
              {vitaminLegend.map(item => (
                <View
                  key={item.label}
                  style={[styles.legendButton, { backgroundColor: item.color }]}
                >
                  <Text style={styles.legendText}>{item.label}</Text>
                </View>
              ))}
            </View>
            
            <LineDivider />

            {foodList.map(food => (
              <View style={styles.imageContainer} key={food.id}>
                <Text style={styles.imageText}>{food.label}</Text>
                <Image source={imageSource[food.picture]} style={[styles.image]} />
                <Text style={styles.smallText}>{food.desc}</Text>

                <View style={styles.listContainer}>
                  {food.vitaminList.map(vitamin => (
                    <View style={styles.vitaminContainer} key={vitamin.toString()}>
                      <TouchableOpacity
                        onPress={() => navigation.navigate('Vitamins',{vitamin: vitamins[vitamin]})}
                        style={[styles.button, { backgroundColor: vitamins[vitamin].buttonColor }]}
                        >
                          <Text style={styles.buttonText}>{vitamins[vitamin].label}</Text>
                      </TouchableOpacity>
                    </View>
                  ))}
                  </View>
              </View>
            ))}
          </ScrollView>
        </Screen>
    );
}

const styles = StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.light,
    },
    scrollContent: {
      paddingTop: 10,      // adds space under header before text
      paddingHorizontal: 15,
      paddingBottom: 80,  // ensures content is above bottom nav bar
      alignItems: "center",
    },

    title: {
      fontSize: 40,
      marginBottom: 15,
      marginTop: 0,
      textAlign: "center",
    },
    italic: {
      fontStyle: 'italic',
      textAlign: "center",
      marginBottom: 20,
      fontSize: 15,
    },

    // vitamin legend styles:
    legendIntroText: {
      // fontStyle: 'italic',
      fontWeight: "bold",
      textAlign: "center",
      marginBottom: 5,
      fontSize: 15,
    },
    legendContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
    },
    legendButton: {
      height: 35,
      minWidth: 80,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      margin: 4,
    },
    legendText: {
      fontSize: 10,
      color: colors.white,
      textTransform: "uppercase",
      fontWeight: "bold",
      fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    },

    listContainer: {
      flex: 1,
      flexDirection: 'row', // Align children horizontally
      flexWrap: 'wrap',
      justifyContent: 'center',
      paddingTop: 20,
    },
    imageText: {
        fontSize: 18,
        textTransform: "uppercase",
        fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
        fontWeight: "bold",
        //position: 'absolute',
        color: colors.black,
        alignSelf: 'center',
        //top: 80,
        paddingBottom: 5,
    },
    smallText: {
        fontSize: 14,
        fontStyle: 'italic',
        textAlign: "center",
        color: colors.medium,
        fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
        top: 10,
    },
    image: {
        height: 150,
        width: "100%",
        borderRadius: 25,
    },
    imageContainer: {
      padding: 20,
      flexDirection: 'column', // Align children horizontally
      alignItems: 'center', // Optionally, center items vertically
      width: 375,
    },
    vitaminContainer: {
      justifyContent: 'center', // Centers each row of buttons vertically
      alignItems: 'center', // Optionally, center items vertically
      padding: 5,
      width: '33%',
    },
    button: {
      height: 50,
      width: 100,
      borderRadius: 25,
      justifyContent: "center",
      alignItems: "center",
    },
    buttonText: {
      fontSize: 12,
      color: colors.white,
      textTransform: "uppercase",
      fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
      fontWeight: "bold",
      position: 'absolute',
    },
  });

  export default FoodsForVitamin;