/**
 * HelpScreen Component
 *
 * Provides users with guidance on how to use the ELTR mobile app.
 * Displays a brief message and includes a clickable link to the official user manual hosted at:
 * https://eatliketherainbow.org/eltr-mobile-app/
 *
 * The screen is styled with centered layout and bold, readable text.
 * Ideal for onboarding, troubleshooting, or general support access within the app.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { StyleSheet, ScrollView, Text, Linking } from "react-native";

import AppText from "../components/AppText";
import Screen from "../components/Screen";
import colors from "../config/colors";

function HelpScreen(props) {
  return (
   <Screen style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <AppText style={styles.title}>Frequently Asked Questions</AppText>

        <AppText style={styles.subTitle}>Question?</AppText>
	      <AppText style={styles.text}>
          For more information on how to use the ELTR app, please read the user
	        manual <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org/eltr-mobile-app/')}>here</Text>!
        </AppText>

        <AppText style={styles.subTitle}>Question?</AppText>
	      <AppText style={styles.text}>
          For more information on how to use the ELTR app, please read the user
	        manual <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org/eltr-mobile-app/')}>here</Text>!
        </AppText>

        <AppText style={styles.subTitle}>Question?</AppText>
	      <AppText style={styles.text}>
          For more information on how to use the ELTR app, please read the user
	        manual <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org/eltr-mobile-app/')}>here</Text>!
        </AppText>

        <AppText style={styles.subTitle}>Question?</AppText>
	      <AppText style={styles.text}>
          For more information on how to use the ELTR app, please read the user
	        manual <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org/eltr-mobile-app/')}>here</Text>!
        </AppText>

        <AppText style={styles.subTitle}>Question?</AppText>
	      <AppText style={styles.text}>
          For more information on how to use the ELTR app, please read the user
	        manual <Text style={styles.link1} onPress={() => Linking.openURL('https://eatliketherainbow.org/eltr-mobile-app/')}>here</Text>!
        </AppText>
      </ScrollView>
    </Screen>
  );
}

//how info is being displayed
const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: colors.light,
  },
  title: {
    color: colors.black,
    fontWeight: "bold",
    fontSize: 36,
    marginTop: 10,
    textAlign: "center",
  },
  subTitle: {
    color: colors.primary,
    fontWeight: "600",
    fontSize: 25,
    marginTop: 40,
    marginBottom: 2,
    textAlign: "center",
  },
  text: {
    textAlign: "center",
    fontSize: 18,
  },
  link1: {
    color: colors.eltrdarkblue,
    fontWeight: "bold",
    textDecorationLine: 'underline',
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: {
    paddingBottom: 50, // make sure you can view the text above the navbar
  },
  });

//exporting function
export default HelpScreen;