/**
 * Home Component
 *
 * Serves as the main landing screen for the ELTR app, offering users quick access to educational resources
 * and ingredient safety tools. It combines interactive navigation buttons with a rotating carousel of fun facts.
 *
 * Key Features:
 * - Displays a randomized carousel of nutrition-related fun facts using `react-native-reanimated-carousel`
 * - Includes banner images for visual engagement
 * - Provides navigation buttons grouped by:
 *   • Positive nutritional categories: Vitamins & Minerals, Healthy Fats, Energy Foods
 *   • Ingredient safety categories: Food Dyes, Preservatives, Sugars
 * - Uses custom-styled buttons and layout for a clean, responsive interface
 * - Designed for health-conscious users seeking quick access to food education and safety insights
 *
 * Styling:
 * - Organized into top and bottom button groups with distinct color coding
 * - Carousel and banners are centered and padded for optimal readability
 * - Responsive layout adapts to screen width using `Dimensions`
 *
 * Dependencies:
 * - React Native components
 * - Custom components: `AppText`, `AppButton`, `Screen`
 * - External libraries: `react-native-reanimated-carousel`
 * - Config data: `funfact.js`, `colors.js`, `routes.js`
 *
 * Generated by Copilot AI
 */

import React, { Component } from "react";
import {
  StyleSheet,
  View,
  Dimensions,
  Text,
  TouchableOpacity,
  Image,
  Platform,
  Linking,
  ScrollView
} from "react-native";
import Carousel from "react-native-reanimated-carousel";

import AppText from "../components/AppText";
import Screen from "../components/Screen";
import colors from "../config/colors";
import AppButton from "../components/AppButton";
import choices from "../config/funfact";

const windowWidth = Dimensions.get("window").width; // used to map fun facts

// this code will shuffle ALL food facts, and then only show the top 15 of them to the user
const getfunfacts = (funfacts) => {
  return [...funfacts]               // copy foodfacts array
    .sort(() => 0.5 - Math.random()) // shuffle the copy
    .slice(0, 15);                   // take first 15
};

// this code will shuffle ALL food facts and show to user
// const funfacts = [...choices.funfact].sort(
//   () => 0.5 - Math.random()
// );

// var random_index = 0;
// for (var i = 0; i < 18; i++) {
//   random_index = Math.floor(Math.random() * funfact.length);
//   //console.log({random_index});
//   funfact.splice(random_index, 1);
// }
//console.log("funfact size: %d", funfact.length);

export class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
      images: [
        require("../assets/transparant.png"),
        require("../assets/adamBanner.png"),
        require("../assets/bannerSponsor.png"),
      ],
      activeIndex: 0,
      carouselItems: getfunfacts(choices.funfact).map((fact) => ({
        id: fact.id,
        label: fact.label,
      })),
      // carouselItems: funfact.map((fact) => {
      //   return { text: <AppText key={fact.id}>{fact.label}</AppText> };
      // }),
    };
  }

  // _renderItem({ item, index }) {
  //   return (
  //     <View
  //       style={{
  //         backgroundColor: "floralwhite",
  //         borderRadius: 20,
  //         height: 200,
  //         alignItems: "center",
  //         padding: 2,
  //         marginLeft: 25,
  //         marginRight: 25,
  //       }}
  //     >
  //       <Text style={{ fontSize: 25 }}>{item.title}</Text>
  //       <Text>{item.text}</Text>
  //     </View>
  //   );
  // }

  render() {
    return (
      <Screen style={styles.container}>
        <ScrollView contentContainerStyle={{ paddingBottom: 40 }}>
          {/* <View style={styles.grid}> */}
            <Image
              style={styles.logo}
              source={require("../assets/appsponsor.png")}
            />
            {/* <Image
              style={styles.eltrlogo}
              source={require("../assets/eltrRainbow_new.png")}
            /> */}
          {/* </View> */}

          <View style={styles.flexContainer}>
            <Carousel
              loop
              autoPlay
              autoPlayInterval={6500}
              width={windowWidth * 0.9}
              height={120}
              data={this.state.carouselItems}
              scrollAnimationDuration={1000}
              renderItem={({ item }) => (
                <View style={styles.carouselItem}>
                  <AppText style={styles.carouselText}>
                    {item.label}
                  </AppText>
                </View>
              )}
            />
          </View>

          <View style={styles.buttonGood}>
            <TouchableOpacity
              onPress={() =>
                this.props.navigation.navigate('EssentialNutrients')
              }
              style={[styles.button]}
            >
              <Image
                source={require("../assets/essential_nutrients.png")}
                style={[styles.image]}
              />
              <Text style={styles.buttonText}>Essential Nutrients</Text>
            </TouchableOpacity>

            <TouchableOpacity
              onPress={() =>
                this.props.navigation.navigate('HarmfulIngredientsStack')
              }
              style={[styles.button]}
            >
              <Image
                source={require("../assets/harmful_ingredients.png")}
                style={[styles.image]}
              />
              <Text style={styles.buttonText}>Harmful Ingredients</Text>
            </TouchableOpacity>

            <TouchableOpacity
              onPress={() => this.props.navigation.navigate('FoodFacts')}
              style={[styles.button]}
            >
              <Image
                source={require("../assets/food_facts.png")}
                style={[styles.image]}
              />
              <Text style={styles.buttonText}>Other Food Facts</Text>
            </TouchableOpacity>

            {/* Donation Section */}
            <View style={styles.donationContainer}>
              <Text style={styles.donationTitle}>
                Every Contribution Makes This Real
              </Text>

              <Text style={styles.donationText}>
                Private sponsorships and donations will enable Eat Like The
                Rainbow™ to develop and maintain the highest level of educational
                fun through regular and consistent updates, new Funny Food
                Facts™, Create a Fact-Snack™ and many more interactive activities
                that will bring reward and awards to schools that participate.
              </Text>

              <Text style={styles.donationText}>
                Click the button below to be taken to a PayPal donation portal.
                Eat Like the Rainbow™, Inc is a recognized 501(c)(3) charitable
                organization. All contributions are tax deductible.
              </Text>

              <TouchableOpacity
                style={styles.donateButton}
                onPress={() =>
                  Linking.openURL(
                    "https://www.paypal.com/fundraiser/charity/3629811"
                  )
                }
              >
                <Text style={styles.donateButtonText}>DONATE</Text>
              </TouchableOpacity>
            </View>
          </View>
        </ScrollView>
      </Screen>
    );
  }
}

/* for flex component in container
1 -> (only top half)
2 & 3 ->(all but last button)
4 -> (all 6)
*/

const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.light,
  },
  flexContainer: {
    alignItems: "center",
    marginVertical: 20,
    // flexDirection: "row",
    // justifyContent: "center",
    // top: 100,
  },

  // grid: {
  //   flexDirection: "row",
  //   justifyContent: "space-between",
  //   alignItems: "center",
  //   paddingHorizontal: 45,
  //   marginTop: 15,
  // },
  logo: {
    alignSelf: "center",
		height: 75,
    width: 185, 
		resizeMode: 'contain',
    overflow: "hidden",
    marginTop: 10,
    // marginBottom: 10,
    // width: 250,
    // top: 0,
    // position: "absolute",
    // justifyContent: "center",
  },
  // eltrlogo: {
  //   // alignSelf: "center",
	// 	height: 100,
  //   width: 100, 
	// 	resizeMode: 'contain',
  //   overflow: "hidden",
  //   marginTop: 10,
  //   borderRadius: 20,
  // },

  carouselItem: {
    backgroundColor: "floralwhite",
    borderRadius: 20,
    height: 120,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
    padding: 10,
  },
  carouselText: {
    fontSize: 17,
    textAlign: "center",
  },

  buttonGood: {
    // flexDirection: "column",
    width: "90%",
    alignSelf: "center",
    // marginTop: 150,
  },
  text: {
    color: colors.primary,
  },
  button: {
    height: 120,
    width: "100%",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    padding: 3,
    marginVertical: 5,
    // iOS Shadow properties
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    // Android Elevation property
    elevation: 6,
  },
  buttonText: {
    fontSize: 24,
    textAlign: "center",
    color: colors.white,
    textTransform: "uppercase",
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
    position: "absolute",
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: 25,
    resizeMode: "cover", // Or 'contain', 'stretch', etc.
  },

  donationContainer: {
    backgroundColor: "#EDEDED",
    padding: 15,
    borderRadius: 20,
    marginTop: 25,
    marginBottom: 30,
  },
  donationTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    color: "#444",
  },
  donationText: {
    fontSize: 14,
    textAlign: "center",
    color: "#555",
    marginBottom: 8,
    lineHeight: 20,
  },
  donateButton: {
    backgroundColor: "#6A3DBB",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    alignSelf: "center",
    marginTop: 10,
  },
  donateButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
});

export default Home;
