/**
 * LoginScreen Component
 *
 * Authenticates users via Firebase and retrieves profile data from Firestore.
 * On success, stores user and username in global context.
 * Includes form validation, error handling, and navigation to registration.
 *
 * Uses: Firebase Auth & Firestore, Yup, custom form components, AuthContext.
 * 
 * 🔥 Firebase Integration
 * - Uses `signInWithEmailAndPassword` from Firebase Auth to authenticate users.
 * - On success, retrieves user profile from Firestore (`users` collection) using `getDoc` and `doc`.
 * - Stores authenticated user and username in global context for app-wide access.
 * 
 * Generated by Copilot AI
 */

import React, { useContext, useState } from "react";
import { Image, ImageBackground, StyleSheet, View, Platform } from "react-native";
import * as Yup from "yup";

import ScreenAuth from "../components/ScreenAuth";
import { AppForm, AppFormField, SubmitButton } from "../components/forms";
import colors from "../config/colors";

import { auth, db } from "../config/firebase";
import { signInWithEmailAndPassword } from "firebase/auth";
import { doc, getDoc } from "firebase/firestore";
import { clearAllOptionCaches } from "../utility/fetchOptions";

import AppText from "../components/AppText";
import AuthContext from "../auth/context";
import ErrorMessage from "../components/forms/ErrorMessage";
import AppButton from "../components/AppButton";
import routes from "../navigation/routes";

const validationSchema = Yup.object().shape({
  email: Yup.string().required().email().label("Email"),
  password: Yup.string().required().min(6).label("Password"),
});

function LoginScreen( { navigation} ) {
  const authContext = useContext(AuthContext);
  const [loginFailed, setLoginFailed] = useState(false);


  const handleSubmit = async ({ email, password }) => {
    try {
      const userCredential = await signInWithEmailAndPassword(auth, email, password);
      const user = userCredential.user;

      authContext.setUser(user);

      // CLEAR ALL CACHES EVERY TIME USER LOGS IN
      // this way new firebase updates will load in
      await clearAllOptionCaches();

      const userDoc = await getDoc(doc(db, "users", user.uid));

      if (userDoc.exists()) {
        authContext.setUsername(userDoc.data().name);
      } else {
        console.log("No such document!");
      }

      setLoginFailed(false);
    } catch (error) {
      setLoginFailed(true);
      console.log("Login error:", error);
    }
  };

  return (
    <ImageBackground
      blurRadius={Platform.OS === "android" ? 1 : 5}
      style={styles.background}
      source={require("../assets/welcome_2.png")}
    >
      {/* VOIDED - added transparentBackground to ensure background image fully shows */}
      <ScreenAuth style={styles.container}>
        <Image
            style={styles.logo}
            source={require("../assets/eltrRainbow_new.png")}
          ></Image>
          <View style={styles.boxContainer}>
            <View style={styles.buttonContainer}>
            <AppForm
              initialValues={{ email: "", password: "" }}
              onSubmit={handleSubmit}
              validationSchema={validationSchema}
              >
              <ErrorMessage
                error="Invalid email and/or password."
                visible={loginFailed}
              />
              <AppFormField
                name="email"
                autoCaptilize="none"
                autoCorrect={false}
                keyboardType="email-address"
                icon="email"
                placeholder="Email"
                textContentType="emailAddress"
              />
              <AppFormField
                name="password"
                autoCaptilize="none"
                autoCorrect={false}
                icon="lock"
                placeholder="Password"
                secureTextEntry
                textContentType="password"
              />
              <View style={styles.fixContainer}>
                <SubmitButton title="Login" color='black' />

                {/* <AppText style={styles.text}>
                  —————— OR ——————
                </AppText> */}

                <View style={styles.separatorContainer}>
                  <View style={styles.line} />
                  <AppText style={styles.text}>OR</AppText>
                  <View style={styles.line} />
                </View>

                <AppButton
                  title="register"
                  onPress={() => navigation.navigate(routes.REGISTER)}
                />

                <AppText style={styles.forgotText} onPress={() => navigation.navigate(routes.RESET_PASSWORD)}>
                  Forgot password?
                </AppText>
              </View>
            </AppForm>
          </View>
        </View>
      </ScreenAuth>
    </ImageBackground>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    // top: 15,
    // padding: 2,
  },
  boxContainer: {
    width: "100%",
    maxWidth: 340,
    marginBottom: 28,
    // marginHorizontal: 25,
    // justifyContent: 'center', // Center the box vertically
    alignItems: 'center',     // Center the box horizontally
    backgroundColor: 'white',
    borderWidth: 3,
    borderColor: 'purple',
    borderRadius: 25,
    paddingVertical: 20,
    // overflow: "hidden",
  },
  buttonContainer: {
    width: "100%",
    paddingHorizontal: 20,
  },
  background: {
    flex: 1,
    justifyContent: "center",
    // justifyContent: "flex-end",
    alignItems: "center",
  },
  logo: {
    alignSelf: "center",
    borderRadius: 25,
    bottom: 20,
  },
  separatorContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: colors.medium,
  },
  text: {
    marginHorizontal: 10,
    color: colors.medium,
    fontSize: 20,
    textAlign: "center",
  },
  forgotText: {
    color: colors.medium,
    fontSize: 18,
    textDecorationLine: 'underline',
    textAlign: "right",
    marginTop: 10,
  },
});

export default LoginScreen;
