/**
 * Preservatives Component
 *
 * Displays a scrollable list of preservatives sourced from `badlists.js`.
 * Each item is styled for readability and grouped under a purple-themed title.
 *
 * Used for ingredient awareness and educational reference in the ELTR app.
 * 
 * Generated by Copilot AI
 */

//importing all the necessary items

import React from "react";
import { FlatList, StyleSheet, View, ScrollView } from "react-native";

import AppText from "../components/AppText";
import Screen from "../components/Screen";
import colors from "../config/colors";
import choices from "../config/badlists";

const preservativesChoices = choices.preservativesChoices;

//pulling the array/list elements from the appropriate list in the config file

function Preservatives({navi}) {
    return (
      <Screen style={styles.container}>
	    <ScrollView>
          <AppText style={styles.title}>List of Preservatives</AppText>
        
          {preservativesChoices.map(preservative => (
			<AppText style={styles.text} key={preservative.id}>{preservative.label}</AppText>
          ))}
	    </ScrollView>
      </Screen>
    );
}

//How the list, title, and background will look on the screen

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.light,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    backgroundColor: colors.light,
  },
  title: {
    color: colors.eltrpurple,
    fontSize: 36,
    marginBottom: 5,
    marginTop: 0,
    textAlign: "center"
  },
  text: {
    color: colors.eltrpurple,
    fontSize: 20,
  },
  
});

//exporting the function

export default Preservatives;