/**
 * RegisterScreen Component
 *
 * Allows new users to create an account in the ELTR app.
 * Collects name, email, and password with validation, then registers the user via Firebase.
 *
 * Key Features:
 * - Form validation using Yup (including password confirmation)
 * - Creates user with Firebase Auth
 * - Stores user profile (name) in Firestore under `users` collection
 * - Updates global AuthContext with user and username
 * - Includes navigation back to login screen
 *
 * Uses: Firebase Auth & Firestore, Yup, AuthContext, custom form components, navigation routes.
 * 
 *  Firebase Integration
 * - Uses `createUserWithEmailAndPassword` to register a new user.
 * - On success, stores the user in global context and saves their name to Firestore (`users` collection).
 * - Firestore document is created using the user's UID as the key.
 *
 * Generated by Copilot AI
 */

import React, { useContext } from "react";
import { StyleSheet, Image, ImageBackground, View, Platform } from "react-native";
import * as Yup from "yup";
import AuthContext from "../auth/context";

import { AppForm, AppFormField, SubmitButton } from "../components/forms";
import ScreenAuth from "../components/ScreenAuth";
import colors from "../config/colors";
import { auth, db } from "../config/firebase";

import { clearAllOptionCaches } from "../utility/fetchOptions";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { doc, setDoc } from "firebase/firestore"; 

import routes from "../navigation/routes";
import AppButton from "../components/AppButton";
import AppText from "../components/AppText";

// Validation schema for registration form
const validationSchema = Yup.object().shape({
  name: Yup.string().required().label("Name"),
  email: Yup.string().required().email().label("Email"),
  password: Yup.string().required().min(6).label("Password"),
  confirmPassword: Yup.string()
    .required()
    .oneOf([Yup.ref("password"), null], "Passwords must match.")
    .label("Confirm Password"),
});

function RegisterScreen({ navigation }) {
  const authContext = useContext(AuthContext);

  // Handles form submission
  const handleSubmit = async ({ name, email, password }) => {
    try {
      // CREATE USER WITH EMAIL AND PASSWORD
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      const user = userCredential.user;

      // UPDATE GLOBAL CONTEXT
      authContext.setUser(user);
      authContext.setUsername(name);

      // STORE USER PROFILE IN FIRESTORE
      // Added showIntro: true
      await setDoc(doc(db, "users", user.uid), {
        name: name,
        email: email,
        conditions: [],
        allergies: [],
        dietary_preferences: [],
        showIntro: true
      });

      console.log("Firestore document successfully written for UID:", user.uid);

      // CLEAR ALL CACHES EVERY TIME USER LOGS IN
      // this way new firebase updates will load in
      await clearAllOptionCaches();

    } catch (error) {
      console.error("Error registering user:", error.message);
    }
  };

  return (
    <ImageBackground
      blurRadius={Platform.OS === "android" ? 1 : 5}
      style={styles.background}
      source={require("../assets/welcome_2.png")}
    >
      <ScreenAuth style={styles.container}>
        <Image
          style={styles.logo}
          source={require("../assets/appsponsor_2.png")}
        />

        <View style={styles.boxContainer}>
          <AppForm
            initialValues={{
              name: "",
              email: "",
              password: "",
              confirmPassword: "",
            }}
            onSubmit={handleSubmit}
            validationSchema={validationSchema}
          >
            <AppFormField
              name="name"
              autoCapitalize="words"
              autoCorrect={false}
              icon="account"
              placeholder="Name"
              textContentType="name"
            />

            <AppFormField
              name="email"
              autoCapitalize="none"
              autoCorrect={false}
              keyboardType="email-address"
              icon="email"
              placeholder="Email"
              textContentType="emailAddress"
            />

            <AppFormField
              name="password"
              autoCapitalize="none"
              autoCorrect={false}
              icon="lock"
              placeholder="Password"
              secureTextEntry
              textContentType="password"
            />

            <AppFormField
              name="confirmPassword"
              autoCapitalize="none"
              autoCorrect={false}
              icon="lock-question"
              placeholder="Confirm Password"
              secureTextEntry
              textContentType="password"
            />

            <View style={styles.fixContainer}>
              <SubmitButton title="Register" color="black" />

              <View style={styles.separatorContainer}>
                <View style={styles.line} />
                <AppText style={styles.text}>OR</AppText>
                <View style={styles.line} />
              </View>

              <AppButton
                title="back"
                onPress={() => navigation.navigate(routes.LOGIN)}
              />
            </View>
          </AppForm>
        </View>
      </ScreenAuth>
    </ImageBackground>
  );
}

// STYLES ARE LEFT UNCHANGED
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
  },
  boxContainer: {
    width: "100%",
    maxWidth: 340,
    alignItems: "center",
    backgroundColor: "white",
    marginBottom: 20,
    marginHorizontal: 25,
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "purple",
    borderRadius: 25,
    paddingVertical: 20,
  },
  background: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  logo: {
    alignSelf: "center",
    bottom: 30,
    borderRadius: 25,
    backgroundColor: "white",
  },
  separatorContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: colors.medium,
  },
  text: {
    marginHorizontal: 10,
    color: colors.medium,
    fontSize: 20,
    textAlign: "center",
  },
  fixContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 15,
  },
});

export default RegisterScreen;