/**
 * ResetPasswordScreen Component
 *
 * Informs users that login is required to protect their health data.
 * Provides navigation options to log in or register.
 *
 * Key Features:
 * - Styled background and logo for brand consistency
 * - Message about privacy and login requirement
 * - Buttons to navigate to Login and Register screens
 *
 * Generated by Copilot AI
 */

import React, { useContext, useState } from "react";
import { Image, ImageBackground, StyleSheet, View, Platform } from "react-native";
import * as Yup from "yup";
import { AppForm, AppFormField, SubmitButton } from "../components/forms";
import colors from "../config/colors";
import { auth, db } from "../config/firebase";
import { doc, getDoc } from "firebase/firestore";
import Screen from "../components/Screen";
import AppText from "../components/AppText";
import AuthContext from "../auth/context";
import {ErrorMessage, GoodMessage} from "../components/forms/ErrorMessage";
import AppButton from "../components/AppButton";
import routes from "../navigation/routes";
import {getAuth, sendPasswordResetEmail } from "firebase/auth";

const validationSchema = Yup.object().shape({
  email: Yup.string().required().email().label("Email"),
});

function ResetPasswordScreen( { navigation} ) {
  const authContext = useContext(AuthContext);
  const [loginFailed, setLoginFailed] = useState(false);
  const [validEmail, setValidEmail] = useState(false);
  const auth = getAuth();

  const handleSubmit = async ({ email }) => {
    try {
      await sendPasswordResetEmail(auth, email)
      console.log("Working?");
      setValidEmail(true);
      /*
      OLD CODE
      authContext.setUser(user);
      const userDoc = await getDoc(doc(db, "users", user.uid));

      if (userDoc.exists()) {
        authContext.setUsername(userDoc.data().name);
      } else {
        console.log("No such document!");
      }*/
    } catch (error) {
      setLoginFailed(true);
      console.log("Login error:", error);
    }
  };

  return (
    <ImageBackground
      blurRadius={Platform.OS === "android" ? 1 : 5}
      style={styles.background}
      source={require("../assets/welcome_2.png")}
    >
      <Screen style={styles.container}>
        <Image
          style={styles.logo}
          source={require("../assets/eltrRainbow_new.png")}
        ></Image>
      <View style={styles.boxContainer}>
        <View style={styles.buttonContainer}>
          <AppForm
            initialValues={{ email: ""}}
            onSubmit={handleSubmit}
            validationSchema={validationSchema}
            >
            <ErrorMessage
              error="Invalid email."
              visible={loginFailed}
            />
            <GoodMessage
              //Temporary Holder
              result="Valid email."
              visible={validEmail}
            />
            <AppFormField
              name="email"
              autoCaptilize="none"
              autoCorrect={false}
              keyboardType="email-address"
              icon="email"
              placeholder="Email"
              textContentType="emailAddress"
            />
            <View style={styles.fixContainer}>
              <SubmitButton title="CONTINUE" color='black' />
              <AppButton
              title="cancel"
              onPress={() => navigation.navigate(routes.LOGIN)}
              />
            </View>
          </AppForm>
        </View>
      </View>
      </Screen>
    </ImageBackground>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 10,
  },
  boxContainer: {
    justifyContent: 'center', // Center the box vertically
    alignItems: 'center',     // Center the box horizontally
    backgroundColor: 'white',
    borderWidth: 3,
    borderColor: 'purple',
    borderRadius: 25,
    overflow: "hidden",
  },
  buttonContainer: {
    padding: 20,
    width: "100%",
  },
  background: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  logo: {
    alignSelf: "center",
    marginBottom: 20,
    borderRadius: 25,
  },
  text: {
    color: colors.medium,
    fontSize: 20,
    textAlign: "center",
  },
  forgotText: {
    color: colors.medium,
    fontSize: 18,
    textDecorationLine: 'underline',
    textAlign: "right",
  },
});

export default ResetPasswordScreen;
