/**
 * ScanningScreen Component
 *
 * Uses the device camera to scan barcodes and fetch product data.
 * On successful scan, navigates to the FOOD_ITEM screen with product details.
 *
 * Key Features:
 * - Requests camera permission on mount
 * - Uses Expo Camera to scan barcodes
 * - Calls product API to retrieve item data
 * - Displays loading indicator during fetch
 * - Handles permission states and screen focus
 *
 * Generated by Copilot AI
 */

import React, { useState, useEffect } from "react";
import { View, StyleSheet, ActivityIndicator, Text } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useIsFocused } from "@react-navigation/native";

import colors from "../config/colors";
import routes from "../navigation/routes";
import productApi from "../api/products";

function ScanningScreen({ navigation }) {
  const [permission, requestPermission] = useCameraPermissions();
  const [loading, setLoading] = useState(false);
  const isFocused = useIsFocused();

  const barcodeScanned = async ({ data }) => {
    setLoading(true);
     try {
      const response = await productApi.getProduct(data);
      navigation.navigate(routes.FOOD_ITEM, response.data);
    } finally {
      setLoading(false);
    }
    // OLD
    // const response = await productApi.getProduct(barcode);
    // setLoading(false);
    // navigation.navigate(routes.FOOD_ITEM, response.data);
  };

 useEffect(() => {
    if (!permission?.granted) {
      requestPermission();
    }
  }, [permission]);
  // useEffect(() => {
  //   (async () => {
  //     const { status } = await Camera.requestCameraPermissionsAsync();
  //     setHasPermission(status === "granted");
  //   })();
  // }, []);

  if (!permission) return <View />;
  if (!permission.granted) return <Text>No access to camera</Text>;
  // if (hasPermission === null) {
  //   return <View />;
  // }
  // if (hasPermission === false) {
  //   return <Text>No access to camera</Text>;
  // }

 return (
    <View style={styles.container}>
      {isFocused && (
        <CameraView
          style={StyleSheet.absoluteFill}
          facing="back"
          onBarcodeScanned={barcodeScanned}
        />
      )}

      <View style={styles.overlay}>
        <View style={styles.barcodeBorder}>
          <ActivityIndicator
            animating={loading}
            size="large"
            color={colors.primary}
          />
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "black",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  barcodeBorder: {
    borderWidth: 4,
    width: "75%",
    height: "30%",
    borderColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
  },
});

export default ScanningScreen;
