/**
 * ScanningScreen Component
 *
 * Uses the device camera to scan barcodes and fetch product data.
 * On successful scan, navigates to the FOOD_ITEM screen with product details.
 *
 * Key Features:
 * - Requests camera permission on mount
 * - Uses Expo Camera to scan barcodes
 * - Calls product API to retrieve item data
 * - Displays loading indicator during fetch
 * - Handles permission states and screen focus
 *
 * Generated by Copilot AI
 */

import React, { useState, useEffect, useCallback, useRef } from "react";
import { View, StyleSheet, ActivityIndicator, Text, Animated, } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useIsFocused, useFocusEffect } from "@react-navigation/native";

import colors from "../config/colors";
import routes from "../navigation/routes";
import productApi from "../api/products";

function ScanningScreen({ navigation }) {
  const [permission, requestPermission] = useCameraPermissions();
  const [loading, setLoading] = useState(false);
  const isFocused = useIsFocused();
  const scanLock = useRef(false);

  {/* un-comment below block to simulate barcode scan on android studio */}
  // const MOCK_BARCODE = "5034467000216"; // replace this to test different food products
  // const mockScan = () => {
  //   barcodeScanned({ data: MOCK_BARCODE });
  // };

  const barcodeScanned = async ({ data }) => {
    if (scanLock.current) return; // block repeat scans
    
    scanLock.current = true;
    setLoading(true);
    
    // console.time("API_CALL");

    try {
      const response = await productApi.getProduct(data);
      
      // console.timeEnd("API_CALL");

      if (!response || !response.data) {
        console.log("Invalid/empty API response:", response);
        throw new Error("Invalid/empty API response");
      }
      
      navigation.navigate(routes.FOOD_ITEM, response.data);
    } catch (error) {
      console.log("Scan error:", error);
      setHasScanned(false); // allow rescan 
    } finally {
      setLoading(false);
    }
    // OLD
    // const response = await productApi.getProduct(barcode);
    // setLoading(false);
    // navigation.navigate(routes.FOOD_ITEM, response.data);
  };

  useFocusEffect(
    useCallback(() => {
      scanLock.current = false;
      setLoading(false);
    }, [])
  );

  useEffect(() => {
    if (!permission?.granted) {
      requestPermission();
    }
  }, [permission]);

  if (!permission) return <View />;
  if (!permission.granted) 
    return (
      <View style={styles.permissionContainer}>
        <Text>No access to camera</Text>
      </View>
    );

 return (
    <View style={styles.container}>

    {/* un-comment below block to simulate barcode scan on android studio */}
        {/* <View style={styles.mockButton}>
          <Button
            title="Mock Scan (Emulator)"
            onPress={mockScan}
            disabled={loading}
            color={colors.primary}
          />
        </View> */}

      {isFocused && !loading && (
        <CameraView
          style={StyleSheet.absoluteFill}
          facing="back"
          onBarcodeScanned={barcodeScanned}          
          zoom={0.1} // prevents 0.5 zoom camera effect
        />
      )}

      {!loading && (
        <View style={styles.overlay}>
          <View style={styles.barcodeBorder} />
        </View>
      )}

      {loading && (
        <View style={styles.loadingOverlay}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.loadingText}>Analyzing product...</Text>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "black",
  },
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  barcodeBorder: {
    borderWidth: 4,
    width: "75%",
    height: "30%",
    borderColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.light,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "black",
    marginTop: 15,
    fontSize: 16,
  },
  // un-comment below style block to simulate android barcode scan
  // mockButton: {
  //   position: "absolute",
  //   bottom: 40,
  //   alignSelf: "center",
  //   backgroundColor: "white",
  //   padding: 6,
  //   borderRadius: 8,
  //   zIndex: 9999,
  //   elevation: 10,
  // },
});

export default ScanningScreen;
