/**
 * ScanningScreen Component
 *
 * Uses the device camera to scan barcodes and fetch product data.
 * On successful scan, navigates to the FOOD_ITEM screen with product details.
 *
 * Key Features:
 * - Requests camera permission on mount
 * - Uses Expo Camera to scan barcodes
 * - Calls product API to retrieve item data
 * - Displays loading indicator during fetch
 * - Handles permission states and screen focus
 *
 * Generated by Copilot AI
 */

import React, { useState, useEffect, useCallback } from "react";
import { View, StyleSheet, ActivityIndicator, Text, Button } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useIsFocused, useFocusEffect } from "@react-navigation/native";

import colors from "../config/colors";
import routes from "../navigation/routes";
import productApi from "../api/products";

function ScanningScreen({ navigation }) {
  const [permission, requestPermission] = useCameraPermissions();
  const [loading, setLoading] = useState(false);
  const isFocused = useIsFocused();
  const [hasScanned, setHasScanned] = useState(false);

  {/* un-comment below block to simulate barcode scan on android studio */}
  // const MOCK_BARCODE = "5034467000216"; // replace this to test different food products
  // const mockScan = () => {
  //   barcodeScanned({ data: MOCK_BARCODE });
  // };


  const barcodeScanned = async ({ data }) => {
    if (hasScanned) return;   // block repeat scans

    setHasScanned(true);
    setLoading(true);
    
    try {
      const response = await productApi.getProduct(data);
      navigation.navigate(routes.FOOD_ITEM, response.data);
    } finally {
      setLoading(false);
    }
    // OLD
    // const response = await productApi.getProduct(barcode);
    // setLoading(false);
    // navigation.navigate(routes.FOOD_ITEM, response.data);
  };

  useFocusEffect(
    useCallback(() => {
      setHasScanned(false);
      setLoading(false);
    }, [])
  );

  useEffect(() => {
    if (!permission?.granted) {
      requestPermission();
    }
  }, [permission]);

  if (!permission) return <View />;
  if (!permission.granted) return <Text>No access to camera</Text>;

 return (

    <View style={styles.container}>

    {/* un-comment below block to simulate barcode scan on android studio */}
        {/* <View style={styles.mockButton}>
          <Button
            title="Mock Scan (Emulator)"
            onPress={mockScan}
            disabled={loading}
            color={colors.primary}
          />
        </View> */}

      {isFocused && (
        <CameraView
          style={StyleSheet.absoluteFill}
          facing="back"
          onBarcodeScanned={hasScanned ? undefined : barcodeScanned}          
          zoom={0.1} // prevents 0.5 zoom camera effect
        />
      )}

      <View style={styles.overlay}>
        <View style={styles.barcodeBorder}>
          <ActivityIndicator
            animating={loading}
            size="large"
            color={colors.primary}
          />
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "black",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  barcodeBorder: {
    borderWidth: 4,
    width: "75%",
    height: "30%",
    borderColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
  },
  // un-comment below style block to simulate android barcode scan
  // mockButton: {
  //   position: "absolute",
  //   bottom: 40,
  //   alignSelf: "center",
  //   backgroundColor: "white",
  //   padding: 6,
  //   borderRadius: 8,
  //   zIndex: 9999,
  //   elevation: 10,
  // },
});

export default ScanningScreen;
