/**
 * SponsoredBy Component
 *
 * Displays a full-screen animated sponsor splash with branded images.
 * Includes a fade-in effect and a close button to return to the main app.
 *
 * Key Features:
 * - Uses `Animated` API for smooth fade-in transition
 * - Shows sponsor and promotional images
 * - Closes when the user taps the "X" button, which navigates to IntroVidScreen
 *
 * Generated by Copilot AI
 */

import React, { useRef, useEffect } from "react";
import { Animated, Text, View, Image, StyleSheet } from "react-native";

import CloseButton from "../components/CloseButton";
import { auth, db } from "../config/firebase";
import { doc, getDoc } from "firebase/firestore";

const FadeInView = (props) => {
  const fadeAnim = useRef(new Animated.Value(0)).current;

  React.useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 6000,
      useNativeDriver: true,
    }).start();
  }, [fadeAnim]);

  return (
    <Animated.View
      style={{
        ...props.style,
        opacity: fadeAnim,
      }}
    >
      {props.children}
    </Animated.View>
  );
};

function SponsoredBy({ navigation }) {
  useEffect(() => {
    const timer = setTimeout(async () => {
      try {
        const user = auth.currentUser;

        if (user) {
          const userDoc = await getDoc(doc(db, "users", user.uid));

          if (userDoc.exists()) {
            const data = userDoc.data();

            if (data.showIntro) {
              navigation.navigate("IntroVidScreen");
            } else {
              navigation.navigate("AppNavigator");
            }
          } else {
            navigation.navigate("AppNavigator");
          }
        } else {
          navigation.navigate("AppNavigator");
        }
      } catch (e) {
        console.log("Navigation error:", e);
        navigation.navigate("AppNavigator");
      }
    }, 6000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <View style={styles.container}>
      <FadeInView
        style={{
          flex: 1,
          width: "100%",
          height: "100%",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <View style={styles.buttonContainer}>
          <CloseButton
            title="X"
            onPress={async () => {
              try {
                const user = auth.currentUser;

                if (user) {
                  const userDoc = await getDoc(doc(db, "users", user.uid));

                  if (userDoc.exists()) {
                    const data = userDoc.data();

                    if (data.showIntro) {
                      navigation.navigate("IntroVidScreen");
                    } else {
                      navigation.navigate("AppNavigator");
                    }
                  } else {
                    navigation.navigate("AppNavigator");
                  }
                } else {
                  navigation.navigate("AppNavigator");
                }
              } catch (e) {
                navigation.navigate("AppNavigator");
              }
            }}
          />
        </View>

        <Image
          style={styles.logo}
          source={require("../assets/sponsoredby.png")}
        />

        <View style={styles.sponsor}>
          <Image
            style={styles.sponsor}
            source={require("../assets/appsponsor.png")}
          />
        </View>

        <Image
          style={styles.bottom}
          source={require("../assets/adamapple.png")}
        />
      </FadeInView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    top: 65,
    width: 310,
    height: 240,
  },
  sponsor: {
    resizeMode: "contain",
    height: "50%",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  bottom: {
    height: 90,
    width: 85,
    marginBottom: 40,
  },
});

export default SponsoredBy;