/**
 * Vitamins Component
 *
 * Displays a scrollable list of vitamins and minerals from `vitaminlist.js`.
 * Each item links to the `GoodFood` screen with food sources for that nutrient.
 *
 * Key Features:
 * - Tappable list of nutrients with navigation
 * - Styled title and instructional note
 * - Uses green-themed design for clarity and consistency
 *
 * Generated by Copilot AI
 */

import React from "react";
import { FlatList, StyleSheet, View, ScrollView, Text, Platform, TouchableOpacity } from "react-native";

import AppText from "../components/AppText";
import AppButton from "../components/AppButton";
import Screen from "../components/Screen";
import colors from "../config/colors";
//import vit from "../config/vitaminlist";
import routes from "../navigation/routes";
import { FoodList } from "./FoodList";
import cats from "../config/categories";

//const vitamins = vit.vitamins;
const categories = cats.foodCategories;

//Displays list of vitamins and minerals
//When pressed, send the individual vitamin object to the FoodList screen
export const Vitamins = ({route, navigation}) => {

  const vit = route.params.vitamin;

    return (
      <Screen style={styles.screen}>
        <ScrollView
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          <AppText style={styles.title}>{vit.label}</AppText>
          <AppText style={styles.italic}>{vit.use}</AppText>

          <AppText style={styles.italic}>Commonly found in...</AppText>

          <View style={styles.listContainer}>
            {vit.linkTo.map(Food => (
              <View style={styles.buttonContainer} key={Food.toString()}>
                <TouchableOpacity
                  onPress={() => navigation.navigate('FoodList',{food: categories[Food]})}
                  style={[styles.button, { backgroundColor: categories[Food].buttonColor }]}
                  >
                    <Text style={styles.buttonText}>{categories[Food].label}</Text>
                </TouchableOpacity>
              </View>
            ))}
            </View>

        </ScrollView>
      </Screen>
    );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.light,
  },
  scrollContent: {
    paddingTop: 10,      // adds space under header before text
    paddingHorizontal: 15,
    paddingBottom: 80,  // ensures content is above bottom nav bar
    alignItems: "center",
  },

  title: {
    textTransform: "uppercase",
    color: 'black',
    fontSize: 40,
    marginBottom: 15,
    marginTop: 0,
    textAlign: "center",
  },
  italic: {
    fontStyle: 'italic',
    textAlign: "center",
    marginBottom: 20,
    fontSize: 15,
  },
  listContainer: {
    flex: 1,
    flexDirection: 'row', // Align children horizontally
    flexWrap: 'wrap',
  },
  buttonContainer: {
    // justifyContent: 'center', // Centers each row of buttons vertically
    alignItems: 'center', // Optionally, center items vertically
    padding: 10,
    width: '50%',
  },
  button: {
    height: 150,
    width: 150,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.eltrpink,
    // iOS Shadow properties
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    // Android Elevation property
    elevation: 4,
  },
  buttonText: {
    fontSize: 18,
    color: colors.white,
    textTransform: "uppercase",
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    fontWeight: "bold",
    position: 'absolute',
  },
  
});

export default Vitamins;