/**
 * This component defines a swipeable `ListItemDeleteAction` used to trigger deletion of a list item.
 * 
 * It displays a trash-can icon centered inside a red background container and responds to user taps via `TouchableWithoutFeedback`.
 * Typically used with swipeable list rows to reveal delete functionality.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { View, StyleSheet, TouchableWithoutFeedback } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";

import colors from "../../config/colors";

function ListItemDeleteAction({ onPress }) {
  return (
    <TouchableWithoutFeedback onPress={onPress}>
      <View style={styles.container}>
        <MaterialCommunityIcons
          name="trash-can"
          size={35}
          color={colors.white}
        />
      </View>
    </TouchableWithoutFeedback>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.danger,
    width: 70,
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
});
export default ListItemDeleteAction;
