/**
 * A simple horizontal separator used between list items.
 *
 * Renders a full-width, thin bar with the app's light background color to visually divide list entries.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { StyleSheet, View } from "react-native";
import colors from "../../config/colors";

function ListItemSeparator() {
  return <View style={styles.separator} />;
}

const styles = StyleSheet.create({
  separator: {
    width: "100%",
    height: 3,
    backgroundColor: colors.light,
  },
});
export default ListItemSeparator;
