/**
 * This code defines a stack navigator for managing user account-related screens in a React Native app using React Navigation.
 * 
 * It includes routes for viewing and editing account details, updating name, email, and password, managing allergies and conditions, and deleting the account.
 * Each screen is assigned a user-friendly title to enhance navigation clarity and accessibility.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { getSubScreenHeader } from "./HeaderStyles";

import AccountDetails from "../screens/AccountDetails";
import EditAccount from "../screens/EditAccount";
import EditAccountName from "../screens/EditAccountName";
import EditAccountEmail from "../screens/EditAccountEmail";
import EditAccountPassword from "../screens/EditAccountPassword";
import AccountAllergies from "../screens/AccountAllergies";
import AccountConditions from "../screens/AccountConditions";
import AccountDietaryPreferences from "../screens/AccountDietaryPreferences";
// import DeleteAccount from "../screens/DeleteAccount";

const Stack = createStackNavigator();

const AccountNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen
      name="Account"
      component={AccountDetails}
      options={({ navigation }) => getSubScreenHeader(navigation, "My Account")}	  
    />
    <Stack.Screen
      name="EditAccount"
      component={EditAccount}
      options={({ navigation }) => getSubScreenHeader(navigation, "Account Center")}	  
    />
    <Stack.Screen
      name="EditAccountName"
      component={EditAccountName}
      options={({ navigation }) => getSubScreenHeader(navigation, "Edit Name")}	  
    />
    <Stack.Screen
      name="EditAccountEmail"
      component={EditAccountEmail}
      options={({ navigation }) => getSubScreenHeader(navigation, "Edit Email")}	  
    />
    <Stack.Screen
      name="EditAccountPassword"
      component={EditAccountPassword}
      options={({ navigation }) => getSubScreenHeader(navigation, "Change Password")}	  
    />
    {/* NO LONGER USED - reference EditAccount.js for delete account feature */}
    {/* <Stack.Screen
      name="DeleteAccount"
      component={DeleteAccount}
      options={{ title: "Delete Account" }}
    /> */}
    <Stack.Screen
      name="AccountAllergies"
      component={AccountAllergies}
      options={({ navigation }) => getSubScreenHeader(navigation, "My Allergies")}	  
    />
    <Stack.Screen
      name="AccountConditions"
      component={AccountConditions}
      options={({ navigation }) => getSubScreenHeader(navigation, "My Conditions")}	  
    />
    <Stack.Screen
      name="AccountDietaryPreferences"
      component={AccountDietaryPreferences}
      options={({ navigation }) => getSubScreenHeader(navigation, "My Dietary Preferences")}	  
    />
  </Stack.Navigator>
);

export default AccountNavigator;