/**
 * This code defines a stack navigator for managing user account-related screens in a React Native app using React Navigation.
 * 
 * It includes routes for viewing and editing account details, updating name, email, and password, managing allergies and conditions, and deleting the account.
 * Each screen is assigned a user-friendly title to enhance navigation clarity and accessibility.
 * 
 * Generated by CoPilot AI
 */


import React, { useContext } from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { getSubScreenHeader } from "./HeaderStyles";
import AuthContext from "../auth/context";
import AccountDetails from "../screens/AccountDetails";
import EditAccount from "../screens/EditAccount";
import EditAccountName from "../screens/EditAccountName";
import EditAccountEmail from "../screens/EditAccountEmail";
import EditAccountPassword from "../screens/EditAccountPassword";
import AccountAllergies from "../screens/AccountAllergies";
import AccountConditions from "../screens/AccountConditions";
import AccountDietaryPreferences from "../screens/AccountDietaryPreferences";
import Firebase from "../config/firebase";


const Stack = createStackNavigator();
let word = "Hello world";
console.log(word+"1");


//const userName = useContext(AuthContext).user?.displayName;
const userName = AuthContext.user?.displayName;
console.log(word+"2");
//getAuth().currentUser
console.log(word+"3");
console.log(userName);

const usersAccount =userName+"'s Account"

const AccountNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen
      name="Account"
      component={AccountDetails}
      options={({ navigation }) => getSubScreenHeader(navigation, usersAccount)}
      /*
      .catch((error) => {
        console.error("Error writing document: ", error);
      })}
      */
    />
    <Stack.Screen
      name="EditAccount"
      component={EditAccount}
      options={({ navigation }) => getSubScreenHeader(navigation, "Account Center")}	  
    />
    <Stack.Screen
      name="EditAccountName"
      component={EditAccountName}
      options={({ navigation }) => getSubScreenHeader(navigation, "Edit Name")}	  
    />
    <Stack.Screen
      name="EditAccountEmail"
      component={EditAccountEmail}
      options={({ navigation }) => getSubScreenHeader(navigation, "Edit Email")}	  
    />
    <Stack.Screen
      name="EditAccountPassword"
      component={EditAccountPassword}
      options={({ navigation }) => getSubScreenHeader(navigation, "Change Password")}	  
    />
    <Stack.Screen
      name="AccountAllergies"
      component={AccountAllergies}
      options={({ navigation }) => getSubScreenHeader(navigation, "My Allergies")}	  
    />
    <Stack.Screen
      name="AccountConditions"
      component={AccountConditions}
      options={({ navigation }) => getSubScreenHeader(navigation, "My Conditions")}	  
    />
    <Stack.Screen
      name="AccountDietaryPreferences"
      component={AccountDietaryPreferences}
      options={({ navigation }) => getSubScreenHeader(navigation, "My Dietary Preferences")}	  
    />
  </Stack.Navigator>
);

export default AccountNavigator;