/**
 * This code sets up a stack navigator for advertisement-related screens using React Navigation in a React Native app.
 *
 * It includes a single screen, `SponsoredBy`, which is rendered without a header for a cleaner, distraction-free layout.
 * This navigator can be expanded to include additional promotional or sponsor-related views in the future.
 *
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";

import SponsoredBy from "../screens/SponsoredBy";
import IntroVidScreen from "../screens/IntroVidScreen";
import AppNavigator from "./AppNavigator";

const Stack = createStackNavigator();

const AdNavigator = () => (
  <Stack.Navigator screenOptions={{ headerShown: false }}>
    <Stack.Screen name="SponsoredBy" component={SponsoredBy} />
    <Stack.Screen name="IntroVidScreen" component={IntroVidScreen} />
    <Stack.Screen name="AppNavigator" component={AppNavigator} />
  </Stack.Navigator>
);

export default AdNavigator;