/**
 * This code defines the main bottom tab navigator for the app using React Navigation.
 * 
 * It organizes key sections of the app into accessible tabs:
 * - `Home`: the primary landing screen via `HomeNavigator`
 * - `Budget`: tracks user spending and budgeting
 * - `ScanningScreen`: launches the barcode scanner via a custom `ScanButton`
 * - `About`: provides app information and context
 * - `Settings`: routes to user preferences and configuration via `SettingsNavigator`
 * 
 * Each tab includes a MaterialCommunityIcons icon for visual clarity and intuitive navigation.
 * 
 * Generated by CoPilot AI
 */


import React, { Component } from "react";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { MaterialCommunityIcons } from "@expo/vector-icons";

import SponsoredBy from "../screens/SponsoredBy";
import HomeNavigator from "./HomeNavigator";
import BudgetNavigator from "./BudgetNavigator";
import ScanButton from "./ScanButton";
import ScanNavigator from "./ScanNavigator";
import RecipesNavigator from "./RecipesNavigator";
import SettingsNavigator from "./SettingsNavigator";
import routes from "./routes";

const Tab = createBottomTabNavigator();

// https://static.enapter.com/rn/icons/material-community.html for MaterialCommunityIcons

const AppNavigator = () => (
  <Tab.Navigator
    // hides the default header globally so we can add our own header styles
    // reference HeaderStyles.js to edit headers
    screenOptions={{
      headerShown: false,
    }}
  >
    <Tab.Screen
      name="Home"
      component={HomeNavigator}
      options={{
        tabBarIcon: ({ color, size }) => (
          <MaterialCommunityIcons
            name="home"
            color={color}
            size={size}
          />
        ),
      }}
    />
    <Tab.Screen
      name="Budget"
      component={BudgetNavigator}
      options={{
        tabBarIcon: ({ color, size }) => (
          <MaterialCommunityIcons name="currency-usd" color={color} size={size} />
        ),
      }}
    />
    <Tab.Screen
      name="ScanningScreen"
      component={ScanNavigator}
      options={{
        tabBarButton: (props) => <ScanButton {...props} />,
        tabBarIcon: ({ color, size }) => (
          <MaterialCommunityIcons
            name="barcode-scan"
            color={color}
            size={size}
          />
        ),
      }}
    />
    <Tab.Screen
      name="Recipes"
      component={RecipesNavigator}
      options={{
        tabBarIcon: ({ color, size }) => (
          <MaterialCommunityIcons name="book-open-outline" color={color} size={size} />
        ),
      }}
    />
    
    <Tab.Screen
      name="Settings"
      component={SettingsNavigator}
      options={{
        tabBarIcon: ({ color, size }) => (
          <MaterialCommunityIcons
            name="cog"
            color={color}
            size={size}
          />
        ),
      }}
    />

  </Tab.Navigator>

);

export default AppNavigator;


//name="Chatbot"
//component={AIChatbot}
//options={{ headerShown: false}}