/**
 * This code sets up a stack navigator for authentication-related screens in a React Native app using React Navigation.
 * 
 * It includes:
 * - `LoginScreen`: for user sign-in
 * - `RegisterScreen`: for new account creation
 * - `ResetPasswordScreen`: for password recovery
 * 
 * All screens are rendered without headers to provide a clean, full-screen experience during the authentication flow.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";

import LoginScreen from "../screens/LoginScreen";
import RegisterScreen from "../screens/RegisterScreen";
import ResetPasswordScreen from "../screens/ResetPasswordScreen";

const Stack = createStackNavigator();

const AuthNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen
      name="Login"
      component={LoginScreen}
      options={{ headerShown: false }}
    />
    <Stack.Screen
      name="Register"
      component={RegisterScreen}
      options={{ headerShown: false }}
    />
    <Stack.Screen
      name="ResetPassword"
      component={ResetPasswordScreen}
      options={{ headerShown: false }}
    />
  </Stack.Navigator>
);

export default AuthNavigator;
