/**
 * This code sets up a stack navigator for the Drive-Thru mini-game within Child Mode using React Navigation.
 * 
 * It includes three screens that guide children through a fun, interactive experience:
 * - `DriveThruWelcome`: introduces the game
 * - `DriveThru`: lets users choose a character and transportation
 * - `DriveThruDecision`: allows selection of a fast food restaurant
 * 
 * All screens are displayed without headers to maintain a full-screen, immersive gameplay experience.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { getSubScreenHeader } from "./HeaderStyles";
import DriveThru from "../screens/ChildMode/DriveThru";
import DriveThruWelcome from "../screens/ChildMode/DriveThruWelcome";
import DriveThruDecision from "../screens/ChildMode/DriveThruDecision";
import colors from "../config/colors";

//Create a new stack
const DriveStack = createStackNavigator();

//stack contains the various parts of the drive thru game
const DriveThruNavigator = () => (
  <DriveStack.Navigator
    screenOptions={{
      contentStyle: { backgroundColor: colors.eltrlightblue },
      gestureEnabled: false, // this prevents navigating to previous screens by swiping from left to right
    }}
  >
    <DriveStack.Screen
	    name="DriveThruWelcome"
      component={DriveThruWelcome}
      options={{ title: "Welcome Screen to Game", headerShown: false }}
	/>
    <DriveStack.Screen
	    name="DriveThru"
      component={DriveThru}
      options={{ title: "Character and Transportation Choice", headerShown: false}}
	/>
    <DriveStack.Screen
	    name="DriveThruDecision"
      component={DriveThruDecision}
      options={{ title: "Fast Food Restaurant Choice", headerShown: false}}
	/>
  </DriveStack.Navigator>
  );

export default DriveThruNavigator;
