/**
 * This code sets up a stack navigator for the Home section of the app using React Navigation.
 * 
 * It includes routes to educational and planning screens focused on nutrition and budgeting:
 * - `Home`: the main landing screen
 * - `FoodDye`, `Preservatives`, `Sugars`: ingredient awareness lists
 * - `Vitamins`: navigates to a nested vitamin and mineral explorer
 * - `Budgets`: helps users manage food-related expenses
 * - `Fats`, `Energy`: showcase healthy food categories for specific dietary goals
 * 
 * This navigator supports a structured, informative user experience around food choices and wellness.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";

import Energy from "../screens/EnergyPage";
import fa from "../screens/Fats";
import FoodDye from "../screens/FoodDye";
import Preservatives from "../screens/Preservatives";
import Sugars from "../screens/Sugars";
import Vitamins from "../screens/Vitamins";
import Budgets from "../screens/BudgetPage";
import Home from "../screens/Home";
import VitaminNavigator from "./VitaminNavigator";

const Stack = createStackNavigator();

const HomeNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen
	  name="Home"
      component={Home}
      options={{ title: "Home" }}
	/>
    <Stack.Screen
	  name="FoodDye"
      component={FoodDye}
      options={{ title: "List of Food Dyes" }}
	/>
    <Stack.Screen
	  name="Preservatives"
      component={Preservatives}
      options={{ title: "List of Preservatives" }}
	/>
  <Stack.Screen
	  name="Sugars"
      component={Sugars}
      options={{ title: "List of Sugars" }}
	/>
  <Stack.Screen
	  name="Vitamins"
      component={VitaminNavigator}
      options={{ title: "List of Vitamins & Minerals", headerShown: false}}
	/>
  <Stack.Screen
    name="Budgets"
      component={Budgets}
      options={{ title: "Budgeting Plans" }}
  />
   <Stack.Screen
    name="Fats"
      component={fa} //
      options={{ title: "List of Healthy Fats" }}
  />
 <Stack.Screen
    name="Energy"
      component={Energy} //
      options={{ title: "List of Energy-Filled Foods" }}
  />

  </Stack.Navigator>
  );

export default HomeNavigator;
