/**
 * This code customizes the default navigation theme for the app using React Navigation.
 * 
 * It overrides the default color scheme by:
 * - Setting `primary` to the app's custom primary color
 * - Changing the `background` to white for a clean, consistent look
 * 
 * This theme ensures visual consistency across navigators and aligns with the app's branding.
 * 
 * Generated by CoPilot AI
 */

import { DefaultTheme } from "@react-navigation/native";
import colors from "../config/colors";

export default {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: colors.primary,
    background: colors.white,
  },
};
