/**
 * This file defines a frozen object containing route name constants used throughout the app for navigation.
 * 
 * Each key maps to a screen identifier, ensuring consistent and typo-free references across navigators and components.
 * It includes routes for:
 * - Core app flows (`APPNAVIGATOR`, `SCAN_ITEM`, `FOOD_ITEM`)
 * - User account management (`ACCOUNT`, `ACCOUNT_EDIT`, `DELETE`, `RESET_PASSWORD`)
 * - Child Mode features (`CHILD_HOME`, `CHILD_SCAN`, `CHILD_BADGES`, etc.)
 * - Educational content (`DYES`, `SUGARS`, `VITAMINS`, `FATS`, `ENERGY`)
 * - Utility and support (`SETTINGS`, `HELP`, `ABOUT`)
 * 
 * Using `Object.freeze` ensures the route map remains immutable and safe from accidental modification.
 * 
 * Generated by CoPilot AI
 */

export default Object.freeze({
  APPNAVIGATOR: "AppNavigator",
  SCAN_ITEM: "ScanningScreen",
  ACCOUNT: "AccountDetails",
  ABOUT: "AboutScreen",
  ACCOUNT_EDIT: "EditAccount",
  ACCOUNT_ALLERGIES: "AccountAllergies",
  ACCOUNT_CONDITIONS: "AccountConditions",
  FOOD_ITEM: "FoodDetails",
  LOGIN: "Login",
  REGISTER: "Register",
  CHILD_ALERT: "ChildAlert",
  CHILD_SCAN: "Scan",
  CHILD_HOME: "Home",
  CHILD_FOODITEM: "ChildFood",
  CHILD_BADGES: "ChildBadges",
  CHILD_ABOUTFOOD: "ChildFoodAbout",
  CHILD_CHANGE: "ChildChangeMode",
  DELETE: "DeleteAccount",
  RESET_PASSWORD: "ResetPassword",
  SETTINGS: "SettingsScreen",
  DYES: "FoodDye",
  PRESERVATIVES: "Preservatives",
  SUGARS: "Sugars",
  VITAMINS: "Vitamins",
  BUDGETS: "Budgets",
  FATS: "HealthyFats",
  ENERGY: "AthleteFood",
  HELP: "HelpScreen",
});
