/**
 * This file defines a frozen object containing route name constants used throughout the app for navigation.
 * 
 * Each key maps to a screen identifier, ensuring consistent and typo-free references across navigators and components.
 * It includes routes for:
 * - Core app flows (`APPNAVIGATOR`, `SCAN_ITEM`, `FOOD_ITEM`)
 * - User account management (`ACCOUNT`, `ACCOUNT_EDIT`, `DELETE`, `RESET_PASSWORD`)
 * - Child Mode features (`CHILD_HOME`, `CHILD_SCAN`, `CHILD_BADGES`, etc.)
 * - Educational content (`DYES`, `SUGARS`, `VITAMINS`, `FATS`, `ENERGY`)
 * - Utility and support (`SETTINGS`, `HELP`, `ABOUT`)
 * 
 * Using `Object.freeze` ensures the route map remains immutable and safe from accidental modification.
 * 
 * Generated by CoPilot AI
 */

export default Object.freeze({
  //Account Pages
  APPNAVIGATOR: "AppNavigator",
  SCAN_ITEM: "ScanningScreen",
  ACCOUNT: "AccountDetails",
  ABOUT: "AboutScreen",
  ACCOUNT_EDIT: "EditAccount",
  ACCOUNT_EDIT_EMAIL: "EditAccountEmail",
  ACCOUNT_EDIT_NAME: "EditAccountName",
  ACCOUNT_EDIT_PASSWORD: "EditAccountPassword",
  ACCOUNT_ALLERGIES: "AccountAllergies",
  ACCOUNT_CONDITIONS: "AccountConditions",
  ACCOUNT_DIET: "AccountDietaryPreferences",
  //DELETE: "DeleteAccount", Lukas will need to add code back here!
  SETTINGS: "SettingsScreen",

  //Home & Food Pages
  FOOD_ITEM: "FoodDetails",
  DYES: "FoodDye",
  NUTRIENTS: "EssentialNutrients",
  FOOD_LIST: "FoodList",
  HARMFUL_INGREDIENTS: "HarmfulIngredients",
  FOOD_FACTS: "FoodFacts",
  PRESERVATIVES: "Preservatives",
  SUGARS: "Sugars",
  VITAMINS: "Vitamins",
  BUDGETS: "BudgetScreen",
  BUDGETING_BASICS: "BudgetingBasics",
  SAMPLE_BUDGET: "SampleBudget",
  STORES_SALES: "StoresSales",
  RECIPES: "Recipes",
  RECIPES_WANT_MORE: "RecipesWantMore",
  RECIPES_SUB_SCREEN: "RecipesSubScreen",
  FATS: "HealthyFats",
  ENERGY: "AthleteFood",
  HELP: "HelpScreen",

  //Login & Register
  LOGIN: "Login",
  REGISTER: "Register",
  RESET_PASSWORD: "ResetPassword",

  //Child Mode
  CHILD_ALERT: "ChildAlert",
  CHILD_SCAN: "Scan",
  CHILD_HOME: "Home",
  CHILD_FOODITEM: "ChildFood",
  CHILD_BADGES: "ChildBadges",
  CHILD_ABOUTFOOD: "ChildFoodAbout",
  CHILD_CHANGE: "ChildChangeMode",
});
