export default Object.freeze({
  APPNAVIGATOR: "AppNavigator",
  SCAN_ITEM: "ScanningScreen",
  ACCOUNT: "AccountDetails",
  ABOUT: "AboutScreen",
  ACCOUNT_EDIT: "EditAccount",
  ACCOUNT_ALLERGIES: "AccountAllergies",
  ACCOUNT_CONDITIONS: "AccountConditions",
  FOOD_ITEM: "FoodDetails",
  LOGIN: "Login",
  REGISTER: "Register",
  CHILD_ALERT: "ChildAlert",
  CHILD_SCAN: "Scan",
  CHILD_HOME: "Home",
  CHILD_FOODITEM: "ChildFood",
  CHILD_BADGES: "ChildBadges",
  CHILD_ABOUTFOOD: "ChildFoodAbout",
  CHILD_CHANGE: "ChildChangeMode",
  // DELETE: "DeleteAccount", // NO LONGER USED - reference EditAccount.js
  WELCOME: "Welcome",
  SETTINGS: "SettingsScreen",
  DYES: "FoodDye",
  PRESERVATIVES: "Preservatives",
  SUGARS: "Sugars",
  VITAMINS: "Vitamins",
  BUDGETS: "Budgets",
  FATS: "HealthyFats",
  ENERGY: "AthleteFood",
  HELP: "HelpScreen",
});
