/**
 * This component defines a custom `ScanButton` used in the app's bottom tab navigator to launch the barcode scanning feature.
 * 
 * It includes:
 * - A circular, elevated button styled with the app's primary color and white border
 * - A barcode icon from MaterialCommunityIcons
 * - A small "Scan Now!" label using the `AppText` component
 * 
 * The button is wrapped in a `TouchableOpacity` to handle user interaction via the `onPress` prop.
 * This design provides a visually distinct and interactive entry point for scanning functionality.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { View, StyleSheet, TouchableOpacity } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";

import colors from "../config/colors";
import AppText from "../components/AppText";

function ScanButton({ onPress, accessibilityState, navigation }) {
  return (
    <TouchableOpacity onPress={() => {
      if (accessibilityState?.selected) {
        navigation.popToTop();
      } else {
        onPress();
      }
    }}>
      <View style={styles.container}>
        <MaterialCommunityIcons
          name="barcode-scan"
          color={colors.white}
          size={30}
        />
        <AppText style={styles.text}>Scan Now!</AppText>
      </View>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderColor: colors.white,
    borderRadius: 40,
    borderWidth: 10,
    bottom: 40,
    height: 80,
    justifyContent: "center",
    width: 80,
  },
  text: {
    fontSize: 9,
    color: colors.white,
    fontWeight: "bold",
  }
});

export default ScanButton;
