/**
 * This code sets up a stack navigator for the scanning feature of the app using React Navigation.
 * 
 * It includes:
 * - `ScanningScreen`: where users can scan food items via barcode or image
 * - `FoodDetails`: displays nutritional and ingredient information about the scanned item
 * 
 * The navigator uses `mode="modal"` to present screens in a modal style, enhancing focus and user flow during scanning and review.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { getMainHeader, getSubScreenHeader, getSubScreenHeaderBack } from "./HeaderStyles";

import ScanningScreen from "../screens/ScanningScreen";
import FoodDetails from "../screens/FoodDetails";

const Stack = createStackNavigator();

const ScanNavigator = () => (
  <Stack.Navigator mode="modal">
    <Stack.Screen 
      name="ScanScreen" 
      component={ScanningScreen}
      options={getMainHeader("Scan Now!")}
    />
    <Stack.Screen 
      name="FoodDetails" 
      component={FoodDetails} 
      options={getSubScreenHeaderBack}
    />
  </Stack.Navigator>
);

export default ScanNavigator;