/**
 * This code sets up a stack navigator for the Settings section of the app using React Navigation.
 * 
 * It includes:
 * - `SettingsScreen`: the main settings interface
 * - `AccountDetails`: routes to account management via `AccountNavigator`
 * - `ChildAlert`: informs users about Child Mode activation
 * - `HelpScreen`: provides user assistance and guidance
 * 
 * This navigator organizes user preferences, account access, and support tools in one cohesive flow.
 * 
 * Generated by CoPilot AI
 */


import React from "react";
import { createStackNavigator } from "@react-navigation/stack";

import SettingsScreen from "../screens/SettingsScreen";
import AccountNavigator from "../navigation/AccountNavigator";
import ChildAlert from "../screens/ChildMode/ChildAlert";
import HelpScreen from "../screens/HelpScreen";

const Stack = createStackNavigator();

const SettingsNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen
	  name="Settings"
      component={SettingsScreen}
      options={{ title: "Settings" }}
	/>
    <Stack.Screen
      name="AccountDetails"
      component={AccountNavigator}
      options={{ headerShown: false }}	  
	/>
    <Stack.Screen
      name="ChildAlert"
      component={ChildAlert}
	  options={{ title: "Child Mode" }}
        />
    <Stack.Screen
      name="HelpScreen"
      component={HelpScreen}
	  options={{ title: "Help" }}
        />
  </Stack.Navigator>
);

export default SettingsNavigator;