/**
 * This code sets up a stack navigator for exploring vitamins and their food sources using React Navigation.
 * 
 * It includes:
 * - `Vitamins`: displays a list of essential vitamins and minerals
 * - `GoodFood`: shows foods rich in specific nutrients
 * 
 * This navigator supports educational features and helps users make informed dietary choices based on nutrient content.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { getMainHeader, getSubScreenHeader, getSubScreenHeaderBack } from "./HeaderStyles";

import EssentialNutrients from "../screens/EssentialNutrients";
import Vitamins from "../screens/Vitamins";
import Foods from "../screens/FoodsForVitamin";

//Create a new stack
const VitStack = createStackNavigator();

//stack contains the vitamins and foodforvitamin screens to navigate
const VitaminNavigator = () => (
  <VitStack.Navigator
    screenOptions={{
        headerTitleAlign: "center", // center the title
        headerTitleStyle: { fontSize: 18 },
        headerStyle: { backgroundColor: "white" },
      }}
  >
  <VitStack.Screen
	  name="EssentialNutrient"
      component={EssentialNutrients}
      options={({ navigation }) => getSubScreenHeader(navigation, "Essential Nutrients")}
	/>
  <VitStack.Screen
	  name="FoodList"
      component={Foods}
      options={({ navigation }) => getSubScreenHeader(navigation, "List of Foods")}
	/>
  <VitStack.Screen
	  name="Vitamins"
      component={Vitamins}
      options={({ navigation }) => getSubScreenHeader(navigation, "Vitamins")}
	/>

  </VitStack.Navigator>
  );

export default VitaminNavigator;
