/**
 * This code sets up a stack navigator for exploring vitamins and their food sources using React Navigation.
 * 
 * It includes:
 * - `Vitamins`: displays a list of essential vitamins and minerals
 * - `GoodFood`: shows foods rich in specific nutrients
 * 
 * This navigator supports educational features and helps users make informed dietary choices based on nutrient content.
 * 
 * Generated by CoPilot AI
 */

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";

import EssentialNutrients from "../screens/EssentialNutrients";
import Vitamins from "../screens/Vitamins";
import Foods from "../screens/FoodsForVitamin";

//Create a new stack
const VitStack = createStackNavigator();

//stack contains the vitamins and foodforvitamin screens to navigate
const VitaminNavigator = () => (
  <VitStack.Navigator>
  <VitStack.Screen
	  name="EssentialNutrient"
      component={EssentialNutrients}
      options={{ title: "List of Vitamins & Minerals" }}
	/>
  <VitStack.Screen
	  name="FoodList"
      component={Foods}
      options={{ title: "List of Vitamins & Minerals" }}
	/>
  <VitStack.Screen
	  name="Vitamins"
      component={Vitamins}
      options={{ title: "List of Vitamins & Minerals" }}
	/>

  </VitStack.Navigator>
  );

export default VitaminNavigator;
