/**
 * A wrapper component around Formik that sets up form state, validation, and submission handling.
 *
 * It receives configuration props and renders its children inside the Formik context,
 * allowing access to form values, errors, and handlers without manually wiring them up.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { Formik } from "formik";

function AppForm({ initialValues, onSubmit, validationSchema, children }) {
  return (
    <Formik
      initialValues={initialValues}
      onSubmit={onSubmit}
      validationSchema={validationSchema}
    >
      {() => <>{children}</>}
    </Formik>
  );
}

export default AppForm;
