/**
 * Displays a validation error message when the field has been touched and contains an error.
 *
 * If `visible` is false or `error` is empty, nothing is rendered. 
 * Otherwise, the error is shown in red text.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { StyleSheet } from "react-native";

import AppText from "../AppText";

function ErrorMessage({ error, visible }) {
  if (!visible || !error) return null;

  return <AppText style={styles.error}>{error}</AppText>;
}

function GoodMessage({ result, visible}) {
  if (!visible || !result) return null;

  return <AppText style={styles.good}>{result}</AppText>;
}

/*
//Want to integrate this later
function DisplayMessage({ result, visible, error }) {
  if (!visible || !result) return null;
  //OR if (!visible) return null;
  //with  if (error) 
  
  if(error==true)
  {
    return <AppText style={styles.error}>{error}</AppText>;
  }
  else
  {
    return <AppText style={styles.good}>{result}</AppText>;
  }
}

*/

const styles = StyleSheet.create({
  error: {
    color: "red",
  },
  good: {
    color: "green",
  },
});

export { ErrorMessage, GoodMessage };
export default ErrorMessage;