/**
 * Displays a validation error message when the field has been touched and contains an error.
 *
 * If `visible` is false or `error` is empty, nothing is rendered. 
 * Otherwise, the error is shown in red text.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { StyleSheet } from "react-native";

import AppText from "../AppText";

function ErrorMessage({ error, visible }) {
  if (!visible || !error) return null;

  return <AppText style={styles.error}>{error}</AppText>;
}

const styles = StyleSheet.create({
  error: {
    color: "red",
  },
});
export default ErrorMessage;
