/**
 * A button component wired to Formik's submission handler.
 *
 * Uses `useFormikContext` to access `handleSubmit`, triggering form submission when pressed.
 * Renders an `AppButton` with customizable title and color.
 *
 * Generated by Copilot AI
 */

import React from "react";
import { useFormikContext } from "formik";

import AppButton from "../AppButton";

function SubmitButton({ title, color, style, textStyle }) {
  const { handleSubmit } = useFormikContext();
  return(
    <AppButton
      title={title}
      onPress={handleSubmit}
      color={color}
      style={style}
      textStyle={textStyle}
    />
  );
}

export default SubmitButton;
